### ISSUE TITLE
Make messages pile under poster's nick

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#101]
Instead of:
`a: bla
a: bla bla
b: lol
a: bla lol`

It could be:
`a: bla
bla bla
b: lol
a: bla lol`

Just like in old synchtube, to save some precious space.

**Comment by calzoneman** [comment]
Just added this, did some local testing but it could use more.  Perhaps put up a test server?

**Comment by ghost** [comment]
I'm uploading the commit on my server, I like the risk :D

**Comment by ghost** [comment]
People say that timestamps should stay.

**Comment by calzoneman** [comment]
Out for a few hours but I can tweak that tonight

**Comment by calzoneman** [comment]
Should be fixed.
