### ISSUE TITLE
user controlled video delays

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#103]
Synchtube had a feature that let each user control how close they were from the timecodes read out. Like 5, 10, 15 or don't sync at all. 

This was great for people with high latency or flash issues.

**Comment by ghost** [comment]
+1

**Comment by calzoneman** [comment]
Easy option to add, but I don't think it really helps (this issue isn't the initial delay for buffering, because I'm compensating for that.  The issue is that it buffers slower than the playback speed, and I can't solve that).  Nevertheless I suppose I should add it.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/dd67179fd46d1c075ca2e813d445ec84de41e6e6
