### ISSUE TITLE
Account personalization

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#108]
- Avatars
- Short bios

I'd put profile settings in user options. Avatar and bio could be viewed by hovering over user name.

**Comment by calzoneman** [comment]
Not sure how I feel about this.  It wouldn't be hard to implement, but it's yet another thing to add to the UI and I'm not really sure what use it serves.

I never really used synchtube extensively so I'm not really aware of how this stuff was used.

**Comment by ghost** [comment]
When you have a channel with 50+ users it gets difficult to know who's who. It was really really useful on the community-based channels.

**Comment by Attiasthehun** [comment]
I'll support this its actually a great idea.
Just a Profile with an Avatar (Gravatar maybe) and a Box for some bio make it work with the Chat maybe.

So when you click people's name it opens they're profile in a new window or maybe a little hover box like Tinychat has it.

**Comment by calzoneman** [comment]
### IMPORTANT

Make sure you apply the SQL in the commit message to existing installations https://github.com/calzoneman/sync/commit/ebe48798fe37989712971d82924864d08c8d125d
