### ISSUE TITLE
Video preview in modal window, buttons in the playlist and library/youtube interface

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#109]

**Comment by calzoneman** [comment]
I'll probably just add something to open the playlist item in its respective website (YouTube/Vimeo/etc) rather than clutter it up with a video preview window.

**Comment by ghost** [comment]
Yeah, that's a better idea.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/3af35cb268cf96ae89ffaa3b35313938c1704d8e
