### ISSUE TITLE
Change "next" and "temp/untemp" with symbols to save some space

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#110]
- next: icon-step-forward or icon-share-alt
- temp: icon-time
- untemp: icon-time on red background
- preview(optional): icon-eye-open

**Comment by calzoneman** [comment]
Yeah, the playlist buttons are getting cluttered.  What I really need is a simply way to teach people what the playlist controls are.  The Next button actually used to be an icon, but I changed it because people kept thinking it was "play".  I'll probably go with icon-share-alt.

**Comment by calzoneman** [comment]
I'm thinking icon-fire or icon-flag for the temp, thoughts?

**Comment by ghost** [comment]
icon-flag would be ok
