### ISSUE TITLE
Informational: Detailed install instructions on CentOS

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#112]
here are my compiled notes on setting up CyTube on a fresh CentOS install. 

CyTube setup
Provision CentOS 
stop the httpd service from running at startup
yum install emacs (my preferred text editor)

Install GitHub
yum install git

Install Node.js version 10
yum install openssl-devel gcc-c++
cd /usr/local/src
git pull -b v0.10 https://github.com/joyent/node
cd /usr/src/node
./configure
make
make install

Install MySQL+tools
yum install mysql-server mysql php-mysql mysql-devel mysql-libs

Configure MySQL
mysql -u root (note you’ll want to set your mysql root pass to something other than the OS root pass)
create database syncdb;
grant usage on _._ to monty@localhost identified by ‘some_pass’;
grant all privileges on syncdb.\* to monty@localhost ;
(you’ll want to setup your own username and password, DO NOT JUST BLINDLY COPY)

Install Sync project
cd /usr/src/
git clone https://github.com/calzoneman/sync
cd /usr/src/sync
npm install

configure sync
cd /usr/src/sync
emacs config.js (db name is syncdb, user monty, pass some_pass, port 80)
cd /usr/src/sync/www/assets/js
emacs iourl.js (same info you put into config.js

start Sync
cd /usr/src/sync
nohup node server.js &

**Comment by calzoneman** [comment]
Thanks, added to a wiki page: https://github.com/calzoneman/sync/wiki/Installing#centos
