### ISSUE TITLE
Ubuntu Issue (Yet again)

### ISSUE THREAD

**Issue by Attiasthehun** [calzoneman/sync#114]
So last night we solved the other thing everything was setup and running.
even this morning.

Had everything running 3 hours ago and haven't touched a thing since, now for some reason i get on the computer and run the Server everything is fine its starts the server the database works as its suppose to.

But here's the issue when i run it on localhost it shows up loads the room but i cannot login as a guest or login at all, then when i try it online its just loading.

Its odd that it just stopped working out of the blue, any ideas?

**Comment by calzoneman** [comment]
Check that `IO_URL` as defined in `www/assets/js/iourl.js` matches the hostname and port of the server.

**Comment by Attiasthehun** [comment]
Yes i already checked that and everything is okay.

**Comment by calzoneman** [comment]
Is it giving you error messages about logging in or silently failing?  You can tell if your websocket is connected by the presence of a "n connected users" message above the chatbox.  If that message is not present, then you're not connected via websocket.

**Comment by Attiasthehun** [comment]
Nope no errors.

When i use localhost enter a room, it loads the room right.
But when i try to add a name and hit Guest login nothing happends, and no there's no 'Connected' Box so most be something with that what do you suggest.

Kinda confused not really sure why it does this all of a sudden.

**Comment by calzoneman** [comment]
Check your javascript console (Ctrl-Shift-J on Chrome, Ctrl-Shift-K on Firefox).  Also paste your config.js and iourl.js (with passwords removed) so I can look at it real quick.

You can also try restarting the server and seeing if there's any relevant errors or if that fixes the problem.  I'm assuming you're letting CyTube serve the web content, and you didn't copy the www folder to Apache, for example.

**Comment by Attiasthehun** [comment]
Ah figured it out, mistyped one number sorry about that, that was emberresing.
Just close this thanks again calzoneman
