### ISSUE TITLE
Remove Hardcoded Soundcloud Client ID

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#115]
https://github.com/calzoneman/sync/blob/master/get-info.js#L148

You probably don't want this in the source code. I'd remove it and provide instructions to get their own ID for people who are setting up the site for themselves. Without an ID soundcloud should be disabled with all soundcloud media being silently ignored.

**Comment by calzoneman** [comment]
I'll think about it.  It hasn't become an issue yet, and I was trying to avoid making people jump through Soundcloud's hoops (of all the APIs I had to deal with in this project, theirs is probably the worst).
