### ISSUE TITLE
Video Thumbnail Image

### ISSUE THREAD

**Issue by Attiasthehun** [calzoneman/sync#118]
Just an idea, style the index page a little maybe.
Where "Playing" is maybe have it show a Thumbnail image of what's being played.

I was looking through the Synchtube Web archive
http://web.archive.org/web/20130120214739/http://www.synchtube.com/

**Comment by ghost** [comment]
I'm against on this one, not really useful.

**Comment by Attiasthehun** [comment]
Well the good thing about it is that it gives users the ability to check whats being watched in the diffrent channels with one fast look instead of just text, an image can do better but ye it was just an idea.

Tells a bit more then just some text know what i mean.
another example www.st.localcraft.de

"Image Thumbnail" with "Online count" under it, and about text can be connected with MOTD.

**Comment by calzoneman** [comment]
I'm planning to add the ability to click playlist items to open them in a new tab.  I'll probably just do the same thing on the homepage.

CyTube supports many more media sources than YouTube, and as far as I know, the other APIs don't return preview images.

**Comment by Attiasthehun** [comment]
Oh yeah i forgot the other Media vendors yeah i see something like Twitch and LIvestream probaly dont i think Vimeo does tho and DailyMotion
Well if you do the Avatar thing, that could always be an option then do it like that maybe

Avatars not that important tho its just so its not all text, what i find most useful is the Channel Description.
With that users can easily find the room they belong to if they are Gamers or just people who are looking for a Room that plays they're type of music.

![cal](https://f.cloud.github.com/assets/4179355/493082/978508f0-bb18-11e2-8ccf-8808bae46bd9.jpg)

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/3af35cb268cf96ae89ffaa3b35313938c1704d8e
https://github.com/calzoneman/sync/commit/d9ed6655405fe1fe081672189a9bc63b39101643
Closing for now
