### ISSUE TITLE
Improve Password Storage

### ISSUE THREAD

**Issue by bgw** [calzoneman/sync#12]
Proper practice for password storing is:
- Hash on the server (not on the client)
- Use a (longish) salt
- Use a few hundred rounds
- Ideally use something like bcrypt instead of sha256, which is designed to be fast to compute on GPUs. (Crackers love that)

**Comment by calzoneman** [comment]
Ok, so if I were to implement bcrypt, I should generate a unique salt per-user and store that along with the hash in the database, correct?  What qualifies as "longish salt"?

Changing the code should be easy, the real challenge is going to be migrating existing hashes to the new algorithm.

**Comment by bgw** [comment]
Yes, that's correct. A longish salt, in my mind would be about 20 bytes. Just have some base salt, add in the username, and any other easily accessible information you have that doesn't change. You don't have to store the salt if you can just regenerate it every time (there's nothing wrong with storing it though). The point of the salt is to keep someone from hitting multiple users with one guess. They have to attack each user independently. It also breaks rainbow tables.

The most important thing with a salt is just to make sure that it is unique per-user.

---

To migrate users over, you can do it invisibly by rehashing their accounts when they log in next time. Just make sure to version your password storage mechanism.

**Comment by calzoneman** [comment]
Please look this over before I merge into master
https://github.com/calzoneman/sync/commit/34f20f423f821c55b0090421bb2ee551cfe32c16

**Comment by bgw** [comment]
@calzoneman Looks good to me. I don't know if you do this anywhere, but you might also want to limit password length to a thousand characters or something (just start truncating after that point), seeing as all your processing is synchronous and could block. (Potential for a DOS attack)

**Comment by calzoneman** [comment]
Yes, that's a good idea.  I've been meaning to implement such checks for chat messages as well, as one channel was recently raided by a 4chan member who flooded chat with massive blocks of text.

**Comment by bgw** [comment]
Jesus. You're already getting raided by 4chan?

**Comment by calzoneman** [comment]
Indirectly.  One of the My Little Pony subreddits was raided, in which someone had posted a link to their channel on my website.
