### ISSUE TITLE
Recreate the index.html and channel.html with use of fluid design

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#120]
With http://twitter.github.io/bootstrap/scaffolding.html#fluidGridSystem we can use more space on bigger resolutions.

**Comment by calzoneman** [comment]
I added a fluid layout option.  It's non-default in case there's something wrong with it.  It breaks all the other layout options.

EDIT: I mean when I make things fluid the other layouts break, hence why it's non-default.
