### ISSUE TITLE
MOTD window is not centered

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#121]
`<dragondread> Another quick question: Is there a way to center the MOTD for all window sizes? It seems that it's only centers when the window width is small
<dragondread> Oh sorry, I meant the whole box
<Czterooki> it's centered for me
<dragondread> Isn't it slightly to the right in respect to the whole window?
<Czterooki> oh, you're right
<Czterooki> I didn't even noticed that
<dragondread> Yeah slightly. When I put a banner via JS it becomes more obivous`

**Comment by Attiasthehun** [comment]
Just change the CSS settings.
offset1 to 28px;  and span10 to 95%;

**Comment by calzoneman** [comment]
It's not the same margin or width on different resolutions because Bootstrap is responsive.  I'll see if there's anything weird going on, or I might just make it a span12.

**Comment by ghost** [comment]
+1 for span12
