### ISSUE TITLE
manual send button on chat in addition to enter key

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#127]
I have a couple users that are connecting via various mobile devices that have requested this. some soft keyboards don't have an enter key that the chat interface recognizes.

**Comment by calzoneman** [comment]
Send buttons are ugly, I'd like to avoid it if at all possible.  I know of people using this on iOS and Android with soft keyboards, do you know which devices don't work?

**Comment by coconono** [comment]
Wii-U, PSP, Vita

**Comment by calzoneman** [comment]
Added this as a user option

**Comment by ghost** [comment]
![image](https://f.cloud.github.com/assets/3297156/519190/a0027b06-bf10-11e2-850d-0a962152f3be.png)
It doesn't look good ;/

**Comment by calzoneman** [comment]
Hmm, I hate dealing with multiple layouts.  Screw it, I'll probably just add it below the chatbox instead of trying to fit it next to the chat textbox on every layout.
