### ISSUE TITLE
License

### ISSUE THREAD

**Issue by czaks** [calzoneman/sync#13]
I really love this software. My users love it too. Modern, simple, elegant unlike most other synchtube clones. I've came across it just recently, searching for something that would suit our users after synchtube death.

What I didn't notice at the first glance is the non-standard and non-free license. Actually, some people in my environment would be very keen on contributing, but seeing this license, they are now wasting time searching for alternatives.

We are not really going to make it commercial product, but there are some things (like inclusion of google ads, combination with a whole product) that can't be done with CC BY-NC 3.0. Even if we, unlikely, went full-commercial, we see much profit with being open source.

Thus, I want to ask you to reconsider the licensing options. If you are a fan of Creative Commons, cc-by or cc-by-sa should suffice. If you happen to be afraid of the source of the code when it goes commercial, GNU AGPL should be ok. But if you happen to be a really kind person, please consider some license like zlib/libpng, MIT/X11 or BSD.

Yours sincerely,
Marcin Łabanowski on behalf of other vichan[1] staff and users.

[1] http://vichan.net/

**Comment by calzoneman** [comment]
Thanks for your input.  I started working on this long before Synchtube went down, and I never expected it to become popular.

I will probably relicense under cc-by-sa or MIT
