### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#131]
running 10.0 node.js

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.EventEmitter.addListener (events.js:160:15)
    at Socket.Readable.on (_stream_readable.js:653:33)
    at Socket.EventEmitter.once (events.js:179:8)
    at TCP.onread (net.js:512:26)

I think this is a node.js thing. But popping here to see if there's anything I should be doing running my server

**Comment by calzoneman** [comment]
This is a nodejs bug, specifically https://github.com/joyent/node/issues/5108.  The bug seems to happen on certain distros (I've reproduced it on CentOS and Debian but not on Arch).

What I've done to avoid this is download node v0.8.23 and compile it from source.
