### ISSUE TITLE
Mask IPs on Banlist

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#138]
You're masking IPs on the list of seen logins, but not on the banlist. You'll probably need some other mechanism to designate targets for unbanning.

**Comment by awused** [comment]
Actually I think you need to rework how you specify targets for banning as well. If someone types "/ban " or "/ban  range" they'll ban a random IP without a name attached. That probably isn't intended or desirable. Since you use hidden chat messages even for pushing buttons on the ban list it's impossible to specify individual unnamed users, not that there's much reason to.

It's also impossible to only ban certain usernames, or certain hosts. If users A and B share an IP, perhaps they are connected through a NAT device, I can't ban B without banning A. IP bans should still exist as a more final solution but being able to ban accounts is also desirable for less serious cases.

**Comment by calzoneman** [comment]
I'll check into the /ban issue.

I can add username bans if you think it would be useful, but given that they could immediately return with a guest login it would be about as effective as a kick.

**Comment by calzoneman** [comment]
Would it be more helpful if the banlist mirrored the seen logins for each banned IP instead of just the name it was banned under?

**Comment by awused** [comment]
Right now there's no middle ground between kicking someone and banning every IP they've ever been seen using. One idea would be to ban an IP shared by A and B but then specifically allow A's account. Perhaps a chat ban or something that could prevent IPs from chatting or interacting in any way besides just watching videos would be an easier to implement middle ground.

Having the banlist mirror the seen logins page would at least make it easier to realize if you've banned someone extra by mistake.

**Comment by calzoneman** [comment]
Whitelisting certain names on an IP sounds overly complicated, but doable.  I do intend to merge the bans and connection log into a nicer interface.

**Comment by calzoneman** [comment]
I think I've decided what I'm going to do.  Whitelisting names on an IP doesn't mesh well with my current system, which disconnects a banned IP immediately upon joining the channel (this is preferable because it prevents them from actually doing anything to the channel).

I'll probably add name-based bans (for registered names) and fix up the clientside to ban more precisely.
