### ISSUE TITLE
Forgot Password, Reset Password send email

### ISSUE THREAD

**Issue by Attiasthehun** [calzoneman/sync#139]
Needed yes? 
Forgot my password, had to make a new user would be nice if you made a Email sign up then you could make a 'Forgot Password' option.

Sadly some of us have the memory of a gold fish.

**Comment by calzoneman** [comment]
The reason I haven't done this yet is I haven't found a good way to do it.  The mailers I've found either require you to run an SMTP server (ugh) or use a gmail account, which I suppose isn't terrible.

**Comment by coconono** [comment]
Being able to have an admin to reset passwords would be nice too.

**Comment by nixonthekat** [comment]
This is actually a really nice idea.

**Comment by calzoneman** [comment]
The problem with admin password reset is there's no real way to verify who's asking you to reset the password (unless you know them in person).  Email is a better way to validate, I just need to come up with a good system for doing so.

**Comment by coconono** [comment]
most of my people contact me through alternate means like twitter, text or message boards. Those are about as secure as email validations. 

And frankly its not like we're storing any real serious info.

**Comment by Attiasthehun** [comment]
Oh alright, its just a matter of finding the right solution well i'll close this one you can re-open it in the future when you find something.
