### ISSUE TITLE
Banning no Longer Works

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#142]
Whether through /ban or the connection list I can't ban anyone.

**Comment by calzoneman** [comment]
I didn't actually roll out the ban update to my server yet.  Please note that you can't ban an IP if someone with higher rank than you (or equal rank) has logged on from that IP.

**Comment by awused** [comment]
It was a random spammer. No one else has used that IP. Even trying to ban random people doesn't work anymore.

**Comment by calzoneman** [comment]
I rebooted the server to apply the update, so you can try again now.

**Comment by awused** [comment]
I'm able to ban by IPs on the connection log, but not by names anymore. This includes typing "/ban <name>" and using the Ban Name button (the button doesn't send any frames at all).

There's also no indication on the ban list when you've banned a range of IPs instead of just one. 

It's also impossible to unban ranges, but I can unban single IPs just fine.

A banned IP range doesn't show up on the connection list like a regular banned IP.

**Comment by calzoneman** [comment]
Can you explain what you mean by "I'm able to ban by IPs on the connection log, but not by names anymore"?

I'm unsure if you mean "I am able to ban IPs from the connection log, but I cannot ban IPs by /ban name" or if you mean "I can ban IPs but not names"

**Comment by awused** [comment]
Oops, I was a little mistaken.

The Ban Name button does work, I just missed the frame. Typing /ban <name> should do the same thing but does nothing (sends a chat message which doesn't get relayed). Banning IP ranges works but doesn't show up on the connection list and you can't unban ranges.

**Comment by calzoneman** [comment]
/ban name actually still does an IP ban (assuming name is logged in.  If the person to be banned is not logged in, you must use connection log).  I should probably change that to /ipban and make /ban perform a name ban.

You can also ban names by clicking a row in the connection log to expand it.

Ban range issue confirmed, it was a small problem with a copy/paste.

**Comment by calzoneman** [comment]
Marking as closed unless you can still reproduce problems on latest version.
