### ISSUE TITLE
Clear the chat backlog

### ISSUE THREAD

**Issue by AKPWebDesign** [calzoneman/sync#143]
In my opinion, there should be a way to clear the chat that is shown on screen. Perhaps a '/clear' command that only moderators and up can use?

**Comment by calzoneman** [comment]
Yes, someone suggested this a while back in passing but never opened an issue so I forgot to add it.

**Comment by AKPWebDesign** [comment]
How hard is something like that to implement, out of curiosity?

**Comment by calzoneman** [comment]
The /clear command is trivial, just a command handler with a permission check.
