### ISSUE TITLE
a MOTD & CSS for the index page. 

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#147]
on http://sync.coconono.org I've been manually updating the index.html page. Which I have to move off when the code changes have been pushed down to change the behavior of the index page. 

So I was thinking for the person that has 255 rank, have an area where they can set the CSS style for the index page and also a place like in the channels where a MOTD can be set. 

This could be a part of the ACP.html page to keep the index page uncluttered.

**Comment by Attiasthehun** [comment]
For the "Rules" part.
You can do like Synchtube.irc has it 
Do a fast search for `<input type="text" id="channel" placeholder="Channel Name">`

Under that just add

```
<br>
<div class="well"><h3>Rules:</h3><ol>
<li>Don't be an asshole.
</li><li>report bugs to <a href="http://twitter.com/coconono">coconono</a>
</li><li>have fun
</li></ol>to keep the server running, feel free to toss a few dollars <a href="http://www.gofundme.com/2t8ifg">here</a>.</div>
```

**Comment by Attiasthehun** [comment]
I guess you can close this Calzone.
