### ISSUE TITLE
Library.

### ISSUE THREAD

**Issue by jlkwy** [calzoneman/sync#148]
I love the library feature, but after a while, there are so much items in there it makes the browser lag (a lot) when I open it. I'm sure it's mean to close when I press the button again but it doesn't, so for the moment I do a random youtube search and leave it at that to avoid having videos at 3fps and 200ms chat lag.
I'd like you to look into it, thanks.

**Comment by uchigawa** [comment]
How many items do you have in a library? I have tested it on my old laptop (Atom 1.33 GHz, 1GB RAM, Windows+Firefox) and I can see only a little performance decreasing, no bigger problems. >600 items in my library.

Anyway, if I understand you properly, you want to clear or hide somehow results of searching, right? It is very simple to do, even without such feature. Just paste in the `JS Editor` field below code:

`$("#queuerow .row-fluid .span7").removeClass('span7').addClass('span6');
$("#queuerow .row-fluid .span5").removeClass('span5').addClass('span6');
$("#youtube_search").after('<button class="btn" id="clear_search">✖</button>');
$("#clear_search").click(function(){$("#library").html('');$("#library_query").val('')});`

You'll be have a handy closing button.

**Comment by calzoneman** [comment]
I'll see where I can fit in a button to clear the search results.  The library is actually meant to be searched as well instead of listed out (since larger libraries have so many entries), but perhaps I can paginate it or something.

Actually, the library was originally just a way to cache video data so my server doesn't have to look it up every time; the fact that it's searchable is just a bonus.

**Comment by jlkwy** [comment]
I think paginating it would do the trick, like limiting it to 100 results per page. I don't know how many there are in the room I frequent, but it definitely makes it lag when I open it without making a precise search.

**Comment by calzoneman** [comment]
Added clear button and pagination per 100 videos.
