### ISSUE TITLE
Cannot make room public.

### ISSUE THREAD

**Issue by wololo420** [calzoneman/sync#149]
Despite ticking the 'make room public' box, my room still will not show up on the front page.

**Comment by calzoneman** [comment]
Did you click 'Save' to apply the settings?

**Comment by wololo420** [comment]
Yeah, it might be something to do with the length of the title. 
It's called Eternal_Kitchen_Nightmares

**Comment by jlkwy** [comment]
Might be unrelated, but underscores also make other stuff disfunction like twitch urls.

**Comment by calzoneman** [comment]
@jlkwy That's my fault for not knowing Twitch allowed underscores.

@wololo420 It actually doesn't have to do with the title, but the channel name itself.  I only recently began allowing underscores in channel names and I didn't update the validation regex on the channel view.
