### ISSUE TITLE
Login button not working

### ISSUE THREAD

**Issue by AKPWebDesign** [calzoneman/sync#155]
When I click the Login/Register button, the login window comes up. However, upon clicking the Login button there, nothing happens. I am on the latest Chrome, Windows 7 64-bit. In the Chrome console, I see quite a few errors, but one that may be related is this:

`Uncaught ReferenceError: Callbacks is not defined: /assets/js/iourl.js:23`

I also get an `Uncaught TypeError: Cannot call method 'postMessage' of null: functions.js:915` error, many times, throughout the time I am connected to the server.

**Comment by calzoneman** [comment]
Which website are you connecting to?

**Comment by AKPWebDesign** [comment]
Sorry, I guess that would be a good bit of information. I have an instance of the software running at http://futube.akpwebdesign.com

**Comment by AKPWebDesign** [comment]
I haven't changed the code any on my end, besides changing the name in the HTML files. I just pulled from here and changed the config files, then ran it. Up until today when I pulled the latest code, everything was working fine.

**Comment by calzoneman** [comment]
Please pull the absolute latest code, a view-source shows the channel.html page is slightly outdated.

**Comment by AKPWebDesign** [comment]
Alright. I have the latest code, as far as I can tell. Now, upon clicking login I get the following error:
`Uncaught TypeError: Cannot call method 'postMessage' of undefined; login.html:91`

**Comment by AKPWebDesign** [comment]
Note to self: When changing name of software for my server, be sure NOT to change names of internal variables. Sorry for wasting your time.
