### ISSUE TITLE
RE: Chat character limit (feature request)

### ISSUE THREAD

**Issue by sillybear25** [calzoneman/sync#156]
There is a character limit for chat lines, but chat lines are not split automatically, nor is there any indication to the user that they are going beyond the maximum length for a line. Instead, lines longer than the character limit are simply cut off at that limit.

Suggested solutions (ordered by estimated complexity to implement):
- Display a visual warning to the user if the entered line is longer than the character limit
  - Enhancement: Display the number of characters that remain or that the user has typed beyond the limit
- Prevent the user from entering lines longer than the character limit (ie: additional typed characters don't show up)
- Automatically split lines which are longer than the character limit
  - Enhancement: split lines at breaking characters (spaces, hyphens, etc.) if possible

**Comment by calzoneman** [comment]
I've been meaning to set the maxlength property on the textbox for a while, I just kept forgetting.  I won't implement line splitting, not because it's hard, but because it defeats the point of having a max message length.
