### ISSUE TITLE
Imgur galleries

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#158]
On the old synchtube sometimes we used to watch and discuss imgur galleries. Images are media too. Could you implement it? It is as simple as it can be - just an iframe with a direct link, no API needed.

Sample gallery:
`http://imgur.com/a/OrkDh`

You just add `embed` to the link to make it ready to put in an iframe
`http://imgur.com/a/OrkDh/embed`

**Comment by calzoneman** [comment]
As far as I can tell there's no way to synchronize which image is being viewed, but embedding the album is a snap.  If you find anything to the contrary let me know.

**Comment by uchigawa** [comment]
Actually I just wanted to embedding galleries, nothing more. It is enough for me, I do not even thought about synchronizing images ;)

**Comment by calzoneman** [comment]
Added in the dev branch.  Will make it into master in the next few days
