### ISSUE TITLE
Inconsistent channel rank behavior

### ISSUE THREAD

**Issue by taktoa** [calzoneman/sync#162]
The channel rank coloration behaves oddly when one tries to demote someone below the lowest rank. Also, when trying to promote/demote someone in the channel rank menu, if that person is not on the first page of people, it puts you back on the first page automatically, which is frustrating (this is evident on my channel on cytu.be, "fuspr").

**Comment by calzoneman** [comment]
You should never demote someone below rank 1 (I don't remember if I added a check for that or not) because rank 0 is reserved for guests and rank -1 for anonymous users.

I'll look into the page thing.
