### ISSUE TITLE
Connection Log cleaning

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#166]
Could you add a button to clearing (or leaving only 20 last items) the connections list?

I've got over 20 pages now, most of users have dynamic IP so after few days most of those data is useless for me.

**Comment by calzoneman** [comment]
Sure, I mwight also make it searchable by name

**Comment by calzoneman** [comment]
I might add a quick clear button to the current version, but I'm doing a major code cleanup and this will be further addressed there.

**Comment by calzoneman** [comment]
No longer relevant in v2.0 branch
