### ISSUE TITLE
Videos direct URL path

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#167]
I've just downloaded some video file from YT and I started to wondering - is it possible in this API to get somehow the direct URL path to YT (or others) video files? I've imagined a download button of current playing video, it would be a great feature for me.

Do you know how it works?

Treat this issue like question, not request.

**Comment by calzoneman** [comment]
I think most software that does this gets the data by scraping the website page.  It's not in the API, at least not in the part I'm using.

There are a number of extensions for [insert browser here] which allow you to download any youtube video on the page if you want to be able to download them while on the site, or there's an excellent piece of software called youtube-dl which can be used to download videos from the command line (supports a ton of different media sources - http://rg3.github.io/youtube-dl/)

**Comment by calzoneman** [comment]
Also, for the record, I'd be happy to discuss questions in the #synchtube channel on 6irc: http://webchat.6irc.net/?channels=synchtube
