### ISSUE TITLE
unable to create new accounts

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#168]
after doing latest code pull, users are no longer able to create new accounts. 

User receives error:
Registration Error. Contact an Admin for Assistance

there's nothing in the logs. Going to check the mysql logs and update if I find anything.

**Comment by calzoneman** [comment]
Which update are you talking about?  If you haven't updated since https://github.com/calzoneman/sync/commit/63e6cf380386e7a25f2834eed72e943c01129716 you need to run `node update.js` and edit your config.js because I added new columns to the database.

**Comment by coconono** [comment]
correct. that is what I updated to. can I run the update.js without bringing the server down?

**Comment by calzoneman** [comment]
I have no idea what would happen.  Seeing as you have a broken server anyways it needs to be restarted.

Shut it off, run update.js, turn it back on should take 30 seconds tops.

**Comment by coconono** [comment]
because I live dangerously, I ran it without bringing down the server and am now able to create new users.
