### ISSUE TITLE
Add multiple videos

### ISSUE THREAD

**Issue by waefort** [calzoneman/sync#17]
It would be easier if you could add multiple videos to the playlist at once.

**Comment by calzoneman** [comment]
You can queue YouTube playlists with URLs of the form
`http://www.youtube.com/playlist?list=(id)`

If you're referring to adding multiple individual videos, that's possible but I think the interface for such would be a bit clunky.  Part of the reason I added the library feature is to allow you to easily find and add videos that have been played before.

**Comment by calzoneman** [comment]
Given the number of errors in my error log resulting from people trying to queue multiple videos, I will add comma separation to the URL box.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/4e2702f65f4ea4ec05d79489f89ec338c7452a52
