### ISSUE TITLE
Any way we can get LiveLeak support?

### ISSUE THREAD

**Issue by AKPWebDesign** [calzoneman/sync#170]
It's not a big deal, but it would be cool if you could add support for http://www.liveleak.com/

**Comment by calzoneman** [comment]
I'll look into it later.  Working on a major code cleanup/update.

**Comment by calzoneman** [comment]
Couldn't find a javascript API for their player.  If you find one, let me know and I'll implement it.  I'm trying to avoid adding players that I can't synchronize.
