### ISSUE TITLE
Tolerance for Synchronizing

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#173]
I've noticed with a few videos in particular (and consistently those videos, and not other videos) that the audio drops out every 5 seconds as the `mediaUpdate` packets hit and cause it to seek to almost the same time.

If you don't have a tolerance for when it tries to resynchronize the video, you should add a small one. If you do have one (which I suspect) it needs to be increased, or the check needs to be fixed because it seems to always choose to seek for some specific videos.

http://www.youtube.com/watch?v=3ElAraY0X84 is one video for which the problem always occurs for me. When played in Cytube the video will re-seek every 5 seconds, causing the audio to drop out (it would also pause the video, but I've been unable to track down a video where this occurs that doesn't have a static image).

**Comment by calzoneman** [comment]
The tolerance is the synch accuracy option (default to within 2 seconds).  I had a similar issue where the audio would just glitch for a fraction of a second, and I haven't been able to figure out what causes it.  On certain videos, it even happens when I disable synchronization altogether.

**Comment by calzoneman** [comment]
I'm wondering if it's just an artifact of the way YouTube encodes certain videos (not all videos use the same codec).

**Comment by calzoneman** [comment]
Finding a video that does it consistently is a good start though, when I get a chance I'll load it up locally and check if the player gives any weird outputs when it queries the position to check if it should synchronize.

**Comment by calzoneman** [comment]
The numbers are checking out fine.  I'm thinking this might be an issue with YouTube's player, because I'm not doing synchronization any different from other videos.

**Comment by calzoneman** [comment]
I actually think I know why this was happening, and it's related to why Soundcloud playback was recently broken.

**Comment by awused** [comment]
I should add I was able to fix it for that video in particular by increasing the tolerance. So it's almost certainly something to do with that.

**Comment by calzoneman** [comment]
Actually no, I confirmed multiple time through debug print messages that there was no seeking taking place during the skips.

However (and I didn't think about this before), I am calling `play` on every packet for which `paused` is `false`.  My suspicion is that calling this on the YouTube player causes it to seek to the nearest keyframe.

The proper way to do this is to query the player for whether it is paused, and only call `play` if it is not already playing.
