### ISSUE TITLE
My first impressions about the new version

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#174]
1. Could you wrap all the content of `#main` and `#playlistrow` into additional `<div class="span12"><div class="row">` blocks?
   It is necessary, because currently we have limited possibilities to create more advanced layouts, we can't even set simple properties like the same background for the left and right pane, not to mention about things like borders. This is a good occasion to fix it.
2. I would like to see an optional user option for playlist, displays all the buttons like on the old version (only buttons with icons, without captions).
3. `Moderation Menu` is on the bottom of the channel, so I think it is more convenient to have menu above the button (dropup instead of dropdown).
4. Maybe closing button instead of `Hide Menu` option?
5. I think `Retrieve playlist URLs` option should be deleted from permissions editor and be available for every user. I visit many channels and most of admins give all the permissions for at least leaders/moderators. I don't like it, because I want the lists ;) Normal users should have possibility to get them, playlist is not a secret.
6. I miss multiple filters updating form. I use it all the time.

That's all for now.

**Comment by calzoneman** [comment]
1. I'll look into it, but nesting span12s sometimes causes weird results (if you look at the CSS, I had to manually apply `margin-left: 0` to `#leftpane-inner div.span12` and similar containers)
2. _sigh_ I made the buttons appear by default at the request of people in IRC (I actually prefer the old 2.0 default - no buttons until right clicking; had I known I would get such a strong negative response I would never have implemented it).  I'd like to avoid duplicate code, but perhaps I can add a check to remove the text for you.
3. ~~Hmm, I'm going to have to disagree there, I think dropups would be disorienting, especially given the size of some of the mod menu panels~~
   EDIT: OH, I see what you mean.  I'll see if I can make it drop up easily.
4. Yeah that could work
5. ~~The only problem with this (and actually I hadn't thought about it until now) is that it's wrapped inside the playlist controls pane, which means that unless you have permission to add links you can't see the button.  I'd like to avoid cluttering the page, but I might have to move that button next to voteskip to get it to work~~  Changed this
6. Believe it or not, I actually did think about this (although you're the only person in the history of the software to talk about its use).  I was worried it might confuse people to have 2 ways of inputting filters, but I suppose I could add it back.

**Comment by calzoneman** [comment]
Re point 3: I changed it to a dropup.  It feels a bit weird, but so does the dropdown so I'm not really sure which I like better

Re point 4: Added a "x" button to the right (would it be more clear if it were a chevron icon or something?)

Re point 5: Turns out I wasn't actually doing a permissions check anyways due to the way it was implemented, so it was totally pointless.

**Comment by uchigawa** [comment]
1: I looked to the bootstrap code and it seems span12 nested in another span as a single column always have 30px left-margin. But if you nest 2 or more columns, first left column will have no margin at all.

This is exactly my proposition  - nesting span5 `leftpane-outer` and span7 `rightpane-outer` in a span12 (as well as `chatwrap` and `videowrap` in `main`).

I did some magic in custom JS to change this and it works just it should. Not even slightest difference on the screen, but now I can customize all the CSS just like I want.

So I think you can risk, we'll see if something go wrong.

2: Sorry ;_; I didn't know so many people request those changes. `qbtn_idontlikechange` in this case you have right, I think I used to it.

3-5: Thank you so much.

6:

> you're the only person in the history of the software to talk about its use

Because nobody had to set manually 100 filters on 10 different channels xD

**Comment by calzoneman** [comment]
1. Ok, I'll look into it.  If it wasn't clear, I wasn't flat-out denying it, I was just saying I didn't know off the top of my head whether it would work.
2. It's not your fault.  I'm sure part of it is people being used to the old version, and perhaps the other part is that I just didn't guess correctly how much people rely on the buttons.  The name `qbtn_idontlikechange` was a little joke.
3. If you're having to duplicate the same filters on a bunch of channels, perhaps there's a better way for me to approach this.  Would it be more useful to be able to copy the channel settings from one channel and paste them into another?
