### ISSUE TITLE
[v2.0] little bugs

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#175]
1. After properly adding a new filter in the Chat Filters section, an additional empty filter is appearing.
2.  After creating and opening a new poll, poll menu form is not closing.
3. Will you add back Clear Results button in a Library section? Quite useful for me.

After a few days I am starting to like this new version, it looks great,

**Comment by calzoneman** [comment]
1. I'll look into it, I don't remember that happening when I tried it but maybe I broke something
2. Yes, I guess it should do that
3. forgot.  I'll put it back

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/8c9cbca4c428d1bc0d78890e95cd07ac343d09eb

2 and 3 are fixed.  I could not reproduce 1 on Chromium or Firefox.

**Comment by uchigawa** [comment]
I've got this problem:

![filter](https://f.cloud.github.com/assets/4163505/691583/9987b2b8-db9f-11e2-9332-d6512c7a4afe.jpg)

Additional empty filter is appearing after adding a new filter. But only once - if I add another filter, nothing wrong is happen. But when I delete this filter, it appears again after adding the next one.

I don't know how is it possible. Win 7 x64, Firefox 21.0. Of course no add-ons, no channel scripts, cleared cookies etc.

**Comment by calzoneman** [comment]
Are you clicking the add filter button or pressing enter?  What it looks like to me is that the new filter callback is being triggered twice.

**Comment by calzoneman** [comment]
I reproduced the issue, so I can look into it now.  Not sure why it wasn't happening before.

**Comment by uchigawa** [comment]
It happens after clicking and after pressing enter too.
