### ISSUE TITLE
Skipping Parts of Videos

### ISSUE THREAD

**Issue by BasedGodLuki** [calzoneman/sync#179]
It'd be awesome if the leader of rooms skips a part of a video, it would skip to that part for everybody in the room.

**Comment by calzoneman** [comment]
It...does.  That's literally how leader works.

Marking as invalid unless you can provide an example in which it doesn't work, which would be a bug.

**Comment by BasedGodLuki** [comment]
I tried yesterday and you couldn't skip any parts of videos, neither could you stop the video, I'll try it again today.
Thanks and keep up the good work :)

**Comment by calzoneman** [comment]
Just to be clear, you have to manually assign leader in order to use that function.  By default the server uses an internal timer.

Right click your name in the userlist and select "make leader" and then the seeking and pausing functions will work.

**Comment by BasedGodLuki** [comment]
Oh awesome, it's working now, thank you !
