### ISSUE TITLE
[](/ppshrug) Registration Failed.

### ISSUE THREAD

**Issue by skorotkiewicz** [calzoneman/sync#18]
When trying to register an error "[](/ppshrug) Registration Failed."
mysql database connection exists, the database is in mysql

**Comment by calzoneman** [comment]
Are you using the latest version?  If so, check error.log for "Auth.register: DB Connection failed".  If you get that message, then it can't connect to the database.

Make sure the username you configured has write permission on the database.

**Comment by skorotkiewicz** [comment]
s15433203:/var/synchtube# cat error.log 
[04:13:01] Append to chanlogs/Developers.log failed: 
[04:13:01] Error: ENOENT, open 'chanlogs/Developers.log'
[04:13:16] Append to chanlogs/Developers.log failed: 
[04:13:16] Error: ENOENT, open 'chanlogs/Developers.log'
[04:15:39] [SEVERE] Uncaught Exception: Error: ENOENT, no such file or directory 'chandump/Developers'
[04:15:40] [SEVERE] Uncaught Exception: Error: ENOENT, no such file or directory 'chandump/Developers'
[04:18:46] Append to chanlogs/lol.log failed: 
[04:18:46] Error: ENOENT, open 'chanlogs/lol.log'
[06:45:49] Append to chanlogs/test.log failed: 
[06:45:49] Error: ENOENT, open 'chanlogs/test.log'
[06:45:57] Append to chanlogs/lol.log failed: 
[06:45:57] Error: ENOENT, open 'chanlogs/lol.log'
[06:46:49] Append to chanlogs/test.log failed: 
[06:46:49] Error: ENOENT, open 'chanlogs/test.log'

Is connected to the base,  because automatically created a database
s15433203:/var/synchtube# node -v
v0.8.8
s15433203:/var/synchtube# npm -v
1.1.59

![2013-03-31-13-16-28](https://f.cloud.github.com/assets/899351/321620/81673f74-99f4-11e2-92ae-f9b64163b1df.png)

**Comment by calzoneman** [comment]
From your error log, I don't see anything relevant to the problem (there is another issue I will explain below).  Please try adding a row manually from phpMyAdmin with the MySQL user/pass you defined in config.js.  It seems odd that it would have permission to create tables but not insert into them, but that's the only case I can think of where this error would come up.

Out of curiosity, can you provide the name you were trying to register?

Please create the directories "chanlogs" and "chandump", I didn't realize that node's `fs` module didn't create them if I tried to write to a file inside a nonexistent directory.

**Comment by skorotkiewicz** [comment]
With a user and PHPMyAdmin correctly added data.
So there is no problem with permissions.

A few tried to register the name, the user "test" with password "testtest"

What encryption uses a Register, because I would like to manually add a new user from PHPMyAdmin

**Comment by calzoneman** [comment]
It uses bcrypt (https://npmjs.org/package/bcrypt).

I'll try setting this up on a clean server to see if I can reproduce your issue, because I don't really know why this is happening.

EDIT: I'm not sure if it's related, but I just noticed you're using a really outdated version of node (0.8.8).  I'm using v0.10.0.  If your OS's repositories only have the outdated version, you can easily build node from source by downloading the tarball from their website.

**Comment by calzoneman** [comment]
I just fixed it, it was an issue with the database initialization not setting `AUTO_INCREMENT` on the `id` field.  You may either use phpMyAdmin to add the `AUTO_INCREMENT` property to the `id` column on the `channels` and `registrations` tables, or update the software, drop the tables and let it regenerate them.

https://github.com/calzoneman/sync/commit/802cb199763cb9201f56da9db153827573abcb65
https://github.com/calzoneman/sync/commit/c97e6f3f84e5ca9967cdc213f1dfc9af4e285899
