### ISSUE TITLE
"Allow usage of channel's custom CSS and JS" option in User Options

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#181]
This way user can choose whether custom channel CSS is being loaded or the one chosen in User Options (Default/Dark/Hybrid etc.) Also JS for privacy paranoids and those who prefer vanilla interface.

**Comment by calzoneman** [comment]
So basically, if the option is checked, the CSS and JS should be processed normally, otherwise it should act as if the channel is vanilla.

**Comment by ghost** [comment]
Exactly
