### ISSUE TITLE
Playlist Race Conditions

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#182]
Since you use indices for identifying videos rather than any kind of unique identifier there exist a lot of race conditions.

The easiest to conceive is two users (or one bot cleaning checking a list for invalid videos naively) delete two videos in rapid succession. Say user A deletes video 3, and user B deletes video 4. If user B's frame arrives first there's no problem, the desired videos will be removed. If user A's frame arrives first then videos 3 and 5 will be deleted instead of the desired 3 and 4.

Similar issues exist for sending `delete` and `play` frames at the same time. Or multiple people moving videos around (though you can never truly make this one race-proof).

Two solutions seem obvious. They're not mutually exclusive. 
1) Limit directly changing the playlist to the leader of the room. This is a pain for everyone involved (especially going back to the old takeLeader shtick for Naoko) but doable.

2) Assign a uid to each video. Instead of sending `{"args": [<index>], "name": "delete"}` clients would send `{"args": [<uid>], "name": "delete"}`. This is probably the best solution and can probably make some parts of the backend nicer.

**Comment by calzoneman** [comment]
TCP guarantees data to be received in the correct order, it's only the async callbacks that can finish out of order.

I started fixing this by adding a wait check for playlist movement, I just need to add one for additions and deletions and all of these bugs should be fixed.

I'd like to avoid option 2 if at all possible because some rooms have obscenely large playlists and the time taken to iterate across the whole thing and compare ids would be wasteful.

**Comment by calzoneman** [comment]
Option 2 also becomes an issue given that I allow the same video to exist more than once in the playlist.

**Comment by calzoneman** [comment]
Just comment here if the issue returns and I'll reopen this one instead of creating new issues.

**Comment by awused** [comment]
TCP doesn't help when it's two different users acting on the same playlist from different clients. Please think through the examples I posted. The point of a UID is to be unique, as in you don't repeat it, so having the same video multiple times on a playlist doesn't cause an issue. As in you're using a random hash or something instead of the youtube ID.

This is completely unrelated to issue #180 which deals with a single client and asynchronous javascript.

**Comment by calzoneman** [comment]
Has this actually been an issue or are you just speculating?

**Comment by calzoneman** [comment]
I'll look into tagging each media item with a unique hash

**Comment by awused** [comment]
Also how large is obscenely large? Even in javascript I can't see even naive linear scans of the playlist being an issue unless the playlists are literally tens or hundreds of thousands of videos long. If you're dealing with playlists that long you're probably using a database to store them, and then you can stick an index on `UID` or `UID, index` to solve the lookup issue for another few orders of magnitude. Clients can just linear scan it no matter the length since, relative to a server under load, cpu time is cheap on clients.

**Comment by awused** [comment]
Right now I've only run into it with my bot (as in she checks the list, sees videos 3 and 4 are invalid, and sends two deletes in rapid succession. This leads to videos 3 and 5 being deleted, and 4 remains on the list.) But the possibility exists for any two users who just happen to take actions at the same time. Or one user clicking delete on two videos _really_ fast.

Edit: Internally, for Naoko alone, my easiest solution would be to tag individual videos with UIDs when they get added, and use that  and a combination of waiting for responses from the server (and all the tedium that goes with handling cases where a response never comes - like if she didn't have permission) so that Naoko would never conflict with herself. But then she could still conflict with regular users, and regular users could still conflict with each other.

**Comment by calzoneman** [comment]
Actually, I'm not worried about the server.  I recently had to change the way playlist buttons are added because adding the buttons to a 1,400 video playlist froze Chromium for several seconds (this was an issue on /x/'s channel).

Obviously lookups are a lot cheaper than DOM manipulation, so on second thought it might not be an issue.

The playlist actually is stored in RAM rather than the database, so server lookup time is cheap.  The hashes have to be generated dynamically anyways to prevent duplicate playlist items from having the same id.

**Comment by calzoneman** [comment]
I'll have to test this out, I'm not sure how much additional load it will add to the server

**Comment by calzoneman** [comment]
I'm actually going to change the way this works slightly.  It's not necessary to use a hash, I can just use an auto incrementing integer.

Even if you added a video every second and never restarted the server, the counter wouldn't overflow in my lifetime.

**Comment by awused** [comment]
As long as you treat it the same way (not assuming it'll be ordered) that'll be fine.

**Comment by calzoneman** [comment]
Yeah, I'm basically just ripping out the hashes and replacing them with unique integers.  Integers are much, much faster than md5 hashes for generating and comparing.
