### ISSUE TITLE
Empty btn-group With display: none

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#183]
Seemingly randomly on page load the first several videos (most often the first two) will have an empty `btn-group` with `display` set to none. I suspect a race condition when the playlist is first created.
![playlist_empty_btn-group](https://f.cloud.github.com/assets/1551320/712431/e728acae-dea9-11e2-8773-b339207e4ea8.jpg)

**Comment by awused** [comment]
Also to be clear, I didn't hide the buttons by right clicking. I can hide the buttons for the videos that show buttons, and bring them back, but these videos simply do not have buttons to unhide.

**Comment by calzoneman** [comment]
I know what's causing this
