### ISSUE TITLE
Videos Added as Temporary Videos Have Incorrect Button Displayed

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#184]
Videos added in the temporary state have the `Make Temporary` button instead of the `Make Permanent` button.

![wrong_buttons](https://f.cloud.github.com/assets/1551320/712920/2273b6a4-deb5-11e2-80c8-536264041f28.jpg)

**Comment by awused** [comment]
Yeah I never even noticed, but the button still sends the wrong frame. It says Make Permanent now, but it still sends `setTemp`: true when it should be false.

**Comment by calzoneman** [comment]
Tickets are on hold until this weekend
