### ISSUE TITLE
Lost Channel Administrator Status

### ISSUE THREAD

**Issue by DoctorCogs** [calzoneman/sync#190]
To make a long story short, I created the room and got assigned the Channel Administrator status; however, for some reason I opened the same room in another tab, and was kicked automatically because "Double Login". When I re-entered the room, I discovered I had lost my Admininstrator status and functions, and now the channel has no Administrators or Mods.

Is there any way to fix this issue? Or at least to request the channel's deletion since it's useless by now?

**Comment by calzoneman** [comment]
Did you actually register the channel before this occurred?

**Comment by DoctorCogs** [comment]
No; I'm sorry, I know I probably screwed up hard by now.

**Comment by calzoneman** [comment]
Alright, well if you don't register the channel then it just gives admin to the first person to enter it.  If you can get everyone to leave the channel it should unload and be reset.

**Comment by DoctorCogs** [comment]
Alright then, thank you.

EDIT: It worked, thanks for answering this petty careless idiot's question.
