### ISSUE TITLE
Exclude afk users from voteskip pass counter

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#193]

**Comment by nuclearace** [comment]
I think you should also exclude people in chat-only mode from skips.

**Comment by calzoneman** [comment]
Nope, would be too easy for someone to fake.

**Comment by calzoneman** [comment]
Also if you're in chat only there's not even a voteskip button; you'd have to manually send the packet

**Comment by nuclearace** [comment]
But aren't they making it harder for people who want to skip?

**Comment by nuclearace** [comment]
Yes, but how many people would know they can do that? Let alone actually take the time to do it?
