### ISSUE TITLE
Empty Playlist Index

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#194]
I've noticed that the new `setPosition` will send 0 for the current position in an empty playlist where the old `setPlaylistIdx` sent -1. Since you are using 0-indexed arrays this seems like an unintended change. I am not sure when it started since the playlist is never empty.

**Comment by awused** [comment]
Similar issue so I'll post it here:

If you clear a playlist (of, say, 5 videos), you'll get two `playlistMeta` frames _after_ the playlist is cleared. One sill say it's 5 videos long, which is incorrect now, and the other will say 0 videos. The first, errant, one should not be sent to clients.

**Comment by calzoneman** [comment]
UID experimenting is happening in the dev branch.  If that works out, this won't really be relevant
