### ISSUE TITLE
HTTPS-Everywhere Firefox addon makes embedded YouTube return error

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#195]
Ubuntu Linux 10.04 (lucid)
Firefox 20
HTTPS-Everywhere 3.2.3 addon (https://www.eff.org/https-everywhere)
Channel: http://cytu.be/r/animu

Disabling the rule for YouTube in HTTPS-Everywhere allows the embedded YouTube videos to play normally.  The rule for YouTube is enabled by default.  Enabling the rule for YouTube makes the embedded player display an error message.  The player and its controls appear, but instead of the video buffering inside the player, an error appears with a black background.

**Comment by calzoneman** [comment]
This is a known issue and I'm not sure how much I can do about it (see http://code.google.com/p/gdata-issues/issues/detail?id=4299).

I can try loading the iframe API over HTTPS, but that didn't correct the issue for the person in that thread.

**Comment by calzoneman** [comment]
Looks like this is something I can't really fix, at least not without switching the whole server over to use SSL.  I've toyed with the idea of supporting SSL, and I might implement it one day.
