### ISSUE TITLE
Firefox's dom.storage.enabled config variable must be set true

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#197]
With Firefox on any CyTube channel, the `dom.storage.enabled` variable in Firefox's `about:config` list must be set to **true**.

I had set it to false to deter persistent cookies, reduce website tracking, and increase privacy.  Most sites don't need it and load fine without it.  I wish CyTube didn't require it.  The variable isn't configurable for different sites (unless you install a separate addon), so now with it enabled, all sites can store persistent cookies.

Edit:
At the time this issue was posted, this is what CyTube looked like with `dom.storage.enabled` set to **false** (disabled): http://i.cubeupload.com/a3k103.jpg  (For anyone accessing an older version.)

**Comment by calzoneman** [comment]
I'm using localStorage to store user options (login credentials are stored in regular, expiring cookies).  If there exists an easy way to check if localStorage is enabled, I will add a fallback of just setting/getting a cookie.

Just curious, what's to stop a site where localStorage is disabled from just setting a cookie with an expiration so long that it is, for all intents and purposes, infinite?

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/6a6dd7bc211dfd0f495a79dd343ffe28e1741065

**Comment by ipatjolvur** [comment]
> what's to stop a site where localStorage is disabled from just setting a cookie with an expiration so long that it is, for all intents and purposes, infinite?

The major difference I'm concerned about is whether the browser provides adequate enough access to view, delete, or filter the objects in localStorage.  Firefox, for example, provides access to _regular_ cookies and offline website data, but the DOM storage area is [not as accessible](http://developer.mozilla.org/en/docs/DOM:Storage#Storage_location_and_clearing_the_data).

Worse yet, if the browser does not provide enough access for managing localStorage, regular and DOM objects can be used as "[redundant backups](http://www.whatwg.org/specs/web-apps/current-work/#user-tracking) for each other."  I've had this happen to me recently.  A particular cookie, even when all cookies were deleted, would reappear.  I do not know whether Firefox can yet delete objects from DOM storage when the program closes, the way it already can for regular cookies, offline data, cache, etc.

**Comment by calzoneman** [comment]
Although I have implemented a fallback to regular cookies in my software, I encourage you to contact major browsers about your concerns.  It's a real shame for new features to be added that web developers are discouraged from using.
