### ISSUE TITLE
Chat-only with hide video

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#198]
I seem to be unable to turn on chat-only mode when I have the hide video option enabled.

**Comment by calzoneman** [comment]
Note to self https://github.com/calzoneman/sync/blob/master/www/assets/js/util.js#L1219 and the problem is `fluidLayout()`

**Comment by nuclearace** [comment]
Also, while this may seem pointless since a refresh would do the same thing, why not change the chat-only button to "Video-mode" when someone enters chat-only mode. Thus clicking it would take them back to the video layout.

**Comment by calzoneman** [comment]
Not really possible given that chat only mode removes a decent portion of the DOM.
