### ISSUE TITLE
Keep Playing Current Video When Videos Are Added to An Empty Playlist

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#199]
With the "new" `changeMedia` there's no longer a need to instantly skip to the first video added when the playlist is empty. Users who join the room will see the video they should be seeing. So you can wait until the video is done to jump to the first video.

Likewise, if a video is deleted it shouldn't be skipped, it should be treated as a video "before" the playlist is playing, and when it finishes the first video on the playlist will play.

**Comment by calzoneman** [comment]
Point 1 is debatable.

I disagree on point 2, I often delete videos to skip them.  It seems unnecessarily complex to have to delete and then click play on the next one.

I think it also creates a semantic issue to have a video playing that isn't on the playlist.

**Comment by calzoneman** [comment]
It sounds to me like you are basically describing a video which is temporary but invisible.
