### ISSUE TITLE
Youtube keyword browsing

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#20]
One of most basic features to implement, supplemental to the media library..
https://developers.google.com/youtube/2.0/developers_guide_protocol_category_keyword_browsing

**Comment by calzoneman** [comment]
I'll look into it.  If I can find a way to implement this without making the interface more cluttered than it is, I'll go for it.

**Comment by calzoneman** [comment]
I will probably integrate this with the library search.  However, at the moment I want to do a feature freeze and reorganize some code to prevent this from becoming too messy.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/362fd0ab236a47136d100a30fb5475cf51a52b80
