### ISSUE TITLE
Glitched 0 Second Video

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#200]
http://www.youtube.com/watch?v=nCVUhHK5c_Y

I don't know why, but cytube thinks this video is 0 seconds long. It's not an API error, Naoko knows it's actually 92 seconds long.

This leads to an annoying loop where Naoko won't add new videos and won't delete it because to her, someone is deliberately restarting it so it isn't a normal transition. But cytube will jump to 0:00 every five seconds.

This might be a caching issue where you failed to get a response from Youtube and cached a null response, but that's just a guess on my part.

**Comment by calzoneman** [comment]
It is a caching issue, because I confirmed that it loads correctly on a fresh channel.  I checked the database row, and the title was fetched properly but for some reason `seconds` was set to 0.

I'm not really sure how to reproduce this, but you can force a refresh of the API data by deleting it from the library and adding it again.

Is Naoko leading?  If the server was leading, and it wasn't skipping a 0 second video, then there is a further bug here.

**Comment by calzoneman** [comment]
As a tagentially related bug, you can actually cache live media by marking them as un-temporary.

**Comment by awused** [comment]
What was happening was Naoko naturally adding and deleting videos from the playlist. She happened to add this one, and cytube skipped it. But once Naoko finished the last video that was the only video left on this list. Since the video wasn't finishing normally Naoko wouldn't add more videos. Naoko uses a naive heuristic to determine whether a video is finishing normally or if it's been skipped/restarted by a user.

You might want to handle very short videos (whether legitimately short or through another bug like this) specially, like forcing them to be temporary, to alleviate this issue. In rooms without Naoko a situation like this would be rarer but still annoying.

**Comment by calzoneman** [comment]
I see

**Comment by calzoneman** [comment]
Perhaps you should have Naoko look at the playlist data that the server sends and compare the video lengths.  If they don't match, you could have it automatically send the "uncache this" message and re-add the video.

**Comment by awused** [comment]
I noticed with your `uncache` frame you don't specify the type of video. If there's a collision between two video hosts that could cause unwanted deletions. Not that that's very likely.

Also how long do you keep those caches around? One issue if you keep them around for more than a few days is that videos will often get removed from Youtube.

**Comment by calzoneman** [comment]
I'll consider it for the future.

**Comment by awused** [comment]
Well, I did add something to Naoko that should handle cases like this by skipping the video and uncaching it.

**Comment by calzoneman** [comment]
There is currently no cache expiry because the library is the cache.  I've been thinking about separating out caching into a global table of all videos from all channels, and setting a TTL on them.
