### ISSUE TITLE
Double changeMedia/setCurrent

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#203]
Right now the server sends two sets of these frames when the video changes.

Also they are sent in the opposite order they were sent before. It used to be `changeMedia` then `setPosition`. Now it's `setCurrent` first followed by `changeMedia`.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/blob/master/playlist.js#L438 is a duplicate of L436 of the same file.
