### ISSUE TITLE
Allow playlist to be paused

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#213]
Request:
Add a new Permission option to allow users to pause the playlist (preferably mid-video, but between videos would be acceptable, too).  The permission could be set for X user-level or above like the other permissions.

**Comment by nuclearace** [comment]
You could just use leader...

**Comment by calzoneman** [comment]
@nuclearace is correct. The proper way to do this is to give leader to someone which gives them control of the current video. This user can then pause or seek.

**Comment by calzoneman** [comment]
For clarification of why I won't implement a non-leader permission for this: allowing more than one person to control the active video is a disaster waiting to happen. This is why I decided to synchronize server side

**Comment by ipatjolvur** [comment]
Ah, I see.  I thought with how the permissions are set up, anyone above leader rank would be able to pause or seek.  It wasn't working for me with moderator or above.  I didn't know you had to be leader, exclusively, even if you have admin rank.  The FAQ doesn't explain that too well.

Thank you.

**Comment by calzoneman** [comment]
Leader is a special case because there can only be one at a time. I explained it briefly under the section where I explained the user list controls, but I suppose adding a more prominent paragraph won't hurt.
