### ISSUE TITLE
Loading Justin Tv brings in an ad

### ISSUE THREAD

**Issue by diboy2** [calzoneman/sync#216]
I got the following alert box blocking the video. "Twitch is for gaming content only." The box blocks half off the screen making the streaming unwatchable.

**Comment by calzoneman** [comment]
I'll look into it tomorrow. Away from computer at the moment but I suspect the wrong player is being loaded

**Comment by diboy2** [comment]
Here's an example link http://www.justin.tv/twit#/w/6107025456/91. I'm using google chrome. 

edit: the latest google chrome.

**Comment by calzoneman** [comment]
I checked and the player is indeed being loaded from Justin and not twitch. Are you sure you are properly linking a Justin stream? http://justin.tv/channelname.  I have not tested it with prerecorded content but I suspect it would not work.

**Comment by calzoneman** [comment]
If you are streaming through twitch, use twitch.tv as the stream URL

**Comment by diboy2** [comment]
yup, it doesn't work. Here's another link with ur format. http://www.justin.tv/hlctv. It doesn't work either. Ustream also doesn't work anymore. It worked last week. Here's the link I was suppose to watch with my friends today. http://www.ustream.tv/channel/elaina1205-kyr. It also worked with prerecorded content, since the ustream link was offline and it still showed images. The error message for ustream is "The page requested cannot be found." I also tried removing my css code, user script, and title picture. It still didn't work. My channel is http://synchtube.6irc.net/r/infinite_channel.

**Comment by calzoneman** [comment]
If you will re-read the supported media providers section of the FAQ, you'll notice that the link format for ustream is http://ustream.tv/channelname without the additional /channel/.  Ustream didn't make it clear to me what the difference between the 2 syntaxes is but right now only the first will load properly.

**Comment by diboy2** [comment]
oh, ok. That's weird. All the ustream links that I use have this syntax http://ustream.tv/channel/channelname. If I use  http://ustream.tv/channelname, it doesn't load correctly. Here's what i get if I use that syntax, http://www.ustream.tv/hydroplane-quebec. If you click on this link, that's the message I'm getting on the player.  I'm wondering why my ustream links worked a week ago. Maybe ustream doesn't use that link format anymore. Oh, and thank you for taking the time to answer my requests.

**Comment by calzoneman** [comment]
I will look into it, but I think internally ustream has different types of things that they call "channels" and I'm not really sure which is which.

**Comment by calzoneman** [comment]
Ustream is one of the providers that I'm regexing the player ID out of the HTML because their API is so badly explained I have no idea how it works

**Comment by diboy2** [comment]
RE: i've also tested it with a this syntax(http://ustream.tv/channelname) and it works on the browser. However, it displays the same error if I load it on the player. http://www.ustream.tv/nasahdtv

**Comment by diboy2** [comment]
Ok, so I used fiddler2 for web debugging and I'm getting this error "HTTP/1.1 404 Not Found". Hope this helps.

**Comment by diboy2** [comment]
thank you.

**Comment by calzoneman** [comment]
Just dumb mistakes and oversight, this should have been fixed a while ago but I guess JTV and Ustream just don't get used that often
