### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by diboy2** [calzoneman/sync#219]
I get the following error. "The connection was reset. The connection to the server was reset while the page was loading." It was working this morning. Now I can't even enter the site.

**Comment by diboy2** [comment]
Fiddler gives me this error "[Fiddler] ReadResponse() failed: The server did not return a response for this request."

**Comment by nuclearace** [comment]
That is a connection problem.

**Comment by diboy2** [comment]
Is it working on your computer? It doesn't seem like a client problem since the client sent the server request. The other websites I go to are working perfectly. I can't even join the support chat.

**Comment by calzoneman** [comment]
@diboy2 the CyTube server located at http://synchtube.6irc.net is currently down.  In the meantime you may use my server, http://cytu.be.

For news or general questions, you can join #synchtube on irc.6irc.net (webchat here: http://webchat.6irc.net/?channels=synchtube)

**Comment by diboy2** [comment]
Thank you!!! :smile:
