### ISSUE TITLE
Links No Longer Work

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#222]
Links of the form http://cytu.be/?channel=animu no longer seem to work in any browser. They display an empty channel list.

http://cytu.be/r/animu seem to work but you seem to be having site issues or something right now. They display the room but never make the websocket connection, but they were working yesterday.

**Comment by nuclearace** [comment]
When I click on your first link it brings me to your room. Is it not working for you?

**Comment by awused** [comment]
Actually, so much for "any" browser. Neither will work in Firefox or Chrome, but both will work in Opera. Opera is my main browser but for work I generally have Chrome and FF up, so I normally have cytube on a chrome window on my second monitor.

Restarting the browsers does not fix the issue.

**Comment by nuclearace** [comment]
I'm using Chrome for Mac and it is working for me. I just tried FF and it worked.

**Comment by awused** [comment]
Welp, seems restarting my computer fixed issues in Chrome and Firefox. Guess my computer just had brain problems.

I did notice some javascript errors (trying to call a function before it was initialized) but they're still there and don't seem to impede loading.

**Comment by calzoneman** [comment]
Both links confirmed working.

Occasionally you get a reference error for YT if the `changeMedia` packet comes before the YTAPI is loaded, but it doesn't break anything because the client automatically requests another `changeMedia` when the API fires the ready callback.

**Comment by calzoneman** [comment]
@Suwako worth noting that ?channel= syntax is deprecated and relies on a client side redirect. /r/channel directly loads channel.html

**Comment by awused** [comment]
Actually I'm not sure what causes this, but it happened again. Windows Chrome just would not work on any link. However when I logged in to Cytube on Opera (invalidating the session in the Chrome cookie) Chrome started working again.

It doesn't seem to be a link issue. I'll try to gather more information if it happens again and see if I can't open a better issue.

**Comment by awused** [comment]
Okay, it seems a lot of people are having connectivity issues stemming from cookies (well they're fixed when they clear their cookies). I'm not sure what exactly triggers it, I will try to gather more information, but I thought I'd let you know in case you knew of anything that could be causing this.

**Comment by calzoneman** [comment]
Any information you can figure out would be great. I have not experienced this issue on chromium, Firefox, or Midori (all latest versions in the Archlinux repos).

I only use cookies to store login sessions, so if somehow you get a bad cookie it should still load the channel but just not auto login.

Are you sure you're not clearing something else at the same time? Does clearing the cache help?

**Comment by calzoneman** [comment]
Also if you find any uncaught exceptions at the global level that might be relevant.
