### ISSUE TITLE
Temporary videos scroll playlist 2 items on completion

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#225]
When a video marked as "temporary" completes, the next video is played, but the playlist scrolls up 2 entries instead of 1, making the newly-playing video scroll up and out of the visible area.  Videos marked as "permanent" do not have this happen, properly scrolling to make the newly-playing video appear at the top of the visible playlist area.

**Comment by nuclearace** [comment]
I've noticed this as well. Calzoneman is out of town but he'll look into it when he gets back.

**Comment by calzoneman** [comment]
It actually only scrolls up one video. However, the scroll occurs before the deletion of the temp video. I might be able to reverse the order without breaking anything.
