### ISSUE TITLE
Voteskip feedback

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#227]
Something I see people saying a lot is "Voteskip isn't doing anything." I suggest changing the button so clicking it once makes it un-clickable again until the next video. Another way could be to change the text to something like, "Voteskipped."

**Comment by calzoneman** [comment]
Doesn't it already do that? It should have the disabled attribute after being clicked

**Comment by nuclearace** [comment]
Well, it doesn't let them vote twice but, I seem to be able to click it again.

**Comment by calzoneman** [comment]
Apparently I haven't vote skipped anything since v2.0

**Comment by nuclearace** [comment]
``` javascript
$("#voteskip").click(function() {
    socket.emit("voteskip");
    $("#voteskip").attr("disabled", true);
});
```
