### ISSUE TITLE
Channel Dumping on SIGINT

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#228]
Channels don't seem to be dumping when the server is shut down. I've tested it on milkbartube.com and when I load a channel back up it is using the last five min dump.

**Comment by nuclearace** [comment]
I'm actually unsure if it is now, I paid attention to the chat buffer more than actual channel stuff. Probably should pay attention next time you have to restart. Its probably just my paranoia.

**Comment by calzoneman** [comment]
On SIGINT, CyTube will print "unloading channels", unload all channels, and then print "goodbye".

If Config.DEBUG is set to true then the default SIGINT handler is used which simply kills the process.

**Comment by calzoneman** [comment]
Can you confirm that this is behaving correctly?

**Comment by calzoneman** [comment]
I think I know what might be broken
