### ISSUE TITLE
mediaUpdate and changeMedia no Longer Sent with Empty Playlist

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#230]
If the playlist is empty mediaUpdate and changeMedia frames are no longer sent. This means, among other things, synchronization doesn't work and new users will not see the current video.

Also Naoko won't realize when the current video is almost done.

**Comment by calzoneman** [comment]
If the playlist is clear, the server abandons playback. It does not explicitly tell the client to stop playback but simply stops sending synchronization.

This is intended behaviour.

If it would make it more clear, I can explicitly unload the player when the playlist is cleared during a video

**Comment by calzoneman** [comment]
Any synchronization of media not on the playlist during previous versions was an unintended feature and has never been officially supported
