### ISSUE TITLE
Custom html5 service support?

### ISSUE THREAD

**Issue by digited** [calzoneman/sync#233]
Hi, I've done an foss Qt app that streams audio/video to html5 javascript wrapper around html video element.

http://code.google.com/p/vocatube-webseed-client/

Try video: http://vocatu.be:39390/traptrap.vs.html
audio: http://vocatu.be:39390/omega_dubstep_animation_t.vs.html

.vs is stream itself (raw file), vs.json will show you JSON with tags, mime, length etc

Since Chrome and Firefox now play both mp4 and .webm, mp3 and .ogg vorbis as html5 source element, and most users use those two browsers, format wars around html5 are sort of settled atm.

The point is:
YouTube mostly has crappy audio quality, NND has no API at all, and when users want to stream their stuff, they use twitch.tv/ustream with tons of ads and crappy quality of everything, if not paid. So they all suck.

My app allows instant streaming of audio and video into browsers (from those with real IP and set port forwarding/routing). In highest quality possible - any bitrate for vp8 + ogg q10, best h264 + aac 600-700 kbps. If user has decent bandwidth, and there aren't too many users in room, that's an ideal and fastest way to stream media from your pc into browsers.

JS player is wrapper around html5 video element, so anything there can be controlled - seeking, volume, play/pause/stop, js callbacks on player events.

There's a dozen of ppl who use that app for half a year or more, and it's quite handy. We'd use it in r/mikuchan here for sure.

**Comment by calzoneman** [comment]
If you can provide some kind of API documentation I might do this eventually, but be warned my TODO list is rather long at the moment.

I have also been wanting to add a generalized way for people to play a custom iframe or something on their page instead of implementing a hundred different indie stream services.

**Comment by digited** [comment]
@calzoneman 
I'll roll out some javascript API then.

It should be noted that for my - or maybe any? - player's script to work, your server should allow browsers' js to do cross-domain requests, as js asks for stream from a completely different IP (seeder's). If you already allow it, no problem.

**Comment by calzoneman** [comment]
The HTML5 APIs I already use have players embedded in `iframe` tags that communicate with `postMessage`.  I'm not sure how cross-domain ties into that, but it definitely will be an issue to consider when implementing your API.

**Comment by digited** [comment]
I'll change messaging to use postMessage then.

**Comment by calzoneman** [comment]
Also worth noting that in the upcoming `v2.3` release, I will support embedding custom `iframe` or `object` (flash) players.  I can't support synchronization without an API, so it acts like a livestream.
