### ISSUE TITLE
actionlog table filled up

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#236]
got a bunch of alerts that no one could log in or show up as guest.

I get this from error.log:
[Tue Jul 30 2013 20:35:54] ! Failed to check tooManyRegistrations
[Tue Jul 30 2013 20:35:54] ! Failed to record action
[Tue Jul 30 2013 20:38:24] ! Failed to record action
[Tue Jul 30 2013 20:38:42] ! Failed to record action
[Tue Jul 30 2013 20:38:48] ! Failed to record action
[Tue Jul 30 2013 20:38:55] ! Failed to record action
[Tue Jul 30 2013 20:39:04] ! Failed to record action
[Tue Jul 30 2013 20:39:13] ! Failed to record action
[Tue Jul 30 2013 20:42:06] ! Failed to record action
[Tue Jul 30 2013 20:46:40] ! Failed to record action

last time I saw this, the actionlog table table was corrupt(select \* from actionlog; returned that table was crashed) so I fixed that by running CHECK TABLE actionlog;

this time the actionlog returned clean. I ran a script to show if other tables were corrupt. None were.

to resolve, I took a backup of the db, dropped the actionlog table, and ran node update.js to regenerate it. 

now users are back in business. 

Is there a max cap for each table?

**Comment by calzoneman** [comment]
How many rows were in there?  You would have to consult the MySQL documentation to see if there are limits to table size.

If the table was corrupt, I would suspect disk corruption, perhaps from a cold reboot.

**Comment by calzoneman** [comment]
BTW, the regular server script automatically regenerates missing tables.  `update.js` is only used when an update involves modifying existing tables.

**Comment by coconono** [comment]
ok, that makes sense.

http://dev.mysql.com/doc/refman/5.0/en/table-size-limit.html shows the max table size is limited to disk space a few other particulars. So i'm going to go with possible bad corrupt filessystem, I'll run a fsck on it later. 

Are there any pruning routines we need to be running against the actionlog to keep it from growing to unmanageble sizes? 

We've had a couple memory leaks with the node process forcing a server crash and reboot. I've been meaning to get around to implementing a memory limiter on the node process but haven't had a time to test it in my dev environment.

**Comment by calzoneman** [comment]
In the next release I will only record `login-success` for administrators, which will save a lot of space.  I generally clear `login-failure` and `login-success` fairly often to keep it slim.

Which version of node are you using?  I ran for almost 7 days straight with consistent memory usage.

**Comment by calzoneman** [comment]
Marking this as closed unless you can determine the fault.
