### ISSUE TITLE
When the window is resized, YouTube videos grow too large to fit in the screen

### ISSUE THREAD

**Issue by mattalxndr** [calzoneman/sync#241]
This is happening in Chrome for Linux and Firefox for Linux.

I believe this is where it's happening:

https://github.com/calzoneman/sync/blob/a2fd40dd247e3913f5abc300ebc04a2f0cb623d5/www/assets/js/ui.js#L342

EDIT: I see the problem here, if it helps: http://cytu.be/r/fullmoviesonyoutube

**Comment by calzoneman** [comment]
What's your screen resolution?

I just tried resizing the window on my laptop to a variety of sizes and it seemed fine (both on Default and Fluid layouts).  I'm using FF 22.0 on Linux

This is on my 1366x768 laptop, I haven't tested my desktop but it worked fine the last I remember

**Comment by calzoneman** [comment]
Just tried on my 1080p monitor, I can't reproduce this with any combination of layouts and browsers.

**Comment by Reload3r** [comment]
I wanted to say that this happens alot while watching stuff from Vimeo aswell.
It seems to work sometimes, sometimes it just breaks for everyone in a channel.

**Comment by mattalxndr** [comment]
http://cytu.be/r/fullmoviesonyoutube

I see the problem here, if it helps.

I will flesh out my bug report or maybe fire up the debugger later.

**Comment by nuclearace** [comment]
I'm going to guess this is a browser specific problem. Because resizing works fine for Chrome on Mac. What layout are you using.

**Comment by mattalxndr** [comment]
Check out my link above for the layout.

**Comment by mattalxndr** [comment]
Also, I doubt it's a browser specific problem since it happens in both Chrome and Firefox.

**Comment by nuclearace** [comment]
I know what the problem is. That channel has custom JS that is playing with things. Tell me if disabling custom JS fixes it.

**Comment by nuclearace** [comment]
They were hiding part of the layout for ranks below mod. Which must be causing issues

**Comment by calzoneman** [comment]
Ah I see, fullmoviesonyoutube is one of those channels that hides the playlist.  I'm currently using the width of the playlist div to calculate the player size.

I'll look into adding an empty container at the bottom of the page with the same CSS class as the playlist and using that instead.

**Comment by calzoneman** [comment]
This is solved per https://github.com/calzoneman/sync/commit/15085fc6ae48f34638e0525c29a08669ad371913

Please note that you may need to clear your cache to see the changes.

**Comment by mattalxndr** [comment]
Thanks for fixing it so fast. @calzoneman
