### ISSUE TITLE
Typing "month=8" in MOTD displays "m".

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#250]
Typing "month=8" in the MOTD displays only "m". A URL with that parameter (&month=X) gets truncated after the "m" until a space character is reached. The truncation also removes the `">` if the URL is inside an HTML anchor tag.

**Comment by calzoneman** [comment]
Overzealous XSS filter, I'll look into it.  The literal text "month=8" shouldn't have problems, but I did notice that in a tag it has issues.

**Comment by ipatjolvur** [comment]
The literal text (without quotes) has the issue if a word and space are typed before it.

**Comment by calzoneman** [comment]
Actually I think this might be fixed if I update the library.  I'll leave this open untill I next restart cytu.be (assuming that's the server you're using).

If you're using a different server, notify the admin that dependency "node-validator" needs to be updated.  The latest version does not behave the way you described.

**Comment by ipatjolvur** [comment]
Using cytu.be.
Thank you.
