### ISSUE TITLE
Suggestion: Add Chat Sound Check Box

### ISSUE THREAD

**Issue by diboy2** [calzoneman/sync#251]
Every time someone sends a reply, produce a chat sound when he's not on the site's tab.

**Comment by nuclearace** [comment]
This can be done with custom JS or a client userscript. I know I've written one that makes a sound when my name is said.

**Comment by calzoneman** [comment]
Might make this a core option

**Comment by diboy2** [comment]
I noticed it keeps the chat going.

**Comment by calzoneman** [comment]
http://www.freesound.org/people/fordps3/sounds/186669/
