### ISSUE TITLE
Scipts doubling during server restart

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#253]
I noticed lately that during server restart all previously loaded custom scripts are loading one more time. This results in double layers/buttons/images etc.

Temporary I've added `.remove()` method on the beginning to delete hypothetically existed script elements. It's not a big problem though, but is it possible to not re-load custom scripts by default in case of server restart?

**Comment by calzoneman** [comment]
I'll look into it, but the safest way is to explicitly delete anything you create.

**Comment by calzoneman** [comment]
The external JS channel option should not be reloaded (per https://github.com/calzoneman/sync/blob/master/www/assets/js/callbacks.js#L308).  Is this the case?

**Comment by uchigawa** [comment]
When I wrote "restart" I meant rather client reconnection, that with `Disconneting from server. Attempting reconnection...` message.

I think now it is a wontfix problem, because after reconnection all API is started from begin, but channel HTML (with previously added custom script elements) is not reloaded. So all those elements appear twice. There is no way in this situation to check if external script is already loaded on the client side (or I don't know how).

But it's a rare situation anyway.
