### ISSUE TITLE
Offer of Server use - 1TB/month traffic Linix server

### ISSUE THREAD

**Issue by RidleyScottTowels** [calzoneman/sync#256]
I don't know if this would be useful or not, but I just received this message on reddit  

Cytube seems down. I have a spare server (1tb traffic) want any help?

from /u/dtxer sent 18 minutes ago  

Hey RST,  

seems cytube is down and i really miss the random movies. I have a spear 1TB/month traffic Lunix server sitting around in Seattle i think. It's a lowend VPS but it should do the job to host a cytube instance for us. If you want it/any help to get our movie nights back up just drop me a note

greetings from germany DILDOOOOOAPOOOOCAAAALLYYYYYPSEEEE :)

**Comment by calzoneman** [comment]
CyTube was DDoSed yesterday, and after being down for a few hours, I failed over to a secondary server.

The URL pattern http://cytu.be/* currently returns a 302 Temporary redirect to http://ny2.cytu.be.  Some users have reported that certain browsers do not handle this redirect correctly.

I expect to move the server back to the main host within the next couple of days, and in the meantime I'll see if I can figure out why stupid browsers are ignoring Cloudflare's redirect
