### ISSUE TITLE
Client side mute ability

### ISSUE THREAD

**Issue by Zalg0** [calzoneman/sync#26]
Requesting a client side mute ability (just for those people who we may have a personal dislike for heh)

**Comment by calzoneman** [comment]
To be clear, you're talking about ignoring chat lines from a given person?

**Comment by Zalg0** [comment]
yeah

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/d5ce1020b2e4a292ae5a396b0ac5734952ae4fde
