### ISSUE TITLE
New Version Breaks Unicode Video Titles

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#265]
Video titles are no longer decoded correctly. Instead of treating it as a UTF-8 encoded string they're treated as 8-bit strings.

For example: Sasami-san@ganbaranai Opening ã€Œã•ã•ã¿ã•ã‚“@ãŒã‚“ã°ã‚‰ãªã„ Opã€

Should be: Sasami-san@ganbaranai Opening 「ささみさん@がんばらない Op」

**Comment by calzoneman** [comment]
Unintended consequence of switching database interfaces, apparently node-mysql doesn't treat UTF-8 the same way as libmysqlclient did.  I'll look into it.

**Comment by calzoneman** [comment]
Ran into some unexpected issues with this.  The database actually uses latin1, whereas node uses utf8.  libmysqlclient was ignoring this and just treating the latin1 data as utf8.

The good: It's trivial to run a script to update the tables to use utf8 encoding.  This solves the issue for all new entries

The complication is that for existing library items, I've yet to find a way to actually unfuck the data.  If you have any suggestions for this, please let me know.

**Comment by awused** [comment]
Well you'd probably want to keep data in one table consistent. If you have existing data in latin1 you don't want to be inserting utf8 bytestrings into the same column. You can convert it using something similar to `CONVERT(latin1string USING utf8)`. It's next to impossible to (reliably) determine what is a utf8 bytestring and what is a latin1 bytestring just from the raw bytes.

I see you've already got utf8 going into the database. I hope you have timestamps or are willing to sift through the table for a row number you can use as a boundary.

**Comment by awused** [comment]
I normally handle issues like this in Naoko through my dbclient class. It checks the version of the database on initialization and will update it to the newest version before any data gets inserted. You should probably adopt something like this; It'll allow you to make more complex changes later on without forcing users to run scripts manually, worry about db versions, or toss out their data.

**Comment by calzoneman** [comment]
I think I've found a solution, I'm testing it locally.  The data in the database is actually utf8, just the charset is latin1 so that's why it's coming out garbled.  I should be able to dump the database, change latin1 to utf8 and reimport it without any decoding/encoding going on.
