### ISSUE TITLE
Duplicate names

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#267]
I've seen this happening a few times now. No idea why its happening.

![screen shot 2013-08-21 at 3 41 44 pm](https://f.cloud.github.com/assets/1211049/1004031/e2f9e4ce-0a99-11e3-90f7-8c4c489e8efb.png)
![screen shot 2013-08-21 at 1 25 37 pm](https://f.cloud.github.com/assets/1211049/1004032/e3012d60-0a99-11e3-9440-32371018b3c1.png)

**Comment by calzoneman** [comment]
I can't tell from the context of the screenshots, are those registered users or guest names?

**Comment by nuclearace** [comment]
Registered

**Comment by calzoneman** [comment]
Is it clientside or serverside?  i.e. if you refresh, does Specter's duplicate name go away, or does it remain part of the userlist?

**Comment by nuclearace** [comment]
Yes it goes away if you refresh

**Comment by calzoneman** [comment]
To clarify, you mean that the user who gets stuck (for example, Billy) only appears stuck to people are in the room at the time that the stickening happens.  Anyone who joins afterward has a proper userlist

**Comment by nuclearace** [comment]
Correct

**Comment by calzoneman** [comment]
Ok, I'll add some extra work into the `userLeave` handler clientside to prevent it from not being able to find the item, and I'll also check the serverside to make sure kicks are broadcasting properly.

If you know how to reproduce this, great, otherwise I'll just do some preventative measures.

**Comment by calzoneman** [comment]
I'm gonna mark this closed, per https://github.com/calzoneman/sync/commit/4841e7bc1ca18b505c6265ef437649fb12f6581c
