### ISSUE TITLE
Suggestion: Put Mute button on Right click menu + anon count

### ISSUE THREAD

**Issue by d-dd** [calzoneman/sync#270]
Could you place a Mute/Unmute button in the right click menu in the user-list since the other controls are there too?

Also it would be nice if you could add Anonymous user count in the user count box/stats.

**Comment by calzoneman** [comment]
Hmm, I want to avoid confusing people by having both a clientside "ignore" button and a serverside "mute" button on the same menu.

Anonymous user count is possible I guess.  I'm not really sure what the use is (well actually I don't know what the use of that popup is to begin with) but it shouldn't be difficult.

**Comment by calzoneman** [comment]
Anonymous usercount has been accepted and implemented
