### ISSUE TITLE
Relax Flood Controls for Room Admins

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#271]
I'm assuming the flood controls are more to protect rooms from scripters than to protect the site from DDoS. 

Allowing people with sufficient rank to "flood" a little should be fine, since if a room has an abusive moderator/admin there's not really anything the site should do automatically to handle it. I'd actually prefer you just dropped the limits completely for higher ranked users, given that there is an overall playlist length limit now.

I realize this only really affects Naoko and other bots, but I think they're widespread enough that it's worth considering them.

**Comment by calzoneman** [comment]
I have been considering a more tier-based system which would allow for small bursts and limit you to lower averages over large time periods (e.g. you can add without reasonable limit within 5 seconds, 1 per second up to a minute, etc...).  The current static limit was something I wanted to put into place to prevent the situation that came up on 6irc the other day (an abusive moderator was adding hundreds of videos per second, which resulted in the entire server being throttled by YouTube).

I'm not worried about playlist length, it's capped at 4,000 which is no load on the server and would lag a browser but not enough to crash it.  The primary reason for rate limiting is to prevent a denial of service by getting the server itself rate-limited by the APIs it uses.

Currently, moderators and above should be limited to 2 videos per second, unless my math is wrong.  That's faster than any human could add them, but if it's really necessary to have your bot add more than 2 videos per second, I can look into relaxing for short bursts.

**Comment by awused** [comment]
Well, in order to match with the most common adds I'd like at least five videos at once. If I know the exact limits for how much can be added at once I can at least work with it.

When importing lists from files Naoko will currently add at most two videos a second. I'd say five videos burst and two videos/second sustained should be workable.

**Comment by calzoneman** [comment]
This is addressed by https://github.com/calzoneman/sync/commit/02887958cb87e6650a2583c1286f55dce18f2278.
- Plain users are limited to a burst of 3 videos and 1 video/second sustained
- Moderators are limited to a burst of 10 videos and 2 videos/second sustained

**Comment by calzoneman** [comment]
Note that I haven't pushed this out to cytu.be yet.
