### ISSUE TITLE
Case insensitive regex

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#29]
Is it possible to create case insensitive regex? I try to add something like

`/word/i`

and it seems doesn't work.

**Comment by calzoneman** [comment]
I'm actually using what you put in the box as the regex and manually adding the "g" flag:
`data.filter[0] = new RegExp(data.filter[0], "g");`

I probably should allow adding flags after the `/`.  Currently, your regex is actually matching the string "/word/i" rather than "word".

**Comment by uchigawa** [comment]
Oh, I just find it in a code. So it is really impossible currently.

It's not a big problem to do it indirectly creating more advanced filters if you have a few of them, but it is if you have 50.

Also, what exactly `\\\\([-a-zA-Z0-9]+)` filter does?
