### ISSUE TITLE
Server Skips Incomplete Videos

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#295]
Not sure what leads to this, but occasionally the server will skip an incomplete video.

It's happened a few times but I was never certain, but I just caught it in a case where only I and my bot were in the room, and neither of us skipped it. I believe it has happened sporadically many more times.

**Comment by calzoneman** [comment]
I have never seen this behavior so unfortunately without any additional information there's nothing I can do.

The only thing I can think of is perhaps the server has cached bad data for the length of the video and therefore thinks the video is over.

**Comment by awused** [comment]
Naoko generally picks up on it. I lack any steps to reproduce it. It can be obvious on a very long video but I have reason to believe it can happen on any video, even pretty short ones.

I opened this issue to make you aware of it, maybe there's some additional checking/logging you can do to narrow it down.

**Comment by calzoneman** [comment]
I might add debugging symbols to your channel.

**Comment by calzoneman** [comment]
I now have every lead loop logging the current time to a file for your channel (as well as whenever a video starts or ends).  Please try to tell me the exact time if it breaks so I can view the relevant portion of the logfile.

**Comment by calzoneman** [comment]
@Suwako ^

**Comment by awused** [comment]
Next time I notice it happening I'll let you know. I don't know what triggers it, exactly. I might add some form of alerts to Naoko to let me know when she suspects it.

**Comment by calzoneman** [comment]
If this remains unconfirmed over the next few days I'm going to stop maintaining the debug logging for animu and assume it's not reproducible.

**Comment by awused** [comment]
Yeah I can't reproduce it at will. I've been watching for it but I haven't noticed it. It has happened enough that I believe it is a real problem, and it's happened in circumstances where the only two people in the room who could skip it (myself and Naoko) didn't skip it.
