### ISSUE TITLE
Bad mediaUpdate Packet

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#298]
I've had a few people tell me that they are being kicked for bad `mediaUpdate` packets. They were both leader so could it be that it tries to update at the end of a video which sends something that isn't a number?

**Comment by calzoneman** [comment]
I've been considering making certain packet checking less strict (just fail silently instead of kicking).  I'm not sure what would send a malformed packet but perhaps one or more of the APIs are inconsistent.

**Comment by calzoneman** [comment]
Wouldn't that be a first, an API returning bad data...
