### ISSUE TITLE
"Temporary fix" in updateMotd is a bit broken

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#299]
It strips out all but the first style= attribute, looks like it's meant to be doing a global replace, i.e.:

```
html = html.replace("style", "stlye", "g");
html = sanitize(html).xss();
html = html.replace("stlye", "style", "g");
```

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/33e5f2e0566c27f4869fd59a9cbe036e6e63b2bf
