### ISSUE TITLE
Strange behavior of "close poll" button

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#30]
If the poll is open, after every make/take leader action, a new "close poll" button is added.
![buttonbug](https://f.cloud.github.com/assets/4163505/386137/21b07fda-a69e-11e2-80a1-bac2713f3a01.png)

Also, I suggest change caption to "End Poll". "Close" may be misunderstood.

**Comment by calzoneman** [comment]
Does this affect everyone or only the leader?  If it only affects the person being made leader, then I simply forgot to add a check for open polls when the remove leader action is fired.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/6ae16d567191533df8c60063eb57f9c0fd8ed394 Fixed
