### ISSUE TITLE
Youtube videos blocked in countries

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#305]
Update the youtube queue processor to warn people if a video is blocked in certain countries

**Comment by calzoneman** [comment]
Also I keep forgetting to have library searches fall back on youtube if the search term doesn't return any results from library.

**Comment by nuclearace** [comment]
How well would that work? I know when I'm searching the library I only use a key phrase, like "clap" or something vague. But since I know that a video like that was added, it's narrow enough to find it.

Also, did you ever look into the video controls not hiding after a video switch?

**Comment by calzoneman** [comment]
It's so I can just hit enter and not have to click the youtube button if the query isn't in the library.

I can't fix the hiding thing, that's youtube's fault and I've been too lazy to produce a test case for them.
