### ISSUE TITLE
Add optional chat throttle/slow mode, and/or optional room caps

### ISSUE THREAD

**Issue by The-Celt** [calzoneman/sync#309]
Please allow room admins the option to throttle the chat or allow them to engage a slow mode. When a room becomes quite full, and the chat becomes blistering fast, things become very unstable and chaotic. The option to engage a slow mode/throttle the chat would be very useful in resolving this. 

Similar, the option to cap the number of users in the room would be another way of achieving the same goal. If the room admin could set a maximum capacity number for the room, that would be great. 

Please do not set hard room caps, but soft room caps that each room can set at their own discretion.

**Comment by nuclearace** [comment]
Isn't there already a throttling for chat? Why not let channel admins choose the time it takes to hit cooldown.

**Comment by calzoneman** [comment]
I have been considering improvements to the anti chat flood system to deal with spam, but I suppose I could extend those to allow you to just always throttle people (although be aware this is frustrating from an end-user perspective).

I'd like to avoid adding room caps, it just seems like a messy feature to implement.  It's not as simple as kicking every user above the cap.

**Comment by The-Celt** [comment]
@nuclearace There is a throttle but it's very, very short, like a 3 seconds cooldown and doesn't prevent spam in rooms that really see big numbers

**Comment by calzoneman** [comment]
Well yeah, the current spam filter is intended as more of a short warning for mods to kick in and mute/ban the offenders and to prevent people from just flooding chat very quickly.  It's not really intended as a general purpose "slow down the chat" feature.

I may just use the same basic throttling system that the playlist uses and allow the admins to vary the parameters (burst count, sustained rate).

**Comment by calzoneman** [comment]
@The-Celt I'm working on this idea; I would like you to test it on the dev server sometime to see if it will suffice

**Comment by The-Celt** [comment]
@calzoneman Yeah, I'd be happy to help test it out: How would like to go about it? Do we need to set up a time and date to both meet up in the dev room?

**Comment by calzoneman** [comment]
Can you just join the IRC when you get a chance and if I'm around we can test it?
