### ISSUE TITLE
JWPlayer .mp4 videos are incredibly choppy in Chrome

### ISSUE THREAD

**Issue by misspokeycat** [calzoneman/sync#318]
To get issue, load a .mp4 file into JWPlayer by putting in jw:http://foo.com/bar.mp4 into the player in Chrome.  The video playback is incredibly choppy, and not due to bandwidth issues.  Viewing the same video on Firefox is smooth.

**Comment by calzoneman** [comment]
I'm not sure there's much, if anything, I can do about this given that JWPlayer is a third party video player that I'm simply embedding and calling via an API.

If you have a link to a video that demonstrates the issue I will see if it happens to me, but the consensus on [their support forum](http://www.longtailvideo.com/search/google_cse_adv/chrome%20choppy) seems to be that they either don't know or don't care why certain browsers are experiencing choppy playback.

**Comment by calzoneman** [comment]
There's a couple of possibilities, my guess would be either a video encoding issue, or a caching issue given that you're loading directly from file.

JWPlayer was originally implemented to be able to support Icecast and other streaming media, so you should really try to avoid using it to play very large direct download video files when possible.
