### ISSUE TITLE
Cannot add external javascript to page.

### ISSUE THREAD

**Issue by lolihopper** [calzoneman/sync#319]
Is there any special way to do this that i am missing? I have used every link from this page http://pastebin.com/auE468Nx and i still cannot get it to work. Any ideas or help please?

**Comment by calzoneman** [comment]
External javascript is meant to be a URL (which is indicated by the hint text "Script URL").  The intent is that if you need more than the maximum amount (20KB) of code that you can embed directly in the Channel JS option, you can host a script file on some other server and load it from there (for example, http://somewebsite.com/path/to/script.js).

I'm not sure what you're trying to accomplish from that pastebin, but I can almost assure you that using `document.write` is the worst possible way to accomplish it.

**Comment by lolihopper** [comment]
Thanks for the help. Also for some reason none of that will work without it and im not really sure why. Right now its just an exact copy of my page and i want to add that so i can move some of the boxes around and add another one but for some reason i cant just add 1 line of java or the entire page just goes white with the text i input at the top.

**Comment by calzoneman** [comment]
Yeah, you shouldn't use `document.write` at all in this case.  `document.write` literally overwrites the page, so the first time you call it, it deletes the entire page and writes whatever you passed into it.  Overwriting the page is not what you want to do.

If you come to [IRC](http://webchat.netchat.io/?channels=cytube), someone may be available to help you if you can explain what you're trying to do.  You'll probably want to use jQuery to detach and move page elements around.

**Comment by lolihopper** [comment]
Ok thank you very much. Unfortunately java script is one of the things that i am very very bad at. I guess ill look into it some more and try to find a better way to do this. I wish i could just do this in HTML im a lot better at that.
