### ISSUE TITLE
Request: Option to choose temporary instead of permanent as default for playlists

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#324]
I really like sync, and I would love to be able to choose if my playlist additions are temporary per default. If this is already a feature buried somewhere in the "Moderation Menu" please point me to it.

Thanks for creating sync, mr calzoneman + everyone contributing to this.

**Comment by calzoneman** [comment]
Only way to do this right now is to set the "add nontemporary media" permission above your rank.  People have suggested the ability to add things as temporary and I might add a checkbox or something in 3.0, but I'm not planning to update the current version in the interest of getting work done on 3.0.

**Comment by calzoneman** [comment]
Added in 3.0
