### ISSUE TITLE
log in issues

### ISSUE THREAD

**Issue by altosax29b** [calzoneman/sync#328]
I'm the leader of my synchtube room but I got disconnected from the server for 5 minutes, some red text message appeared in my chat box, now i can't log in as anyone. pls help

**Comment by altosax29b** [comment]
also it's the /r/braverytube room that I can't get in. however when i clicked the /r/blah link it had me logged in. i don't know whats happening

**Comment by calzoneman** [comment]
Assuming you're referring to synchtube.6irc.net / synchtu.be the admin misconfigured the webserver so certain functions weren't functioning properly.  I've notified him and it should be fixed shortly.

**Comment by calzoneman** [comment]
Also, for future reference, you'll probably get a faster response time by joining [IRC](http://webchat.6irc.net/?channels=synchtube) as myself and the other support people tend to get notifications for that faster than I do for github.
