### ISSUE TITLE
Hitbox.tv support

### ISSUE THREAD

**Issue by JackKucan** [calzoneman/sync#330]
Could hitbox.tv support be added (I'm sorry, I don't know how to add the "enhancement" tag).

**Comment by calzoneman** [comment]
Since hitbox is a livestream provider (and hence synchronization is unnecessary), you can simply use the Custom Embed feature to embed the `<iframe>` code provided on each hitbox channel (click "Share").

**Comment by calzoneman** [comment]
Also, you can't add tags yourself I don't believe, the tags are for the repo owner to classify things.

**Comment by JackKucan** [comment]
I just figured it was worth asking since the custom embed code is in a
really simple format (I'm sorry I can't implement it myself, I can't get
the MySQL stack it wants working on this computer so I can't test it for
errors).

On Mon, Feb 10, 2014 at 7:38 PM, Calvin Montgomery <notifications@github.com

**Comment by calzoneman** [comment]
It's not about it being difficult to add, it's just adding more lines of code to write and maintain to basically add no new functionality.

The main reason JTV/Twitch/Livestream/Ustream are native is that they were implemented months before the custom embed feature was introduced.

One thing I have considered before is just implementing a general "embeddable livestream" thing and adding simple rules for different provider URLs.

**Comment by JackKucan** [comment]
That would be very useful. Would those be per-site or per-room (or possibly
both)?

On Mon, Feb 10, 2014 at 7:54 PM, Calvin Montgomery <notifications@github.com
