### ISSUE TITLE
Layout changes

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#336]
Could you make all layout changes in User Preferences window not require refreshing? I often change layout depending on the video and it's not very comfortable. I think mainly about back to "compact" option.

**Comment by calzoneman** [comment]
Not easily.  Well, fluid would be pretty easy to undo I think, but HD kind of wreaks havoc on the DOM.

**Comment by calzoneman** [comment]
If you want to contribute a function that undoes [this](https://github.com/calzoneman/sync/blob/3.0/www/js/util.js#L1432-L1486) I'll happily implement a way to handle it automatically from the settings (and take care of fluid as well).

**Comment by uchigawa** [comment]
I'll try to do such function this weekend.

**Comment by uchigawa** [comment]
http://pastebin.com/3frWvhKn

I tested it as custom JS and it perfectly changes layout from HD to compact. You need to add of course non-fluid and non-synchtube functions, but it's just a couple of code lines.
