### ISSUE TITLE
Emote matching

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#339]
Some things I've noticed with emotes.

![screen shot 2014-03-27 at 11 41 51 am](https://cloud.githubusercontent.com/assets/1211049/2539259/68165020-b5c6-11e3-9d70-b6f5b8d38b5b.png)

**Comment by calzoneman** [comment]
First message is expected behavior- an emote should only be matched if it is not part of a larger word (i.e. the emote code is buffered by whitespace on either side).

Second message is fixed by https://github.com/calzoneman/sync/commit/43be6402a018373323a7bcf497b4bbd7c2322b33
