### ISSUE TITLE
Slate theme / Volatile Actively Playing

### ISSUE THREAD

**Issue by QuillOmega0** [calzoneman/sync#343]
On the slate theme, it is impossible to distinguish if the currently playing video is set to volatile or not.

**Comment by ipatjolvur** [comment]
I got around that by slightly changing the gradient colors in my custom CSS:

```
.queue_active {
  background-image: linear-gradient(#595e61, #505659, #4b5054);
  background-repeat: no-repeat;
}
```

It recolors the active queue regardless of whether it is Permanent or Temporary.

**Comment by calzoneman** [comment]
I changed the color slightly so that the striped image was visible, but I wasn't sure how much that depended on my monitor's contrast so I left the ticket as open for other people to test it.

**Comment by ipatjolvur** [comment]
These tools check colors using the [Web Content Accessibility Guidelines (WCAG) version 2.0](http://www.w3.org/TR/WCAG20/):
- http://www.dasplankton.de/ContrastA/ - Click "Show Thresholds for normal Vision" and "Show Color Deficiency Simulation."
- http://www.stainlessvision.com/blog/projects/colour-contrast-visualiser - At the bottom under "Downloads," click the SWF link.  Note that the single threshold line in this tool is based on a 2006 WCAG draft which recommended a 5:1 contrast ratio.
- http://www.checkmycolours.com - Input a URL, and this will check the WCAG rating for multiple containers on the page.
