### ISSUE TITLE
Regular members playlist control

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#35]
It seems that moving videos and "next" playlist buttons are not working for normal users, even if the queue is open and all options are allowed. Deleting and jumping to a video is ok. Could you check it? Bug, or my admin didn't update some files yet?

**Comment by calzoneman** [comment]
Fixed, I had inverted a logical AND to a logical OR when checking for permission in the movement function, so it always failed instead of only if that option was disabled.
