### ISSUE TITLE
Change userlist to left-click instead of right click and make the mouse cursor change properly

### ISSUE THREAD

**Issue by CoolOppo** [calzoneman/sync#352]
It should be more obvious that you even _can_ right-click on users. The cursor currently just is a standard text cursor, and there is nothing telling you to right-click for more options. Since left-clicking doesn't invoke anything anyways, why not make the usernames make your mouse pointer into the standard one for links, and enable left-clicking for the menu?

**TL;DR:**
- Make left-click activate the menu
- Make the mouse cursor show that it's clickable

**Comment by calzoneman** [comment]
I'll have a look at setting the cursor attribute on userlist items.  I don't want to remove the right click handler because people are used to it, but I'll see how having both works out.
