### ISSUE TITLE
Implement registration password verification and reset

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#36]
There's enough people using this now that people forgetting their passwords is becoming a problem.

2 things to do:
1. Modify the registration form to include a "confirm password" field that must match the password field (and also perhaps a recovery email?)
2. Implement some way to reset your password.

**Comment by uchigawa** [comment]
If you haven't got specific ideas yet, I suggest leave basic registration form as is, and after clicking "register" button display a password confirmation field.

Also, I would like to see "User Controls" tab next to "Channel Controls" in `#modnav`. You could put there a form with fields to change personal password and to add recovery email.
