### ISSUE TITLE
Site doesn't load content – Cross-Domain Access Error

### ISSUE THREAD

**Issue by justjanne** [calzoneman/sync#361]
The site doesn't load content (only empty player, empty playlist and empty chat with a message "not connected".

The error in JavaScript console is this one:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://sea.cytu.be:8880/socket.io/1/?t=1400356395678. This can be fixed by moving the resource to the same domain or enabling CORS.
```

**Comment by calzoneman** [comment]
Which URL are you connecting to?  Which browser?

It sounds like perhaps you're attempting to connect from a third-party domain and/or your browser is being extremely strict about cross-origin requests.  This should not normally happen because `sea.cytu.be` is the same root domain as `cytu.be`.

**Comment by justjanne** [comment]
I'm using Firefox 29 with RequestPolicy (which usually blocks cross-origin requests completely, but I had put cytu.be->sea.cytu.be into the whitelist.) right now, and sometimes it works, sometimes not.

It only didn't work for some hours, now it works again. Strange thing, though.

But still you should enable Cross-Origin requests from `cytu.be` to `sea.cytu.be` on your `sea.cytu.be` server.

**Comment by calzoneman** [comment]
I don't think I can do that.  The particular request that you're having issues with is not served by my regular webserver, but by socket.io.  It's the initial handshake request that returns the session ID and various parameters for the socket.io client.  I'm not sure I would be able to set custom headers on it without modifying socket.io itself.
