### ISSUE TITLE
Feature: /kickanons

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#367]
For a while now, there has been the ability to kick anonymous users with `/kick` as a side effect of the extra space being parsed as an empty nickname.  I think it would be beneficial to make the behavior available on purpose with an easy command.

**Comment by nuclearace** [comment]
I can't remember if it has always only kicked one per /kick, or if that's a bug

**Comment by calzoneman** [comment]
Probably always one per /kick, since I'm pretty sure the `for` loop would have a `break` statement after the first target is found, since in the intended use case no two users would have the same name.
