### ISSUE TITLE
Google docs refresh

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#373]
Sometimes google docs doesn't seem to refresh the link correctly. It fails to the load the video and "Failed to load resource: the server responded with a status of 403 (Forbidden)" appears in the web console. The videos are public, and you can load the video in Google drive.

**Comment by calzoneman** [comment]
Need a demonstration link.

**Comment by nuclearace** [comment]
The console says this 403s: https://r19---sn-nwj7kned.c.docs.google.com/videoplayback?requiressl=yes&shardbypass=yes&cmbypass=yes&id=aa171b1e2faa1a67&itag=34&source=webdrive&app=docs&ip=192.184.93.12&ipbits=0&expire=1402517522&sparams=requiressl%2Cshardbypass%2Ccmbypass%2Cid%2Citag%2Csource%2Cip%2Cipbits%2Cexpire&signature=25291FF8B9865B0A91775DFA9ADC3C1A60F19B25.ADD88842DB6B1BAFB82005147515855E26A2503F&key=ck2&ir=1&ms=nxu&mt=1402513897&mv=m&mws=yes&cpn=U5b8hoZAU9LU75yo

and this 404s: https://www.youtube.com/get_video?eurl=http%3A%2F%2Fcytu.be%2Fr%2Fxaemae&fmt=34&el=embedded&t=1&noflv=1&autoplay=1&cpn=U5b8hoZAU9LU75yo&asv=3&video_id=0B3Vd6oAeI3jyRlN1aWNYV3BxdDg

with the video being: https://docs.google.com/file/d/0B3Vd6oAeI3jyRlN1aWNYV3BxdDg/edit

**Comment by Xaekai** [comment]
The video used is irrelevant. Just queue up three episodes of a 1hr long show and by the time the playlist gets to the third it will give error and not load.
