### ISSUE TITLE
Relax xss filtering

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#379]
Links like http://apps.microsoft.com/windows/en-us/app/gt-racing-2-the-real-car/d28d48a5-e32b-41bc-bd32-5198a60c23e1 get the word "windows" filtered out, thus breaking the link.

Also maybe allow the video tag?

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/3661ab1fd967f5858279e7e810f08cc485851ac4

I don't want to allow video tags right now.
