### ISSUE TITLE
Some minor layout/code suggestions

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#38]
Not really important, just my thoughts about a little layout improvement.
- library search results box displays only scrollbar after loading a channel, you could make it hidden by default
- shouldn't "help" link on the top navbar be opened in a new tab, or you want it open on purpose in the same tab?
- unique id for every `<div class="row">`, it's not very comfortable to use `.row:nth-child(1)` etc. while creating custom css

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/9e8ca1ad3a49b1d9005dc57928ae2a9cfcc65a5c
