### ISSUE TITLE
Bundled dark theme

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#39]
It's would be nice to include dark theme for people who don't feel alright with bright colors or for those with sight issues, especially at night. I know that there is custom css option, but dark theme is quite essential.

**Comment by calzoneman** [comment]
This sounds like a good idea.  If you have ideas for a dark theme you can submit the CSS and I'll include it in the official repository.

**Comment by ghost** [comment]
I'm working on one here: http://synchtube.6irc.net/?channel=4oki

**Comment by calzoneman** [comment]
Working on one.
