### ISSUE TITLE
Video pause issue even after assigning leader 

### ISSUE THREAD

**Issue by Vergo777** [calzoneman/sync#390]
This question was already raised in https://github.com/calzoneman/sync/issues/358, where the solution given was to make someone leader so that the room would pause for everyone when the leader paused

I tried doing this by making myself leader, but the video still continued to loop for everyone in the room when I paused. I'm using Google Chrome version 36.0.1985.125 m, as was everyone else in the room. This issue occurs with Firefox 22.0 as well. The channel in question is  http://cytu.be/r/Warwick, and I've already tried clearing my cache + cookies.

**Comment by calzoneman** [comment]
I'm fixing a pause issue with the native HTML5 player (used for Vimeo, Google Docs, and Google+ videos).  I have confirmed that pausing works correctly for YouTube.

If your pausing issue is occurring with a different video type, please indicate it here.

**Comment by calzoneman** [comment]
Fixed by https://github.com/calzoneman/sync/commit/f11be6ae810aef8cb2cee31a287cc6760dbfd5d4 (once it gets deployed to cytu.be).

Resolving.
