### ISSUE TITLE
SMIL files in JWPlayer

### ISSUE THREAD

**Issue by frenchja** [calzoneman/sync#403]
Is it possible to play [.smil](https://en.wikipedia.org/wiki/Synchronized_Multimedia_Integration_Language) files in the present build? It looks like JW Player supports .smil since version 6 ([see here](http://support.jwplayer.com/customer/portal/articles/1430398-dynamic-rtmp-streaming)), and that 6.6 is already included with the software.

**Comment by calzoneman** [comment]
Do you have a test file?  Any link prefixed with `jw:` is passed to JWPlayer directly regardless of file extension.  The only catch is that because there's no unified API for retrieving time, you must either specify the time in the appropriate input box, or use the leader function.

**Comment by calzoneman** [comment]
@frenchja If I don't hear back from you on this issue I'm going to assume that you've figured it out and close the ticket.

**Comment by frenchja** [comment]
Thanks for following up.  I'll post an example SMIL file with active
streams tonight.  I don't have access to the server from this computer to
spin it up.
