### ISSUE TITLE
Adjustable voteskip ratio and current votes indicator

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#41]

**Comment by calzoneman** [comment]
Voteskip ratio would be fairly easy to add to the channel options.  If I do add a current votes indicator, I'd probably make it only show up to moderators (to prevent bandwagon voting).

**Comment by ghost** [comment]
> I'd probably make it only show up to moderators (to prevent bandwagon voting).
> That's a good idea.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/40ad039a06bfa0f7ca5ab0a82f1de746a7f25aa2
