### ISSUE TITLE
Putting emoji into profile text breaks login

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#419]
Locally using mysql trying to set an emoji in your profile seems to cause a database failure, however on cytu.be it doesn't.

**Comment by nuclearace** [comment]
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html maybe?

**Comment by nuclearace** [comment]
Also happens on trying to save a playlist with an emoji name

**Comment by calzoneman** [comment]
It's funny you mention this because my friend and I just encountered this somewhere else last night... It is a DB schema problem; I'll either have to do another huge conversion like the original `latin1` to `utf8` fix, or just make the code strip out emoji.

**Comment by calzoneman** [comment]
@nuclearace guessing the reason that it works on cytu.be is that cytu.be is actually running MariaDB, which might have a sane `utf8` collation (seriously why the hell would `utf8` in MySQL not actually be fully UTF-8 compliant?)

**Comment by nuclearace** [comment]
Example: 👽 ayy lmao

**Comment by calzoneman** [comment]
Fixed by https://github.com/calzoneman/sync/commit/9deff9bdb1fac4ac457f443e7ce9a039aeb2d5bf and https://github.com/calzoneman/sync/commit/c39c394f3665997479f9e57178a29519d26daede
