### ISSUE TITLE
ACL Editor or something like that

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#42]
One cannot unmod an offline mod :D

**Comment by uchigawa** [comment]
I strongly recommend it. A basic feature. I would like to see a new tab in `#modtabs` with listed all registered channel users, sorted by rank or name. Every user could be promoted or demoted, even if an user is offline.

Practice shows that "bad" mods avoid owners and it's hard to demote them.

**Comment by calzoneman** [comment]
This hasn't been denied, I just haven't had the time to work on it.  Generally I tag issues as "wontfix" if I don't intend to implement them.

**Comment by calzoneman** [comment]
Implemeted.  Currently only accessible to channel owners (just shows up as blank for moderators).  When someone joins a channel as a registered user (not a guest), their name will be added to the channel ranks table with their global rank (global rank is 1 for everyone except network admins).

Note that the channel ACL will have no effect on global rank, only on the per-channel rank.
