### ISSUE TITLE
CSS is pretty big.

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#420]
Hey, thanks for noticing me (flussence@5d9249bd). I was in the middle of writing something here about it but you beat me to it... wasn't intending to get that branch merged, it was an experiment.

So, it turns out the default Bootstrap CSS and the site themes are 99% identical, and the latter ones override the former in its entirety, so having `bootstrap.css` in the `<head>` all the time is just a waste. Can you make that line go away? It'd probably make mobile users a bit happier.

**Comment by calzoneman** [comment]
As long as we can verify that removing `link(href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css", rel="stylesheet")` doesn't break/change anything, I'm fine with removing it.

The current method of handling themes has some other issues as well (`slate.css` is always loaded first and is swapped out by JavaScript), which are being resolved by redoing the theme system in version 4.0.

**Comment by ghost** [comment]
I've tested removing that stylesheet locally and everything looks OK, no sudden changes or anything. And with having recently read all of both files side by side in an editor... I'm pretty confident it's safe.

**Comment by calzoneman** [comment]
It looks like this breaks the `light` theme, which is just the bootstrap default theme (with some extra rules for CyTube colors).  I'll have to download the CSS for that and merge those the same way the other themes work.

**Comment by calzoneman** [comment]
The bootstrap theme, which uses `bootstrap-theme.min.css` is also affected.

**Comment by calzoneman** [comment]
Ok, I think I've got those fixed, the only annoyance is the page flickers when changing themes since there is no base bootstrap CSS to fall back on.

**Comment by calzoneman** [comment]
Theme flicker should be resolved by a bit of javascript trickery
