### ISSUE TITLE
tab completion

### ISSUE THREAD

**Issue by estillesemae** [calzoneman/sync#423]
There is an issue with tab completion in the mlp anniversary room. Xaekai is sleeping, I thought I would inform you.

Most of the time, when tab completion is used, an "image.channel-emote" appears. It is a blank box with nothing in it. Cannot click or anything. 
http://i.imgur.com/zZuj6hf.png
http://i.imgur.com/Y1D8P4e.png

I noticed it is only in the anni room though. I don't know if you can help, but that would be great!!

Estillesemae

**Comment by estillesemae** [comment]
Update to the problem, it's open spaces after the tab completion. So when you tab complete a name Rainbow23: , if there is an open space, that box will show up.

This is also the case for emotes.

**Comment by estillesemae** [comment]
fixed it. added an emote accidently that was just a space

**Comment by Xaekai** [comment]
@estillesemae My room features aren't calzoneman's problem or domain. Nice to see you using the dev console to figure shit out though.
