### ISSUE TITLE
Homepage with channels list + unlisted channel mode

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#43]
Low priority actually, but some would want it.

**Comment by ghost** [comment]
I think that this issue gained some priority lately, since it's the only obstacle remaining to release CyTube in public. I mean, it's pretty much usable now and looks good too.

**Comment by calzoneman** [comment]
I'm not really familiar with how Synchtube did it, so I'm interested in suggestions.  Should it be the most popular channels?  Only channels that have people in them?

**Comment by calzoneman** [comment]
I've started on this by migrating channels to `channel.html` and redirecting the old `index.html?channel=blah` style URL.  I just need to come up with what to do on the index page and I can work on it.

**Comment by ghost** [comment]
My vision is pretty KISS:
`<div class="row">
  <div class="span8">channellist.html contents - that's all we need, sorted by viewers online</div>
  <div class="span4">"Enter Channel" form here and a space for custom html below[1]</div>
</div>`
[1] For welcome message, ads, twitter widget, quick faq, etc.
