### ISSUE TITLE
Mod abuse on cytu.be/r/kpg4

### ISSUE THREAD

**Issue by Pandarap** [calzoneman/sync#436]
Hi,

I've been a user of this /r/kpg4 community for nearly a year now, and I am currently experiencing issues with the current channel administrator ilikesubinthanks, who took responsibility for leading and managing our community for approximately 1-2 months now since our shift from the previous channel named kpg.rongclub.com.

I had uploaded a video from my youtube channel, and certain users in the channel had decided to go through my channel and look at my videos. A video that I thought I had made private was put into the channel, which shows my face and my name. I immediately made this video private, and I thought that there would be no issues.  A user in the channel, boulderhead, had saved the video before I pulled it off, and used a screenshot of my face as an emote into the channel. I had requested both publicly and privately to ilikesubinthanks and to the channel at whole that my face be removed since it was very uncomfortable for me. My request was denied several times from both ilikesubinthanks and the channel, and iikesubinthanks had even encouraged the posting of my face as an emote.

I decided to take matters into my own hands and I had deleted the emote of my face in hopes that it would deter people from posting it. It was not long before another emote was made, which I did expect, but I had still hoped it would at least let the other members know that I was uncomfortable with it. In the process of deleting this emote, I had modified one emote as a fun play with boulderhead who happened to use that emote frequently. Many members have done this in the past, and it has always been a non-issue.

I was then demoted from a moderator to a regular user after deleting the image of my face. It was not long after this that I was being witch-hunted by members of the channel with small pieces of information about my private life started appearing in chat conversations. Information such as my school, my age, my location, my ethnicity, my IRL friends, etc.

Not too long after this, I was banned from the channel without any notice or reason as to why. I had simply entered the channel on the morning (PST) of February 5, 2015, and I was subsequently banned by ilikesubinthanks.

I realize that this issue is not a technical issue as far as cytube is concerned, but I would still like to see if there is any action that could be taken.

Thank you.

**Comment by Xaekai** [comment]
It seems you are already aware that channel politics don't belong on the issue tracker, so I won't comment on that.

People will be assholes. There isn't a line of code that can be written anywhere that will stop that. You could always create your own channel or find a new one.

What type of action were you hoping for exactly?

**Comment by calzoneman** [comment]
@Pandarap 

Regarding being banned, the banlist for each channel is managed at the discretion of its moderators and admins, and I generally don't interfere with that.  If you have an issue with a ban, you will need to contact the channel moderators.

If you believe that people were discussing your private information on CyTube without your permission, you would need to provide approximate times so I can verify this.

As for the emotes, I could ask that they be removed, however it's worth considering that this might make your situation worse if they decide to act out of spite.

Please send further replies to my designated CyTube email address, cyzon@cytu.be.
