### ISSUE TITLE
Support for mp4 links not ending in mp4

### ISSUE THREAD

**Issue by newusernamenotme** [calzoneman/sync#440]
When adding a link like [this](https://r16---sn-hp57knee.googlevideo.com/videoplayback?requiressl=yes&shardbypass=yes&cmbypass=yes&id=3b547cd64bb3d6b9&itag=37&source=picasa&ip=76.18.217.8&ipbits=0&expire=1426522429&sparams=cmbypass,expire,id,ip,ipbits,itag,mm,ms,mv,nh,pl,requiressl,shardbypass,source&signature=7DB10B02B5EA29F82EB3E040D13D84454BFA364C.559DB039EB21EAB84E0C7852E9C83CE0785B6F73&key=cms1&cms_redirect=yes&mm=30&ms=nxu&mt=1423931114&mv=m&nh=IgpwcjAxLm1pYTA0KgkxMjcuMC4wLjE&pl=20) that does not end in .mp4, the software refuses it.  It still has the MIME type of mp4, though, and should be able to play. Is there a way to have the software detect MIME types instead of extentions, or a way to edit the link so the software will still handle it?

**Comment by calzoneman** [comment]
The particular link that you gave as an example looks like the links you get from Google Docs or Google+ photo albums.  Those are both supported by CyTube without the need to add the direct video link.

For google docs, add the `http://docs.google.com/file/d/(file id)/edit` link.

For google+, right click the preview on the post and copy the link.

**Comment by calzoneman** [comment]
It turns out that you can actually do this thanks to a recent change.

Add your link as `fi:http://link/to/file` and it won't complain about the file extension.
