### ISSUE TITLE
Whitespace required between emotes

### ISSUE THREAD

**Issue by Kirtaner** [calzoneman/sync#441]
See title. Emotes break if there is no whitespace between them.

**Comment by calzoneman** [comment]
Intentional.

**Comment by calzoneman** [comment]
A more detailed explanation of why this is intended behavior: while some rooms have a convention for emotes being delimited (e.g. `:emote:`), this is not required.

Consider that someone adds an emote `lel`.  Then the message `parallel` should not be filtered to `paral<img src="whatever.png">`.  This is why whitespace separation is required.
