### ISSUE TITLE
Dailymotion duping

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#445]
Test case:
Channel options: Allow Duplicate Videos unchecked.
Queue: www.dailymotion.com/video/x2geddf_a-history-of-lego-in-three-minutes_tech
Queue: www.dailymotion.com/video/x2geddf
Queue: www.dailymotion.com/video/x2geddf_you_can_put_whatever_you_want_here_dont_matter

**Comment by calzoneman** [comment]
Damn it dailymotion
