### ISSUE TITLE
RFE: add BT command aliases when possible/appropriate?

### ISSUE THREAD

**Issue by jamesmanning** [calzoneman/sync#447]
Mal tried to /rcv but it didn't work.  Turns out the cytube command is /say but since /rcv didn't do anything, I was wondering if it could be added as an alias for /say?  Maybe similar aliases if there are other BT commands that have different names in cytube?

![image](https://cloud.githubusercontent.com/assets/225626/6223335/526d64ce-b634-11e4-9541-d0defe1128e0.png)

**Comment by Xaekai** [comment]
I'm going to assume BT is BerryTube. Is there a full list of BerryTube commands anywhere? Because [this](http://wiki.berrytube.tv/index.php/Chat_markup) is obviously incomplete.

**Comment by Xaekai** [comment]
Didn't you already finish this?
