### ISSUE TITLE
Singular/plural in captions

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#46]
"1 drink", "1 connected user" looks better than "1 drinks" etc.

**Comment by calzoneman** [comment]
Can we just do away with singular forms of words?  It would save programmers a lot of trouble :P

**Comment by uchigawa** [comment]
No problem xD Actually I speak language that has many forms, not only singular/plural but a different forms for 1,2,3... etc. so it's natural for me to see such code everywhere.
