### ISSUE TITLE
Vimeo OAuth 2 Support

### ISSUE THREAD

**Issue by QuillOmega0** [calzoneman/sync#462]
Vimeo oauth v1 is deprecated and is no longer usable.

Looking at the config I found no way to enable oauthv2 and the terms don't match up with v2.

Is API support for v2 planned?

**Comment by calzoneman** [comment]
Man, fuck vimeo.  YouTube gave me a year's notice that they were deprecating their API and sent an email to my developer account to remind me.  I wasn't even aware that Vimeo was planning to deprecate their old API.

I guess I'll look into it, I just literally did not have any idea they did this.

**Comment by calzoneman** [comment]
Closing this for now since we discussed in PM why this wouldn't really solve your problem.
