### ISSUE TITLE
user deletion button

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#464]
I keep getting between 1-3 emails a week from people who want to delete their account. A button in the userlist in acp would be nice and/or a button on the profile tab or something for users to click themselves without me having to do it.

**Comment by calzoneman** [comment]
I'm curious what the motivation is for deleting accounts to begin with.  The only identifiable account data is email address, password, and profile, all of which can easily be wiped by the user and the account just abandoned.  I'll go into detail about the technical issues tomorrow.

**Comment by ghost** [comment]
I agree but users don't understand that's how user accounts work. Accounts
could also be set to be deleted after a set number of days without being
used like on irc services. Would prevent the database getting full of
unused accounts. Another idea could be to put in a link underneath the
change password/email page to the wiki with a page explaining why we don't
have a delete button.

**Comment by calzoneman** [comment]
> Accounts could also be set to be deleted after a set number of days without being used like on irc services. Would prevent the database getting full of unused accounts.

Well if accounts were automatically deleted then it would make sense to add an interface to do it manually as well.  Unfortunately, deleting accounts presents some issues:
- It's inconvenient from a programming perspective, although the newer schema as of last summer makes it somewhat easier.  You'd need to delete information about the user (users table, channel_ranks table, user_playlists table), and decide what to do with other information associated with the user (channels the user owns, bans for that name).
- It opens up avenues for social engineering attacks.  Admittedly this is a stretch, but if a high profile user gets mad and deletes their account, someone could re-register it and trick people into modding the account again or something.

That said, I don't see any reason why, assuming the appropriate information is deleted from the database, anything would break as a result of deleting a user.

Another option is to add soft-deletion, that just flags an account as deleted, erases the profile/email information, and sets the password hash to NULL, thus rendering the account impossible to log into and removing any identifying information from the account.

**Comment by Xaekai** [comment]
Ideas on this:
- Require the user to delete all their channels first.
- Mark the account as in "dormant state" which makes it unusable for 90 days
- Once the 90 days have passed delete everything.

This would prevent abuse of reuse of deleted accounts for social engineering via impersonation / ban evasions.

I also like the idea of autodeletion for seemingly abandoned accounts. Perhaps starting at 6 months for accounts that are barren of profile, email, and channels, with some sort of logic to make it longer for accounts that actually seem to have been used.

**Comment by calzoneman** [comment]
I think I will actually pick this up.  My thought is:

  * Require all channels to be deleted or have ownership transferred first
    - May want to add another feature for transferring channel ownership
  * Display the standard scary warning etc. etc.
  * Mark the account as "flagged for deletion" for 7 days to prevent abuse and to allow that guy who somehow does this accidentally to run to the admins for help
  * Have a cron purge flagged accounts (but not bans)
