### ISSUE TITLE
Emote list scrollable

### ISSUE THREAD

**Issue by zedmike** [calzoneman/sync#469]
It would be an improvement if the emote list was scrollable instead of the buttons for every line of emotes.

**Comment by calzoneman** [comment]
@zedmike You mean like this?
![2015-05-02-115322_1166x784_scrot](https://cloud.githubusercontent.com/assets/385672/7441902/e12bcbfc-f0c1-11e4-8d19-1eeedb13716e.png)

**Comment by shlomogoldberg** [comment]
how deep can we go





































































































































































































































































































































































deep

**Comment by zedmike** [comment]
No that one:
![](http://i.imgur.com/jd2ns6A.png)

**Comment by calzoneman** [comment]
@zedmike That is not currently a core feature.  I do intend to add an emote list as a core feature at some point, but if you have an emote browser currently then that is provided by a custom script and you need to contact the author of that script with any suggestions.
