### ISSUE TITLE
Youtube video duration and title retrieval problems

### ISSUE THREAD

**Issue by dkotel** [calzoneman/sync#471]
As of today all Youtube videos added will report their duration as being 3:56 regardless of actual length. Cytube will switch to the next video in the playlist once this time has been reached, even if the video is not over. A work around for this issue is to give someone leader status. This will allow the video to keep playing after the incorrectly reported video time.

Video titles are no longer being pulled correctly either. All videos added from YouTube are labeled as "https://youtube.com/devicesupport".

**Comment by ghost** [comment]
Have you updated to latest version and added a v3 youtube api key? If you follow the youtube link it tells you you are still using the v2 api which has been discontinued.

**Comment by calzoneman** [comment]
@dkotel YouTube deprecated the v2 API a year ago, and as of this week it has been rigged to only return that specific video, after which it will be turned off completely: http://youtube-eng.blogspot.com/2015/04/bye-bye-youtube-data-api-v2.html

The solution is to update CyTube to the latest version (or apply this commit: https://github.com/calzoneman/sync/commit/27a50cb702bac4302641fb2566edcb68dacd7769), register a v3 API key, and configure CyTube to use it.

**Comment by calzoneman** [comment]
You can find instructions on how to create an API key [here](https://gist.github.com/calzoneman/b5ee12cf69863bd3fcc3#file-youtube-py-L33-L38), and then you need to add the key to your `config.yaml` like so:

```
youtube-v3-key: blahblahblahthekeygoeshere
```
