### ISSUE TITLE
ffmpeg - fixes for debian

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#476]
Leaving this here as more of a note to myself than anything else.

A combination of Debian having old versions of everything in stable and using libav instead of ffmpeg creates some issues for CyTube's ffmpeg module.
- Instead of `ffprobe`, the binary is `avprobe`.  CyTube should try both (perhaps at startup?) and figure out which one exists.
- The version of `libav-tools` in wheezy (oldstable) does not support VP9, hence causing errors when people try to add VP9 encoded webms.  The version in `wheezy-backports` does, but has an incompatible output format with the format used by ffmpeg and older versions of libav.
- The newer version of libav supports a JSON output (convenient!), and so does the version of ffmpeg in Arch, however old versions of libav/ffmpeg do not have this output format and must be parsed as before.

As a consequence of the last 2 points, CyTube will have to feature detect, prefer the JSON output format if available and fall back to the old format if not.  Thank you, Debian for making stable software so difficult to work with.

**Comment by Xaekai** [comment]
Since CyTube only enables raw files if the ffmpeg option is set in config.yaml, maybe you should put the burden on the user to specify the binary if its not ffprobe?

**Comment by ghost** [comment]
Or you could just force people to install/update ffmpeg themselves. Its not
that hard and if they can't do that they shouldn't be running a server.

**Comment by calzoneman** [comment]
> Since CyTube only enables raw files if the ffmpeg option is set in config.yaml, maybe you should put the burden on the user to specify the binary if its not ffprobe?

I considered that, but I think it may be worth autodetecting avprobe anyways because virtually every Debian-based OS uses libav instead of ffmpeg.

> Or you could just force people to install/update ffmpeg themselves. Its not that hard and if they can't do that they shouldn't be running a server.

The problem in this case is that simply updating is not enough; the version of `libav-tools` in `wheezy-backports` is the one with the weird format, and presumably that is the version that is also in `jessie` now.  I'd rather not require people to install ffmpeg from a custom repository.  Regardless of whether a server admin should be able to do that, many of them will not be able to.  I'd rather add support for the JSON output (which shouldn't be hard) than deal with a ton of emails/IRC PMs about ffmpeg not working.
