### ISSUE TITLE
Support YouTube Livestreams (preferably before Saturday 23rd May)

### ISSUE THREAD

**Issue by justjanne** [calzoneman/sync#481]
Currently YouTube livestreams are marked as "Video not embeddable", even though the normal YouTube player is supported.

It should be easy to add support for it, as one doesn’t has to care about being in sync (I’d say support for live-only playback should be enough for the beginning).

Why Saturday 23rd? That’s when Eurovision is live on TV (the largest TV event worldwide with twice the viewership of the Superbowl even) and the channel I’m in would like to see it live through the official YouTube stream in our current cytube channel.

**Comment by ghost** [comment]
Can't you just use an iframe?

**Comment by calzoneman** [comment]
@justjanne YouTube livestreams are already supported-- I just tried adding https://www.youtube.com/watch?v=sw4hmqVPe0E (selected randomly from videos marked as "LIVE NOW") and it works as expected.  The error message "Video not embeddable" indicates that the uploader (in this case, streamer) has disabled third-party embeds of the video, meaning it can only be watched on youtube.com.

@bush6 Not relevant in this case.  If a video is marked non-embeddable, then the iframe code given by YouTube won't work either.

**Comment by calzoneman** [comment]
However, this is a good indication that I should change that error message to be clearer.
