### ISSUE TITLE
Constant Buffering when YouTube is paired with ps3

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#482]
As the title says. i'm lazy and didn't post this earlier :^).

Edit : https://youtu.be/1fDOs5De3HI (i don't even know if im allowed to put links here)

**Comment by calzoneman** [comment]
You can try increasing the Synch threshold (under Options and Playback), or disabling synchronization altogether and that may help with clients that buffer too slowly to keep up.  Other than that, this is an issue on your end.

**Comment by ghost** [comment]
if i increase the sync threshold it still buffers. if i disable sync it
does not auto play the next video.

On Sun, May 24, 2015 at 9:23 AM, Calvin Montgomery <notifications@github.com

**Comment by nuclearace** [comment]
I'd blame that on the PS3 browser being bad. I'm surprised it works at all.

**Comment by calzoneman** [comment]
nuclearace is right, this is a problem with your PS3.

**Comment by ghost** [comment]
I had a ps3 it couldn't stream on WiFi due to shit WiFi bandwidth in ps3.
Try using Ethernet.

**Comment by ghost** [comment]
I'm Using the Play Station 3 YouTube app. i am using Ethernet. i have 27 Mbps down and 5.5 Mbps up on my ps3.
