### ISSUE TITLE
Chat length isn't capped correctly

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#484]
There's a check in `addChatMessage` that removes the oldest line in `#messagebuffer` before adding a new one.

The problem here is a bunch of callbacks also add lines directly, bypassing that check, and it only ever removes a single line. So if a user's on a flaky connection in a busy room, each time they reconnect the chat permanently ends up 2 lines longer due to the connect and disconnect messages.

I've fixed it in flussence/sync@41f09278b523 if you'd like to cherry-pick that. That commit also makes the limit adjustable, in case channels want to tweak it themselves.

**Comment by calzoneman** [comment]
Have you stress tested your fix at all?  The original code isn't the most efficient, but I'm concerned that running a relatively complicated selector on every chat message might lag on some busier rooms where there are dozens of messages per second.

**Comment by calzoneman** [comment]
A quick jsfiddle shows it's not that much worse than the most efficient non-jQuery I could come up with.

**Comment by ghost** [comment]
You have a point, I just tried both and the original code is about 5x faster (10 per second on my desktop here, for 10000 iterations). They're both much slower than I thought.

Changing the `$` to `document.querySelectorAll` on my version doesn't seem to make a difference, but replacing the original code with `getElementById` and `childElementCount`/`firstElementChild` makes it run 655 loops per second. Sounds like it'd be worth a shot...

**Comment by calzoneman** [comment]
The original being a lot faster makes sense because it only removes 1 element (which is bugged behavior).  See if you can improve `testCalzoneFix` in this jsfiddle, I tried my best at native DOM but maybe you can find a way to make it even faster: https://jsfiddle.net/1w26kkz2/1/

**Comment by calzoneman** [comment]
`childElementCount` and `firstElementChild` sound promising.

**Comment by ghost** [comment]
I'm looking at the supported browsers for those now, seems fine as long as not working in < IE9 isn't a problem.

**Comment by calzoneman** [comment]
I'm not sure if CyTube currently works with IE8 or not.  In any case, I'll probably go with a solution that supports it even if it's suboptimal for now, since I'm about to leave for vacation and I don't want to inadvertently break something right before I leave.

**Comment by ghost** [comment]
In that case, `childNodes` and `firstChild` should be safe to substitute in, since I don't think the JS adds anything but elements to the message buffer anyway.

**Comment by calzoneman** [comment]
Ok, I think I'll go with this since it's a bit faster than what I posted before:

``` javascript
var buffer = document.getElementById('buffer');
var count = buffer.childNodes.length - CHATMAXSIZE;
for (var j = 0; j < count; j++) {
    buffer.firstChild.remove();
}
```

**Comment by ghost** [comment]
I came up with something slightly late here: https://jsfiddle.net/1w26kkz2/2/

Though the difference is pretty much rounding error at this point; what you've just posted looks fine to me.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/d9f06a50de5977effe86f8bbc4a37ac44e7487d6
