### ISSUE TITLE
Add support for VP9 WebM

### ISSUE THREAD

**Issue by cobrafast** [calzoneman/sync#485]
When trying to add a WebM with the VP9 video codec, an error appears and the video is not added.
Please add support for VP9 encoded videos.

(VP8 seems to work fine)

**Comment by calzoneman** [comment]
VP9 is supported by CyTube.  Whether or not it is able to be added is determined by whether the server's version of ffmpeg supports it (if you're using Debian Squeeze or equivalent, the version of libav is too old to support VP9).

cytu.be is currently using the squeeze stable version of libav, and hence it cannot query VP9.  I plan to update it, but I am going on vacation and don't want to risk breaking something before I leave.

**Comment by calzoneman** [comment]
For reference: CyTube uses a [whitelist](https://github.com/calzoneman/sync/blob/3.0/lib/ffmpeg.js#L15) of allowed codecs (that can be played in most browsers), however if ffmpeg is unable to read any of these then that causes problems.
