### ISSUE TITLE
Direct BrodCast Vs PalyList

### ISSUE THREAD

**Issue by shpedro** [calzoneman/sync#492]
First of all, this is an excellent product.
Congratulations.
But I would propose an "improvement".
The ability of visitors seeing the videos Live, or Playlist.
We not always put the programs in the best hours for everyone, but if we could choose what to see from the channel playlist. that would attract more visitors.
A Small "Go Live" button to synchronize with the server. And if you choose "Go Offline" can see and select any content from the playlist.

**Comment by calzoneman** [comment]
The title of each video in the playlist is also a hyperlink that, when clicked, opens the video in a new tab.  This way you can open playlist videos separately from the channel.

I don't really see the point of using the embedded player if you're not going to watch it synchronized.

**Comment by shpedro** [comment]
i didn't think about the links. you are correct that will work

2015-06-22 22:29 GMT+01:00 Calvin Montgomery notifications@github.com:

> The title of each video in the playlist is also a hyperlink that, when
> clicked, opens the video in a new tab. This way you can open playlist
> videos separately from the channel.
> 
> I don't really see the point of using the embedded player if you're not
> going to watch it synchronized.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/calzoneman/sync/issues/492#issuecomment-114267871.

## 

Pedro Ferreira
about.me/shpedro
[image: Pedro Ferreira on about.me]
  http://about.me/shpedro
