### ISSUE TITLE
Per rank channel limit

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#508]
There is an option to have a limit on the number of channels each user can register. But it doesn't allow filtering on the user global rank.

**Comment by calzoneman** [comment]
What are you proposing?  I could see allowing admins to bypass the channel limit, although this is a rare case (I've only needed more than 5 channels once, and that was on a test server, so I just bypassed the limit temporarily).

"Per rank" sounds like over complication.  Although `global_rank` is an integer field, for most purposes it is actually used as a boolean (is this user under or over rank 255?).  In future releases, the database schema is being changed to replace the `global_rank` field with an `is_admin` flag.

**Comment by henke37** [comment]
Well at its simplest, it would be having a limit of zero channels for most users and only allowing a few users to create channels.

**Comment by calzoneman** [comment]
Hmm, that is a use case I didn't consider when designing the software.  The solution I proposed (channel limit is enforced for everyone except global admins) would allow you to prevent everyone except admins from creating channels by setting the limit to 0, but that would not handle the case of having other values for `global_rank`.

As I said, I'm planning to get rid of `global_rank` completely and just replace it with a boolean flag for whether the user is a website administrator.  It sounds like you have a different use for this than anyone else running CyTube.

**Comment by henke37** [comment]
It does seem that way yes. But it doesn't seem like this refactoring you want to do would be a problem in my use case.

**Comment by calzoneman** [comment]
As far as the feature "users with global_rank >= 255 are not subject to the channel registration limit", I'm willing to implement that.

**Comment by henke37** [comment]
Yeah, that makes sense, no matter the use case.
