### ISSUE TITLE
Global emotes

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#509]
There is usually a desire for a default set of emotes for all channels. Sure, some channels will want to override/replace/remove them, but it's a default.

**Comment by calzoneman** [comment]
> There is usually a desire for a default set of emotes for all channels.

[citation needed]

I can only really see this being useful for servers hosting a bunch of channels related to one community.  For cytu.be, I don't really see this as being desirable, since there is a huge variety in the interests of channels and each one has different ideas of what emotes they want (movie gifs for the movie rooms, pony emotes for the MLP rooms, anime emotes for the anime rooms, etc.).

**Comment by henke37** [comment]
Exactly, it's useful for setups for a single community. And even your main site could use some variant of the stock yellow circle faces.

**Comment by calzoneman** [comment]
> And even your main site could use some variant of the stock yellow circle faces.

Ehh...

You can take a stab at this if you want, but based on my current list of things that have been requested or I want to do and the rate at which I'm getting work done on CyTube, I probably won't be able to pick this one up for a few months.  In the meantime, you can use the export/import emotes feature to provide a predefined emote list that people can copy and import into their channels if they wish.

**Comment by Xaekai** [comment]
I personally think this is a terrible idea.

Especially if you plan on using things like :-) as emote codes.

But if you do do it:
:duane:
![:duane:](http://i.imgur.com/rK30Y3g.gif)

Establish that :emote: syntax. Purge the /emote and #emote heretics.

**Comment by calzoneman** [comment]
:^)

**Comment by Xaekai** [comment]
![:^)](http://i.imgur.com/ae44QR7.gif)

**Comment by calzoneman** [comment]
As of right now I have no plans to add this.  Closing it as wontfix -- we can discuss it further if the topic comes up again.
