### ISSUE TITLE
Skip long list warnings for small setups

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#510]
Surely it's possible to detect roughly how many channels/users there are and skip the show all prompt for those reports when there aren't very many? While at it, why not show the full dataset by default in such cases? Oh, and a small note in the space for the dataset about no query having been made would be nice too.

**Comment by calzoneman** [comment]
This warning is clientside, not serverside.  When you submit an empty query, that gets translated into a `SELECT * FROM users WHERE name LIKE '%%'`, which is a full table scan.  This is usually not what you want, regardless of table size.  The user and channel browser isn't designed to be a fully featured table browser like phpMyAdmin.  It's just a quick way to search for specific users/channels without having to query the database manually (it's expected that 99% of the time you would be using this feature, you would have a nonempty query).

**Comment by henke37** [comment]
A full table scan can indeed be costly for large tables. But it's always cheap to check how much data there is in the table. Time-of-check-to-time-of-use doesn't really apply here, it's fine to have slightly stale data. If the number of rows changes enough to matter in the short timespan then there is a much bigger problem.

**Comment by calzoneman** [comment]
The cost of checking the size of the table is not the issue.  The issue is that if you're submitting empty queries enough to get annoyed by the popup confirmation message, then you're using it in a way that was not intended.
