### ISSUE TITLE
Resumption of autolead inadvertently moves on to next video when a livestream is playing

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#513]
Steps to reproduce:
1.) Queue and play a livestream feed
2.) Assign leader
3.) Remove leader

**Comment by calzoneman** [comment]
Yeah I read IRC backlog and pretty much knew exactly where the problem is.  `startPlayback()` has special logic that checks for live media and doesn't kick off the timer loop, but `handleAssignLeader()` bypasses that and starts the timer itself when resuming autolead.
