### ISSUE TITLE
Normal layout as an option

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#519]
The layout menu doesn't include the normal layout. This requires an annoying reload when you want to go back to the normal layout.

**Comment by calzoneman** [comment]
Both of these are not intended to be things that you would undo later.  I understand that there is a use case for "Remove Video temporarily and then bring it back later", which should be a separate feature that some channels have added to their channel js (I just haven't gotten around to implementing it in core), but both of the "Layout" options are intended to be one-way.  If you can think of a better name for that dropdown, I'm glad to consider it.

Chat Only is basically unrecoverable, unless you want to reconstruct the entire page from JavaScript which is hacky and ugly.  It doesn't just hide everything, it completely removes everything except for the chat div.
