### ISSUE TITLE
Rooms information retrieving API

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#52]
Did you ever thought about creating simple CyTube API for retrieving information about rooms?

Everyone could paste on their websites a piece of code displaying current title, number of connected users etc.

**Comment by calzoneman** [comment]
Yeah I'll look into adding a JSON API for data and perhaps an embed code for a little channel widget.

**Comment by calzoneman** [comment]
You can access channel data by sending a `GET` request to `/api/json/channeldata?channel=channelname`.

A small widget that you can source, for example, in an iframe is available at `/channelwidget.html?channel=channelname` (this is broken at the moment, but I'm going to fix it).
