### ISSUE TITLE
Add Gravatar support by default. 

### ISSUE THREAD

**Issue by Leopere** [calzoneman/sync#520]
These things are pretty handy.  Since you can just set one avatar everywhere in one place thanks to wordpress.
An example of a gravatar url generator.
[http://asaph.org/gravatar/](http://asaph.org/gravatar/)

Gravatar itself. 
[http://en.gravatar.com](http://en.gravatar.com)

**Comment by calzoneman** [comment]
Can you clarify what this request is?  You can already use a gravatar URL as your profile image if you wish.

**Comment by Leopere** [comment]
Just to pull the gravatar URL by default with no user input required unless you want to try something else instead.

**Comment by calzoneman** [comment]
How does CyTube know the Gravatar URL for the user's avatar without them specifying it?

If you mean generating a random avatar for users who don't explicitly set one, I don't really see the value in that.

**Comment by Leopere** [comment]
The way that gravatar works is that, you have an email that is hashed and then appended to the end of the gravatar url with some modifiers in the URL to adjust the size and rating (parental guidance ratings) of the avatar used.  

The url uses a hash so that you're not giving out everyones email address just to embed their Avatar.  There are a lot of people who use Gravatar and any avatar might be better than no avatar.  I suppose this is my only case for this suggestion because from what I've seen the generator I linked above is the only publicly facing one I've found.  Normally its up to the service providers to provide integration.

**Comment by calzoneman** [comment]
> The way that gravatar works is that, you have an email that is hashed and then appended to the end of the gravatar url with some modifiers in the URL to adjust the size and rating (parental guidance ratings) of the avatar used. 

Not every user has an email address, and I'd rather not generate a random one just for the purpose of getting a Gravatar image.  I'm not sure I agree with the statement "any avatar might be better than no avatar".  I provided avatars as a small feature for people who choose to use them, not as an integral part of the service.  I don't think that it really detracts from the experience that some people choose not to have avatars; perhaps others disagree.

**Comment by Leopere** [comment]
I don't believe that I ever implied that not having it was a bad thing it was only suggested as a convenience thing.

**Comment by calzoneman** [comment]
I struggled for a few minutes to come up with a wording for the above comment that didn't sound abrasive/defensive.  I'm not saying your idea is stupid, I was just giving a reason for why I closed this out.

**Comment by Leopere** [comment]
Thats fair, I just enjoy the ability to change one avatar and than the rest of the internet just has that avatar.  

A lot of context can be lost in text based conversations.
