### ISSUE TITLE
Fresh install, missing JS variables

### ISSUE THREAD

**Issue by jaw-sh** [calzoneman/sync#527]
I've set up my synctube up using a proxy_pass on nginx like cytu.be, but when I open a channel I get errors.

```
ReferenceError: IO_URL is not defined callbacks.js:1104:9
unreachable code after return statement all.js:1:23867
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create video.js:13483:415
```

The page takes about 30 seconds to fatten because the JS takes to long to execute, then it complains about missing information. I followed the instructions exactly and other aspects of the site work aside from the player.

**Comment by calzoneman** [comment]
That variable no longer exists and is still referenced in an error handler.  I'll have to update the error message not to depend on it.

**Comment by jaw-sh** [comment]
I closed this ticket after deducing that the issue came from the socket 
not being setup correctly.
