### ISSUE TITLE
[Enhancement] Would it be possible to be able to up vote people for posting stuff that we like?

### ISSUE THREAD

**Issue by Leopere** [calzoneman/sync#529]
There's not much else to this other than basically letting us give each other up votes.

We have a more social channel that we would like to let a more open audience be capable of posting videos.  I can elaborate more if you have questions.

**Comment by nuclearace** [comment]
This was suggested in another issue that was rejected. I don't really see the point in it

**Comment by Leopere** [comment]
It was part of PlugDJ.  It would just be nice to be able to earn reputation for playing entertaining things.  It doesn't have to be a cytu.be global rank maybe just a per channel rank.  A little competition never hurt anyone.  It usually increases peoples interest being able to have something to shoot for.

**Comment by calzoneman** [comment]
This has come up a few times, and it's just one of those features that I don't really see bringing a lot of value to the site.  It's tricky to define the boundary for what to accept and reject, but the line has to be drawn somewhere lest CyTube become an incoherent jumble of unrelated features, and so far this feature has not made it above the line.

That said, some channels have chosen to implement their own "points" systems by means of a chat bot that keeps track of points per user (for example, the "perds" feature of fullmoviesonyoutube's bot), and I think doing it that way is a good compromise.  It allows you to customize how the system works, and it doesn't add any unnecessary cruft to the core software for other channels with no interest in using it.
