### ISSUE TITLE
Login/Register form bugs

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#53]
When I try to log into existing account, the window pops out with message "That username is already taken"
When I try to register, it says "I dunno what went wrong" (Derpy reference? :D)
Also, youtube player is overlapping modal window in the room.

**Comment by calzoneman** [comment]
Did you apply the SQL from the commit message?  I added new columns to the `registrations` table, so if those columns aren't present then all logins/registrations will fail.

``` SQL
ALTER TABLE `registrations` ADD `session_hash` VARCHAR( 64 ) NOT NULL ,
ADD `expire` BIGINT NOT NULL
```

As for the overlap, which browser are you using?  I just tested with Firefox 20 and Chromium 26 (both using Flash for YouTube) and the video was behind the modal, as expected.

**Comment by calzoneman** [comment]
Let me know if https://github.com/calzoneman/sync/commit/6eaa97ccb8be1b7b4420959c84aa6e9c024e99c2 fixes your modal z-index issue.

**Comment by calzoneman** [comment]
The username is already taken bug should be fixed by https://github.com/calzoneman/sync/commit/d5fc0bb03dedf50d1eb0d809b5c152ffbc6232d9

**Comment by calzoneman** [comment]
Please confirm this is fixed

**Comment by ghost** [comment]
Yep, it works. I'll pay more attention to commits messages,
