### ISSUE TITLE
joining a channel while the current video is paused will loop the first 5 seconds, over and over again, ad infinitum, until unpaused

### ISSUE THREAD

**Issue by sariyamelody** [calzoneman/sync#531]

**Comment by calzoneman** [comment]
I'm assuming that you mean someone has leader and has paused the video, since there is no other valid way for a CyTube channel to have a paused video.

Can you give an example of a video where this happened to you?  I just tried several times to reproduce this with a YouTube video and I was not able to make it happen-- occasionally it took a few seconds before pausing, but it always paused and did not loop.

**Comment by ghost** [comment]
I have this issue too, it only works with multiple people in the room though.
It doesn't only happen when I'm joining though, it happens any time the leader pauses it.
It also happens when the leader is buffering.

I would provide a webm of it happening, but I'm on my laptop right now I'm afraid.

**Comment by calzoneman** [comment]
Can you provide a link to a video where this happens, or at least the kind of video it is (YouTube, Vimeo, etc.)?  They are all implemented individually, so it's likely that there is a bug in a specific video type.

**Comment by calzoneman** [comment]
> It also happens when the leader is buffering.

This is expected.  CyTube does not attempt to correct for leader buffering, and this is one of the reasons I recommend limiting its use.  You should only take leader if you need to seek the video or pause it, and then give leader back once you've done this (the transition is seamless; you can seek and then remove leader and the server will continue from that point forward).

CyTube will only automatically pause if the leader has intentionally paused the video.

**Comment by calzoneman** [comment]
This needs an example case.  Without being able to reproduce the problem I am not able to track down where it happens.

**Comment by sariyamelody** [comment]
@calzoneman I'll get you one as soon as possible; sorry for missing the previous communications! I've been really busy recently. Thanks for getting in contact!

**Comment by calzoneman** [comment]
Is this still an issue?

**Comment by sariyamelody** [comment]
Yeah, I think it's still an issue. Not wholly sure what's causing it,
unfortunately – how can I help?

**Comment by calzoneman** [comment]
I'm still waiting on a test case to be able to direct my investigation of this.  Even if it doesn't happen 100% of the time, just knowing that it happens for a particular video type would be helpful in narrowing down the scope of the problem.

**Comment by sariyamelody** [comment]
Sorry it's taking so long in between replies – I'm really busy recently :-(

It seems to consistently happen with YouTube videos. I've never been the leader in a case when it's happened, or if it has, my boyfriend has just not said anything. I think what's happening is that the leader is paused at the start of a video. I'll try to get a repro case, but until I have more free time, I think @Jeviny would be a better avenue to pursue. :disappointed:

**Comment by calzoneman** [comment]
Where in the video the leader is paused shouldn't make a difference; the leader broadcasts synchronization updates every 5 seconds which would include the `paused` attribute that causes clients to pause.

If you wouldn't mind, the next time this happens could you open the JS console (Ctrl+Shift+J on Chrome or Ctrl+Shift+K on Firefox; make sure you click on the "Console" tab), and type in `SOCKET_DEBUG = true`, press enter, then wait several seconds and screenshot it?

It should show something like

```
mediaUpdate Object {currentTime: 0.13517, paused: true}
```

**Comment by sariyamelody** [comment]
I'd be happy to do that!
It'd almost as if we're getting `currentTime` updates and not `paused`
updates. So strange.

I'll be sure to do that when possible.

**Comment by calzoneman** [comment]
Is this still an issue?

**Comment by Rikudouu** [comment]
I'm having this issue too. After the leader, the video will keep looping and does not pause. It works sporadically. I think if the current leader refreshes, and then gives themselves leader again, and pauses, it'll work. It works more often then not though, just takes a couple tries.

**Comment by calzoneman** [comment]
Does this happen consistently for you?

**Comment by Rikudouu** [comment]
Nope. I think the best way to describe it is a bad leader 'instance'. If you're a leader and you are on a bad instance, the video will keep looping.  If you refresh the page and give yourself leader,  and then try to pause, it'll work. 

It's pretty random on what instance you get. I'm on mobile right now but I'll get the logs when I get a chance.

**Comment by calzoneman** [comment]
The video loops for the leader as well?  Or only for the other viewers?

**Comment by Rikudouu** [comment]
Just for other viewers. For the leader it looks normal and it's paused.

**Comment by calzoneman** [comment]
What kind of video was this?  YouTube?

**Comment by Rikudouu** [comment]
Yep, a YouTube video.

**Comment by Rikudouu** [comment]
OK, I have a looping instance right now. It keeps looping infinitely. Even pausing it as a viewer that's a non-leader won't help. The video will unpause and continue to loop.

**Comment by calzoneman** [comment]
Can you give me a link to join?  And can you also have the leader open the JS console (F12) and give the result of `PLAYER.paused`?

**Comment by Rikudouu** [comment]
http://:8080/r/test

Link for instance.

**Comment by calzoneman** [comment]
My increasing suspicion is that the root cause of this issue and #556 is a bug in either the YouTube API, or in CyTube's wrapper around it that causes the leader to report the player as unpaused when in fact it is paused.

**Comment by Rikudouu** [comment]
How would I get the player,paused from the leader?

**Comment by calzoneman** [comment]
Can you have the leader check `PLAYER.paused`?

**Comment by calzoneman** [comment]
Can you also try having the leader run

```
PLAYER.yt.addEventListener("onStateChange", function (state) { console.log('NEW STATE IS ' + state.data) })
```

in the console _before_ pausing, and then have them watch for output when they pause the video?

**Comment by Rikudouu** [comment]
Running the above outputs something while playing, but after pausing nothing outputs.

**Comment by calzoneman** [comment]
Can you paste the output here?  This pretty much confirms my suspicion that for whatever reason, the pause event is not being triggered by the YouTube player for certain clients.

**Comment by Rikudouu** [comment]
I'm very sorry but I'm really new to this, so if I get some things wrong, please correct me.

Here is the output.

`X {b: Mb, a: iframe#ytapiplayer.embed-responsive-item, h: div#ytapiplayer.embed-responsive-item, closure_uid_245055111: 1, g: 1…}`

**Comment by calzoneman** [comment]
So when you pause the video (either by clicking or by using the pause keyboard shortcut), you don't see "NEW STATE IS 2"?

**Comment by Rikudouu** [comment]
Nope. Other than what I posted above, there is nothing else being outputted to console.

**Comment by calzoneman** [comment]
That's very strange, it seems like YouTube is not firing the pause event (that or another event handler is causing an error, but you didn't note any errors in the console output).

**Comment by Rikudouu** [comment]
I'll post a screenshot of what the console looks like.

**Comment by Rikudouu** [comment]
![image](https://cloud.githubusercontent.com/assets/12927314/16860739/81a428f4-49ef-11e6-9cc7-a3225782486e.png)

**Comment by calzoneman** [comment]
One last thing, can you check what the output of `PLAYER.yt.getPlayerState()` is?

**Comment by Rikudouu** [comment]
1

**Comment by calzoneman** [comment]
Ah that fully confirms that YouTube is screwed up, I'll have to try to reach out to them and check if there's any workaround.

**Comment by Rikudouu** [comment]
PLAYER.paused

is false

Even though the video is paused on my end.

**Comment by calzoneman** [comment]
You mentioned that if you refresh the page then it works right?

**Comment by Rikudouu** [comment]
Yeah, It works if I, the leader, refresh the page.

EDIT: Actually, no. I'm trying to do it on my current bugged instance but it's not working.

**Comment by calzoneman** [comment]
Ok, so I'm guessing that the problem is only triggered for you when a few videos have already played and then you try to pause one?

**Comment by Rikudouu** [comment]
No. The channel I'm in is a test channel and this is the first video it's played in a little bit. It got unloaded and it's the first video after getting loaded back in.

**Comment by calzoneman** [comment]
Can you tell me the output of `PLAYER.yt.ready`?

**Comment by Rikudouu** [comment]
After refreshing a ton of times, I also noticed that sometimes, it kinda works. The leader can seek, but once the leader seeks, the video on the viewer's end get's paused where the previous leader seeked to, and then it jumps back to where it was before, while remaining paused at that point. However, for the leader, the video keeps playing from the point the leader seeked to. If I take leader away, then the video jumps back to the previous point (before the leader seeked and the point where the viewer is paused) and continues playing back in sync.

**Comment by Rikudouu** [comment]
the output is true

this is for the one where it's looping for the viewer and paused for the leader.

**Comment by Rikudouu** [comment]
I'm getting a lot of different results now.

After refreshing, it still didn't work. I ran `PLAYER.paused` again while the video was looping for the viewer and paused for the leader and it returned `undefined`. I ran `PLAYER.yt.addEventListener("onStateChange", function (state) { console.log('NEW STATE IS ' + state.data) })`  while the video was playing and then I paused, and this time, it returned something - `www-embed-player.js:219 GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT` I think it's unrelated though, and probably my adblocker.

**Comment by Rikudouu** [comment]
I finally got it to pause. It took many refreshes until it worked. I removed leader, refreshed, gave leader, and paused, and it paused for the viewer side too.

EDIT: After a refresh, it bugs out again, and keeps looping for the viewer.

**Comment by calzoneman** [comment]
Last time I think we tracked this down to an issue with the YouTube player.  Is this still happening?

**Comment by Rikudouu** [comment]
Actually, no. It fixed itself after a couple weeks, and it works perfectly now. I forgot to report it, my bad.
