### ISSUE TITLE
Display album art for raw audio files

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#535]
Many audio files have embeded images in them. Those images are generally interesting to look at while listening to the file.

**Comment by Xaekai** [comment]
While I like this idea, it would require CyTube actually hosting contents from unknown sources, something I believe Cal has been doing his best to avoid (It's best if CyTube is merely a metadata transit and nothing else for a variety of reasons). The browser has no native support for this so the image would have to be extracted and delivered separately to the client.

**Comment by Xaekai** [comment]
Relevant: https://github.com/aadsm/jsmediatags

**Comment by calzoneman** [comment]
Closing in favor of #870
