### ISSUE TITLE
Bind IP address to outgoing request

### ISSUE THREAD

**Issue by bytestostring** [calzoneman/sync#536]
Hi!

My server have 5 IP addresses. Need to change IP address to outgoing request for RAW-videos.
I put in the file **lib/ffmpeg.js** after line:
data = urlparse.parse(url);
next code:
data.localAddress = 'xx.xx.xx.xxx';
And restart cytube.

Cytube writed: **Error Unable to query file data with ffmpeg**

if I change data.localAddress to default bind IP then all is OK.
But I very needed to change on another IP.
All IP is corrected, and worked in the PHP-language (curl).

Any ideas?

**Comment by stigout** [comment]
Sorry, not "before", I want to say "after".
Thanks!

**Comment by calzoneman** [comment]
CyTube sends an initial request to the URL to catch common errors and report them to the user.  However, once this check succeeds, it calls `ffprobe` to do the actual video data lookup.  It is when this fails that this error message occurs.

You can check error.log for more detailed error messages.  You may also need to remove this check https://github.com/calzoneman/sync/blob/3.0/src/ffmpeg.js#L258.

From my reading of the man-page of `ffprobe` it does not appear to support overriding the default network interface, so what you are trying to do may not be possible (you can verify this yourself by reading the man page more carefully).

**Comment by bytestostring** [comment]
Thank you for your answer!
