### ISSUE TITLE
Playback control chat commands

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#544]
Let leaders pause and seek the video using the chat instead of interacting with the embedded player.

**Comment by calzoneman** [comment]
I don't really see the value in adding a second, nonintuitive way of controlling player state.  Can you explain the motivation?

**Comment by henke37** [comment]
Sometimes it is just quicker to type a command than to fiddle with the mouse to hit the pause button.
It is also a lot quicker compared to trying to fiddle with the seekbar. It is also easier to be precise, the two level seekbar in youtube is nice, but it doesn't fully solve the seconds vs pixels problem.

Also, this eliminates a dependency: the player itself. People who choose a layout without it can't control the video.

**Comment by Xaekai** [comment]
1.) A channel admin needing to control the video while not viewing it themselves is a corner case.
2.) It would trivial to add this yourself using Channel JS
3.) This functionality already exists in CytubeBot

**Comment by Xaekai** [comment]
This should be closed due to inactivity.

**Comment by calzoneman** [comment]
Closing.  The existing chat commands are a carry-over from having used IRC for years, where the text-only interface precludes having UI widgets to take certain actions.  I'm actually considering removing chat commands as a server-side feature, and for backwards compatibility, implementing the existing commands as clientside shims that send the appropriate socket.io command.
