### ISSUE TITLE
index file try/catch suggestion

### ISSUE THREAD

**Issue by katanacrimson** [calzoneman/sync#546]
On line 2 of the index file, sync wraps the require in a try/catch, and then suggests to the user to be sure to run the babel rebuild of the codebase if they haven't.  In my case, it turned out I needed an npm rebuild - this might be worth suggesting instead if `err.message.indexOf('module version mismatch') != -1`.

**Comment by calzoneman** [comment]
Thanks for the feedback, I've updated the error logging to present more possible causes that I know of, and explicitly present the `npm rebuild` / remove node_modules and `npm install` solution if `module version mismatch` is encountered.
