### ISSUE TITLE
Buttons under the video do not function in the Synchtube layout

### ISSUE THREAD

**Issue by JorgenPhi** [calzoneman/sync#548]
When the user layout is "Synchtube" and the window size is smaller than the mobile width, the buttons located here do not function (with the exception of the "Emote List").

<img width="495" alt="screenshot 2015-12-27 16 52 37" src="https://cloud.githubusercontent.com/assets/3020272/12012455/425f6712-acba-11e5-912f-742f77e851bd.png">

**Comment by calzoneman** [comment]
This is because the layout collapse that happens when Bootstrap is resized that small causes the left and right control bars to overlap.  Haven't had time to look into a resolution yet, but it is a known issue.

**Comment by calzoneman** [comment]
This will be fixed once I roll out that commit to the live server (it will be up on beta.synchtube.me in the meantime if you'd like to try it out).  Looks a little ugly, but matches the behavior of non-synchtube layout and is functional.  A complete overhaul of the UI will be needed in the future to support small displays such as mobile devices better.
