### ISSUE TITLE
Login form usability

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#55]
I fully agree with the new more secure login system. But I think you should return old login form on the top navbar.

Why? Because it's more user-friendly. People who don't want to register, or just want to login, need only one click. It's fast and useful. And now you must to click once to display proper login form, move a mouse to it, and then click again. Looking back in synchtube era, a non-registered/registered users ratio was 50/50. It isn't very convenient to do so many actions if you just want to enter for a moment. It may discourages people.

So what I propose: bring back old style login form on the top (it can be iframe, no problem) with one-click login. AND after clicking a "register" button system can display a modal window with register form, just like it is now.

What do you think about it?

**Comment by calzoneman** [comment]
The whole reason I have the modal is to sandbox the login inside of an <iframe> so that custom Javascript on each channel can't access your login details.  I'll see if I can accomplish the same with the old inline login form.

**Comment by calzoneman** [comment]
I couldn't make the inline login form look good with the iframe sandbox, so I've made a compromise.

There's still the modal for logging in with a password and registering, but there's also a quick login for guests.  I think this is fair for a few reasons:
1. It makes it clear that guest logins are possible
2. It makes it easy to login as a guest
3. The cookie expiration on a passworded login is 7 days, so you shouldn't have to bring up the modal every time unless you clear your cookies.

**Comment by uchigawa** [comment]
Thanks, it works great!
