### ISSUE TITLE
CloudFlare - Websocket - SSL - Reverse Proxy

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#552]
Hey there!
I have translated "sync" to Spanish and I'm hosting it for my friends and whoever wants to join.
I've been using an auto-deployable version I made for Amazon Elastic Beanstalk, I'm reverse proxying with Apache with mod_cloudflare so it passes the true IP since this is behind CloudFlare.

Internally the node application runs on port 8080 and it's proxied by Apache to port 80 and this is behind CloudFlare.
Websocket is running on port 1337 on another subdomain that is not behind CloudFlare.

Alright! Until there everything it's fine...

But then I decided to try to implement HTTPS, currently CloudFlare only supports websockets (Beta) for their Enterprise plans and Businesses plan so this is not an alternative for me.
Here comes the problem, when I enable HTTPS the io socket is apparently bounded to the HTTPS port (8443 on my case), and I'm reverse proxying 8443 with Apache to the port 443.
Also even when browsing through HTTP the io socket to be used is still the secure one and not 1337 (insecure one).

So my question is, is there a way to use an specific port for io socket when HTTPS is enabled?
Also another question, what SSL protocol is nginx using? TLS1.2?

Thank you!

**Comment by calzoneman** [comment]
> when I enable HTTPS the io socket is apparently bounded to the HTTPS port

Remove the `io: true` from https://github.com/calzoneman/sync/blob/3.0/config.template.yaml#L27-L32.  This will prevent the websocket listener from using the HTTPS listener.

> what SSL protocol is nginx using? TLS1.2?

I'm not sure why you're mentioning nginx since it sounds like your setup is using Apache.  If you mean the Cloudflare nginx proxy, you would have to ask Cloudflare about their setup.  If you mean sync itself, it would be whatever the version of node you're using defaults to.

**Comment by gamerjota** [comment]
Thank you! The first one worked perfectly.
And about my second question sorry, I have no idea why I asked for nginx, I meant node like you said at the end.
Thanks again!

**Comment by ghost** [comment]
Thank you! The first one worked perfectly.
And about my second question sorry, I have no idea why I asked for nginx, I meant node like you said at the end.
Thanks again!
