### ISSUE TITLE
Embed other channels

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#554]
Twitch does it! And it would make it possible to let others borrow your channel.

Or at least detect the attempt and give a custom error message.

**Comment by nuclearace** [comment]
I don't really see the value in this.

**Comment by calzoneman** [comment]
For twitch, rehosting makes sense because it's a livestream and that's the only practical way to share it among different chat rooms.  I'm not so sure it makes sense to do this for CyTube when you can just queue the same link in multiple channels.

**Comment by calzoneman** [comment]
Closing as I don't intend to add this.
