### ISSUE TITLE
Videos occasionally start looping over a short interval for no reason

### ISSUE THREAD

**Issue by OurFlagIsMined** [calzoneman/sync#556]
It sounds like user error or something, but I just saw it happen for myself. Video was playing, with no leader set, and spontaneously started looping over a short interval (5 seconds or so). It was a YouTube video, 30-60 seconds into playing when it happened. Problem resolved itself once the playlist was cleared, after which the video continued to play while the playlist was empty, from where the looping left off.

It happens for everyone in the channel at the same time, and I can't figure out how to replicate it, so I'm just documenting as much information as possible about the details surrounding the incident, and maybe someone will figure it out. It's happened twice, both times in the past 12 hours, and in two separate channels.

**Comment by calzoneman** [comment]
The next time that this happens, can you open the JS console (Ctrl+Shift+K on Firefox or Ctrl+Shift+J on Chrome, make sure you select the Console tab), enter `SOCKET_DEBUG=true`, and then screenshot the output after 20-30 seconds?  It should show a bunch of `mediaUpdate` debug messages.

**Comment by calzoneman** [comment]
Is this still happening?

**Comment by calzoneman** [comment]
In addition to the previously mentioned clientside debug information, it would be helpful to know the channel name and timestamp when this happened.  You can email it to cyzon@cytu.be if you don't want to discuss it here.

**Comment by headzoo** [comment]
This happened to me last night as well. Video was playing fine for a few minutes, and then like a broken record it would skip back to 0 secs, play until 5 secs, and then skip back 0. Over and over.

I'll keep this issue open in a tab for the next few days so I can quickly refer back to your instructions in case it happens again. I'm just leaving this comment to confirm the bug, but I also don't have any more information to provide.

**Comment by calzoneman** [comment]
Please do, the reason this is tagged unconfirmed is because I've never been able to reproduce it.  It'd also be useful to know what type of video this happens on (YouTube, Google Drive, etc.).

**Comment by elo-siema** [comment]
It happened to me several times as well while playing a generic mp4 video, I'll screenshot the console next time it happens.

**Comment by headzoo** [comment]
I have a new clue. The loop skipping started happening today when I gave leader to a user. It kept happening each time I gave leader to someone, and the loop would stop when I unleadered the user. I didn't get a chance to check the console logs, but the loop restarted every 5 seconds, which matches my playlist.update-interval setting. So I imagine the log would have shown the usual mediaUpdate every 5 seconds, but with the same time value each time.

**Comment by calzoneman** [comment]
I don't suppose you know
1. The link that was playing when the issue occurred
2. The browser being used by the leader

?  If I could get those 2 pieces of information it could help narrow it down.

**Comment by headzoo** [comment]
It was every video we tried, but here's a link to one of the videos. Note that restarting the server didn't fix the problem. But as soon as I removed leadership the looping stopped.

https://www.youtube.com/watch?v=Dbd4h1kaFlY

The leader was using the latest version of Chrome.

**Comment by calzoneman** [comment]
Any chance you could join IRC so we can discuss this further?  I've never heard of anyone being able to consistently reproduce this, so I'd like to join and see what I can see.

**Comment by headzoo** [comment]
I have to take my dog for a walk, but I'll be back on in less than an hour if you're still around.

**Comment by calzoneman** [comment]
Is this still happening?

**Comment by headzoo** [comment]
I can't speak for others, but we discovered in the IRC channel that my bug was caused by giving leader to a user who has the video removed.

**Comment by calzoneman** [comment]
I think the other issues were tracked in the other ticket which was confirmed as resolved.
