### ISSUE TITLE
Synchtube broken?

### ISSUE THREAD

**Issue by maswartz** [calzoneman/sync#558]
I went to this synchtube (https://synchtu.be/r/chrj) and it appears broken, it won't let me type and none of the videos show up I'm using the latest firefox if that matters

**Comment by calzoneman** [comment]
That page loads fine for me.  Check that you don't have JavaScript turned off and try disabling any extensions you have in case one of them could be causing the problem.

For help with synchtu.be, please email bush@6irc.us.
