### ISSUE TITLE
poll timestamps

### ISSUE THREAD

**Issue by techanon** [calzoneman/sync#562]
it would be nice if there was a creation timestamp visible for the polls.

**Comment by calzoneman** [comment]
Why?  Not that it's a difficult feature to add, I'm just curious what the benefit is.

**Comment by techanon** [comment]
Not really any technical benefit to it, but sometimes I'm afk for a while and people make various polls during that time, so it'd be nice to know when they were made at. There are some polls that popup with time sensitive info. More of just a convenience thing.
