### ISSUE TITLE
[SEVERE] Uncaught Exception: Error: Cannot find module './build/Release/cytubefilters'

### ISSUE THREAD

**Issue by AllanVester** [calzoneman/sync#564]
I have installed CyTube by npm install and npm run build-server. 
And this is the code I get when I try to start the server up:

Error: Cannot find module './build/Release/cytubefilters'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (\node_modules\cytubefilters\index.js:1:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (\src\channel\filters.js:1:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by calzoneman** [comment]
The filters module likely failed to compile.  If you run `npm install` and watch the output it probably logs an error saying why.

The most common reason is that you don't have the appropriate compilers/libraries installed.  On Debian or Ubuntu, you would need to run `sudo apt-get install build-essential`.

**Comment by AllanVester** [comment]
I get this then I try to install, any idea how I could fix this? I'm running on Windows, just so you know.

npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> bcrypt@0.8.5 install \node_modules\bcrypt
> node-gyp rebuild

\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Users\veste\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
..\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' to 'unsigned char', possible loss of data [C:\Users
\veste\Desktop\HearAndWatchTogether\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(76): warning C4244: 'argument': conversion from 'ssize_t' to 'unsigned char', possible loss of da
ta [\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(135): warning C4244: 'argument': conversion from 'const ssize_t' to 'unsigned char', possible los
s of data [\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(229): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:
\Users\veste\Desktop\HearAndWatchTogether\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(230): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:
\Users\veste\Desktop\HearAndWatchTogether\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  win_delay_load_hook.c
     Creating library \node_modules\bcrypt\build\Release\bcrypt_lib.lib and
  object \node_modules\bcrypt\build\Release\bcrypt_lib.exp
  Generating code
  Finished generating code
  bcrypt_lib.vcxproj -> \node_modules\bcrypt\build\Release\bcrypt_lib.node

> cytubefilters@1.0.0 install \node_modules\cytubefilters
> node-gyp rebuild

\node_modules\cytubefilters>if not defined npm_config_node_gyp (node "C:\Users\veste\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcre_byte_order.c
  pcre_chartables.c
  pcre_compile.c
  pcre_config.c
  pcre_dfa_exec.c
  pcre_exec.c
  pcre_fullinfo.c
  pcre_get.c
......\deps\libpcre\pcre_dfa_exec.c(76): fatal error C1083: Cannot open include file: 'config.h': No such file or dir
ectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_exec.c(45): fatal error C1083: Cannot open include file: 'config.h': No such file or directo
ry [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_fullinfo.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or dir
ectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_byte_order.c(47): fatal error C1083: Cannot open include file: 'config.h': No such file or d
irectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_compile.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or dire
ctory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_get.c(47): fatal error C1083: Cannot open include file: 'config.h': No such file or director
y [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_chartables.c(24): fatal error C1083: Cannot open include file: 'config.h': No such file or d
irectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_config.c(45): fatal error C1083: Cannot open include file: 'config.h': No such file or direc
tory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
  pcre_globals.c
  pcre_jit_compile.c
  pcre_maketables.c
  pcre_newline.c
  pcre_ord2utf8.c
  pcre_refcount.c
  pcre_string_utils.c
  pcre_study.c
......\deps\libpcre\pcre_string_utils.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or
 directory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_study.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or direct
ory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_refcount.c(48): fatal error C1083: Cannot open include file: 'config.h': No such file or dir
ectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_jit_compile.c(44): fatal error C1083: Cannot open include file: 'config.h': No such file or
directory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
  pcre_tables.c
  pcre_ucd.c
  pcre_valid_utf8.c
  pcre_version.c
......\deps\libpcre\pcre_ord2utf8.c(45): fatal error C1083: Cannot open include file: 'config.h': No such file or dir
ectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_globals.c(56): fatal error C1083: Cannot open include file: 'config.h': No such file or dire
ctory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_maketables.c(49): fatal error C1083: Cannot open include file: 'config.h': No such file or d
irectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
  pcre_xclass.c
  win_delay_load_hook.c
......\deps\libpcre\pcre_newline.c(51): fatal error C1083: Cannot open include file: 'config.h': No such file or dire
ctory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_tables.c(49): fatal error C1083: Cannot open include file: 'config.h': No such file or direc
tory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_version.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or dire
ctory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_xclass.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or direc
tory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_valid_utf8.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or d
irectory [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
......\deps\libpcre\pcre_ucd.c(14): fatal error C1083: Cannot open include file: 'config.h': No such file or director
y [\node_modules\cytubefilters\build\deps\libpcre\libpcre.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\veste\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14271
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\veste\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd \node_modules\cytubefilters
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
CyTube@3.14.3 
+-- babel@5.8.35
| +-- babel-core@5.8.35
| | +-- babel-plugin-constant-folding@1.0.1
| | +-- babel-plugin-dead-code-elimination@1.0.2
| | +-- babel-plugin-eval@1.0.1
| | +-- babel-plugin-inline-environment-variables@1.0.1
| | +-- babel-plugin-jscript@1.0.4
| | +-- babel-plugin-member-expression-literals@1.0.1
| | +-- babel-plugin-property-literals@1.0.1
| | +-- babel-plugin-proto-to-assign@1.0.4
| | +-- babel-plugin-react-constant-elements@1.0.3
| | +-- babel-plugin-react-display-name@1.0.3
| | +-- babel-plugin-remove-console@1.0.1
| | +-- babel-plugin-remove-debugger@1.0.1
| | +-- babel-plugin-runtime@1.0.7
| | +-- babel-plugin-undeclared-variables-check@1.0.2
| | | `-- leven@1.0.2
| | +-- babel-plugin-undefined-to-void@1.1.6
| | +-- babylon@5.8.35
| | +-- chalk@1.1.1
| | | +-- ansi-styles@2.2.0
| | | |`-- color-convert@1.0.0
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | | `-- ansi-regex@2.0.0
| | | +-- strip-ansi@3.0.1
| | |`-- supports-color@2.0.0
| | +-- core-js@1.2.6
| | +-- detect-indent@3.0.1
| | | +-- get-stdin@4.0.1
| | | `-- minimist@1.2.0
| | +-- esutils@2.0.2
| | +-- globals@6.4.1
| | +-- home-or-tmp@1.0.0
| | | +-- os-tmpdir@1.0.1
| | |`-- user-home@1.1.1
| | +-- is-integer@1.0.6
| | | `-- is-finite@1.0.1
| | |`-- number-is-nan@1.0.0
| | +-- js-tokens@1.0.1
| | +-- json5@0.4.0
| | +-- line-numbers@0.2.0
| | | `-- left-pad@0.0.3
| | +-- minimatch@2.0.10
| | |`-- brace-expansion@1.1.3
| | |   +-- balanced-match@0.3.0
| | |   `-- concat-map@0.0.1
| | +-- private@0.1.6
| | +-- regenerator@0.8.40
| | | +-- commoner@0.10.4
| | | |`-- detective@4.3.1
| | | |   `-- defined@1.0.0
| | | +-- defs@1.1.1
| | | | +-- alter@0.2.0
| | | | |`-- stable@0.1.5
| | | | +-- ast-traverse@0.1.1
| | | | +-- breakable@1.0.0
| | | | +-- simple-fmt@0.1.0
| | | | +-- simple-is@0.2.0
| | | | +-- stringmap@0.2.2
| | | | +-- stringset@0.2.1
| | | | +-- tryor@0.1.2
| | | | `-- yargs@3.27.0
| | | |   +-- os-locale@1.4.0
| | | |   |`-- lcid@1.0.0
| | | |   |   `-- invert-kv@1.0.0
| | | |   +-- window-size@0.1.4
| | | |`-- y18n@3.2.0
| | | +-- esprima-fb@15001.1001.0-dev-harmony-fb
| | | +-- recast@0.10.33
| | | | `-- ast-types@0.8.12
| | |`-- through@2.3.8
| | +-- regexpu@1.3.0
| | | +-- esprima@2.7.2
| | | +-- regenerate@1.2.1
| | | +-- regjsgen@0.2.0
| | | `-- regjsparser@0.1.5
| | |`-- jsesc@0.5.0
| | +-- repeating@1.1.3
| | +-- resolve@1.1.7
| | +-- shebang-regex@1.0.0
| | +-- source-map-support@0.2.10
| | | `-- source-map@0.1.32
| | +-- to-fast-properties@1.0.1
| | +-- trim-right@1.0.1
| |`-- try-resolve@1.0.1
| +-- chokidar@1.4.3
| | +-- anymatch@1.3.0
| | | +-- arrify@1.0.1
| | | `-- micromatch@2.3.7
| | |   +-- arr-diff@2.0.0
| | |   |`-- arr-flatten@1.0.1
| | |   +-- array-unique@0.2.1
| | |   +-- braces@1.8.3
| | |   | +-- expand-range@1.8.1
| | |   | | `-- fill-range@2.2.3
| | |   | |   +-- is-number@2.1.0
| | |   | |   +-- isobject@2.0.0
| | |   | |`-- randomatic@1.1.5
| | |   | +-- preserve@0.2.0
| | |   | `-- repeat-element@1.1.2
| | |   +-- expand-brackets@0.1.4
| | |   +-- extglob@0.3.2
| | |   +-- filename-regex@2.0.0
| | |   +-- kind-of@3.0.2
| | |   |`-- is-buffer@1.1.2
| | |   +-- normalize-path@2.0.1
| | |   +-- object.omit@2.0.0
| | |   | +-- for-own@0.1.3
| | |   | | `-- for-in@0.1.4
| | |   |`-- is-extendable@0.1.1
| | |   +-- parse-glob@3.0.4
| | |   | +-- glob-base@0.3.0
| | |   | `-- is-dotfile@1.0.2
| | |`-- regex-cache@0.4.2
| | |     +-- is-equal-shallow@0.1.3
| | |     `-- is-primitive@2.0.0
| | +-- async-each@1.0.0
| | +-- glob-parent@2.0.0
| | +-- is-binary-path@1.0.1
| | |`-- binary-extensions@1.4.0
| | +-- is-glob@2.0.1
| | | `-- is-extglob@1.0.0
| |`-- readdirp@2.0.0
| |   `-- readable-stream@2.0.5
| |     +-- process-nextick-args@1.0.6
| |`-- util-deprecate@1.0.2
| +-- commander@2.9.0
| | `-- graceful-readlink@1.0.1
| +-- convert-source-map@1.2.0
| +-- fs-readdir-recursive@0.1.2
| +-- glob@5.0.15
| | +-- inflight@1.0.4
| | |`-- wrappy@1.0.1
| | `-- once@1.3.3
| +-- lodash@3.10.1
| +-- output-file-sync@1.1.1
| |`-- xtend@4.0.1
| +-- path-exists@1.0.0
| +-- path-is-absolute@1.0.0
| +-- slash@1.0.0
| `-- source-map@0.5.3
+-- bcrypt@0.8.5
| +-- bindings@1.2.1
|`-- nan@2.0.5
+-- bluebird@2.10.2
+-- body-parser@1.15.0
| +-- bytes@2.2.0
| +-- content-type@1.0.1
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- depd@1.1.0
| +-- iconv-lite@0.4.13
| +-- on-finished@2.3.0
| |`-- ee-first@1.1.1
| +-- qs@6.1.0
| +-- raw-body@2.1.5
| | `-- unpipe@1.0.0
|`-- type-is@1.6.12
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.10
+-- cheerio@0.19.0
| +-- css-select@1.0.0
| | +-- boolbase@1.0.0
| | +-- css-what@1.0.0
| | +-- domutils@1.4.3
| |`-- nth-check@1.0.1
| +-- dom-serializer@0.1.0
| | `-- domelementtype@1.1.3
| +-- entities@1.1.1
|`-- htmlparser2@3.8.3
|   +-- domelementtype@1.3.0
|   +-- domhandler@2.3.0
|   +-- domutils@1.5.1
|   +-- entities@1.0.0
|   `-- readable-stream@1.1.13
+-- clone@1.0.2
+-- coffee-script@1.10.0
+-- compression@1.6.1
| +-- accepts@1.3.1
| |`-- negotiator@0.6.0
| +-- compressible@2.0.7
| | `-- mime-db@1.22.0
| +-- on-headers@1.0.1
|`-- vary@1.1.0
+-- cookie-parser@1.4.1
| +-- cookie@0.2.3
| `-- cookie-signature@1.0.6
+-- create-error@0.3.1
+-- csrf@3.0.1
| +-- base64-url@1.2.1
| +-- rndm@1.2.0
| +-- scmp@1.0.0
|`-- uid-safe@2.1.0
|   `-- random-bytes@1.0.0
+-- cytube-mediaquery@0.0.2  (git://github.com/CyTube/mediaquery.git#d38c2372f17ba944a15d6aa15a3b3f54d5dc1a29)
|`-- domutils@1.5.1
+-- express@4.13.4
| +-- accepts@1.2.13
| | `-- negotiator@0.5.3
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.1
| +-- cookie@0.1.5
| +-- escape-html@1.0.3
| +-- etag@1.7.0
| +-- finalhandler@0.4.1
| +-- fresh@0.3.0
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- parseurl@1.3.1
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@1.0.10
| | +-- forwarded@0.1.0
| |`-- ipaddr.js@1.0.5
| +-- qs@4.0.0
| +-- range-parser@1.0.3
| +-- send@0.13.1
| | +-- destroy@1.0.4
| | +-- http-errors@1.3.1
| | `-- mime@1.3.4
| +-- utils-merge@1.0.0
|`-- vary@1.0.1
+-- express-minify@0.1.7
| +-- cssmin@0.4.3
| `-- uglify-js@2.6.2
|   +-- async@0.2.10
|   +-- uglify-to-browserify@1.0.2
|`-- yargs@3.10.0
|     +-- camelcase@1.2.1
|     +-- cliui@2.1.0
|     | +-- center-align@0.1.3
|     | | +-- align-text@0.1.4
|     | | | +-- longest@1.0.1
|     | | | `-- repeat-string@1.5.4
|     | |`-- lazy-cache@1.0.3
|     | +-- right-align@0.1.3
|     | `-- wordwrap@0.0.2
|     +-- decamelize@1.1.2
|`-- window-size@0.1.0
+-- graceful-fs@4.1.3
+-- http-errors@1.4.0
| +-- inherits@2.0.1
| `-- statuses@1.2.1
+-- jade@1.11.0
| +-- character-parser@1.2.1
| +-- clean-css@3.4.10
| | +-- commander@2.8.1
| |`-- source-map@0.4.4
| +-- commander@2.6.0
| +-- constantinople@3.0.2
| | `-- acorn@2.7.0
| +-- jstransformer@0.0.2
| | +-- is-promise@2.1.0
| |`-- promise@6.1.0
| |   `-- asap@1.0.0
| +-- mkdirp@0.5.1
| |`-- minimist@0.0.8
| +-- transformers@2.1.0
| | +-- css@1.0.8
| | | +-- css-parse@1.0.4
| | | `-- css-stringify@1.0.5
| | +-- promise@2.0.0
| | |`-- is-promise@1.0.1
| | `-- uglify-js@2.2.5
| |   +-- optimist@0.3.7
| |`-- source-map@0.1.43
| +-- void-elements@2.0.1
| `-- with@4.0.3
|   +-- acorn@1.2.2
|`-- acorn-globals@1.0.9
|     `-- acorn@2.7.0
+-- json-typecheck@0.1.3
+-- morgan@1.7.0
|`-- basic-auth@1.0.3
+-- mysql@2.10.2
| +-- bignumber.js@2.1.4
| `-- readable-stream@1.1.13
|   +-- core-util-is@1.0.2
|   +-- isarray@0.0.1
|`-- string_decoder@0.10.31
+-- nodemailer@1.11.0
| +-- libmime@1.2.0
| | +-- libbase64@0.1.0
| | `-- libqp@1.1.0
| +-- mailcomposer@2.1.0
| |`-- buildmail@2.0.0
| |   +-- addressparser@0.3.2
| |   `-- needle@0.10.0
| +-- needle@0.11.0
| +-- nodemailer-direct-transport@1.1.0
| |`-- smtp-connection@1.3.8
| `-- nodemailer-smtp-transport@1.1.0
|`-- nodemailer-wellknown@0.1.7
+-- oauth@0.9.14
+-- q@1.4.1
+-- redis@2.4.2
| +-- double-ended-queue@2.1.0-0
| `-- redis-commands@1.1.0
+-- sanitize-html@1.5.0  (git://github.com/calzoneman/sanitize-html.git#9bfd47720b974d266559cdfccf0fd3418d301efd)
| +-- he@0.4.1
| +-- htmlparser2@3.7.3
| | +-- domhandler@2.2.1
| | +-- domutils@1.5.1
| | +-- entities@1.0.0
| |`-- readable-stream@1.1.13
| +-- lodash@2.4.2
| `-- regexp-quote@0.0.0
+-- serve-static@1.10.2
+-- socket.io@1.4.5
| +-- engine.io@1.6.8
| | +-- accepts@1.1.4
| | | +-- mime-types@2.0.14
| | | |`-- mime-db@1.12.0
| | | `-- negotiator@0.4.9
| | +-- base64id@0.1.0
| | +-- engine.io-parser@1.2.4
| | | +-- after@0.8.1
| | | +-- arraybuffer.slice@0.0.6
| | | +-- base64-arraybuffer@0.1.2
| | | +-- blob@0.0.4
| | | +-- has-binary@0.1.6
| | |`-- utf8@2.1.0
| | `-- ws@1.0.1
| |   +-- options@0.0.6
| |`-- ultron@1.0.2
| +-- has-binary@0.1.7
| +-- socket.io-adapter@0.4.0
| | `-- socket.io-parser@2.2.2
| |   +-- debug@0.7.4
| |`-- json3@3.2.6
| +-- socket.io-client@1.4.5
| | +-- backo2@1.0.2
| | +-- component-bind@1.0.0
| | +-- component-emitter@1.2.0
| | +-- engine.io-client@1.6.8
| | | +-- component-inherit@0.0.3
| | | +-- has-cors@1.1.0
| | | +-- parsejson@0.0.1
| | | +-- parseqs@0.0.2
| | | +-- xmlhttprequest-ssl@1.5.1
| | | `-- yeast@0.1.2
| | +-- indexof@0.0.1
| | +-- object-component@0.0.3
| | +-- parseuri@0.0.4
| | |`-- better-assert@1.0.2
| | |   `-- callsite@1.0.0
| |`-- to-array@0.1.4
| `-- socket.io-parser@2.2.6
|   +-- benchmark@1.0.0
|   +-- component-emitter@1.1.2
|`-- json3@3.3.2
+-- socket.io-redis@1.0.0
| +-- async@0.9.0
| +-- msgpack-js@0.3.0
| | `-- bops@0.0.7
| |   +-- base64-js@0.0.2
| |`-- to-utf8@0.0.1
| +-- redis@2.3.0
| `-- uid2@0.0.3
+-- source-map-support@0.4.0
|`-- source-map@0.1.32
|   `-- amdefine@1.0.0
+-- status-message-polyfill@1.0.1  (git://github.com/calzoneman/status-message-polyfill.git#03296c0ff5c5e94981346537d63883316e708e95)
+-- uuid@2.0.1
`-- yamljs@0.1.6
  +-- argparse@0.1.16
  | +-- underscore@1.7.0
  | `-- underscore.string@2.4.0
`-- glob@3.1.21
    +-- graceful-fs@1.2.3
    +-- inherits@1.0.2
    `-- minimatch@0.2.14
      +-- lru-cache@2.7.3
`-- sigmund@1.0.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Windows_NT 10.0.14271
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\veste\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE

npm ERR! cytubefilters@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cytubefilters@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cytubefilters package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cytubefilters
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cytubefilters
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \npm-debug.log

**Comment by calzoneman** [comment]
It looks like you're using windows. Some C++ modules this depends on (bcrypt, cytubefilters) may not compile on windows and furthermore I don't support it so you're on your own.

CyTube is only supported on Linux (preferred), OS X, and FreeBSD.

Calvin
