### ISSUE TITLE
Vid.me Support?

### ISSUE THREAD

**Issue by bgiesing** [calzoneman/sync#568]
Do you think [Vid.me](https://vid.me) support is possible to be added?

**Comment by calzoneman** [comment]
So you can already add the direct links to the videos by using the JS console on their website:

``` javascript
console.log(document.querySelector("source[type='video/mp4']").src)
```

And then plugging the resulting link into CyTube.  But I took a glance at their metadata API and it looks like it would work for native support, I'd just need to be convinced that it's worth doing.

**Comment by bgiesing** [comment]
Well a lot of people are using them as a censor free  alternative with the whole #WTFU DMCA and other YouTube issues. 

Plus they allow anonymous uploads with no account so it could be a good alternative in addition to Google  Drive/Photos support for uploads that aren't super public and people who don't like Google.

**Comment by calzoneman** [comment]
Their API looks pretty simple, I'll take a look at it.

**Comment by calzoneman** [comment]
You can try this out on http://beta.synchtube.me

**Comment by bgiesing** [comment]
I just tried it in two separate windows and it works. (I'm guessing it being off by a few seconds is expected since I'm running two on the same computer?)

**Comment by calzoneman** [comment]
it shouldn't behave any different from any other video type in terms of synchronization

**Comment by Xaekai** [comment]
I left a cheeky message on your commit regarding this. :shipit:

**Comment by calzoneman** [comment]
I intentionally left this open for visibility until the change makes it out to live.

**Comment by calzoneman** [comment]
This is live now.
