### ISSUE TITLE
Log filter interprets any word within square brackets from the chat as a filter

### ISSUE THREAD

**Issue by codl** [calzoneman/sync#573]
## Website Problem

**Please confirm whether you've tried the following debugging steps:**
- [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
- [x] Disabling all browser extensions
- [x] Using a clean channel with no customizations
### Description of the Problem
- What triggers the problem?

Going to the channel log after an user has typed a word within square brackets in the chat
- What happens?

A new log filter is created, or the message appears in the corresponding filter if it already existed

![824c9b05-1c68-4835-9b2c-412956f1df4f](https://cloud.githubusercontent.com/assets/315139/15419139/531d2c62-1e64-11e6-8474-94d37b8dbfb3.png)
![b584976c-cfe9-4e45-92e9-88170d52a300](https://cloud.githubusercontent.com/assets/315139/15419125/43c31fb0-1e64-11e6-8a05-2041931d8d30.png)
- What do you expect to happen instead?

The message only appears in the "chat" filter.
### System Information
- **Operating System (Windows / Mac / Linux / Android / iOS):** Linux
- **Web Browser (Firefox / Chrome / Other):** Chrome 50.0.2661.102
- **Error Messages Displayed:** None
- **Screenshot of JavaScript Console:**
  ![a697690d-f0b2-4a09-8aac-004da78ef500](https://cloud.githubusercontent.com/assets/315139/15419040/adbee436-1e63-11e6-9ab5-6282b742a7a1.png)

**Comment by calzoneman** [comment]
The fix for this has been deployed to http://beta.synchtube.me.  It'll be included in the next update to cytu.be.
