### ISSUE TITLE
BEAM.PRO support?

### ISSUE THREAD

**Issue by cyb3rm4n** [calzoneman/sync#576]
I think you need the full support of beam.pro site - it's new streaming platform with interactive apps just-in-browser.

**Comment by Xaekai** [comment]
Leaving this here for convenience:
https://dev.beam.pro/rest.html#channels__channel__manifest__type__get

**Comment by calzoneman** [comment]
I mean adding the video is easy enough, but I don't know what to do about the controls.  Would that even be useful to have on CyTube?  Where would you put it?

It's kind of a weird concept, seems like it's trying to cash in on the "Twitch plays" craze.
