### ISSUE TITLE
KissCartoon videos on CyTu.be?

### ISSUE THREAD

**Issue by Allanbuzzy** [calzoneman/sync#577]
How do I implement KC videos on my CyTube channel? You see, I want to create my own cartoon channel using videos from KissCartoon. How do I add KC videos to my channel?

**Comment by calzoneman** [comment]
As discussed on IRC today, Kisscartoon/Kissanime are not currently supported.  Refer to [the FAQ](https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#which-media-providers-are-supported) for a list of websites which are supported.

Whether or not it can be supported in the future is being evaluated, but there are no promises at this time.
