### ISSUE TITLE
Coloring of nicks in chat window

### ISSUE THREAD

**Issue by atomiswave** [calzoneman/sync#58]
Requesting coloring of nicks _in the window of the active chat_, according to the user rank, just like on the list. This would add some clarity.

**Comment by calzoneman** [comment]
Moderators and above can currently show their nick color with the `/m` command:

`/m message`

I plan to add a user options menu with a checkbox option for this to automatically be applied.  The reason it isn't by default is a matter of preference.

**Comment by calzoneman** [comment]
As of https://github.com/calzoneman/sync/commit/8d6b228f8fdc858beefb26d50923c0377da57d8c, you can check the "Modflair" box to have your name colored by default.

**Comment by ghost** [comment]
Great, it's now possible to use > quote with modflair.

**Comment by calzoneman** [comment]
Yes, `/m` should chain with greentext and `/d`
