### ISSUE TITLE
Did you add Facebook Vidéo in synchronized support

### ISSUE THREAD

**Issue by Taromis** [calzoneman/sync#581]
Hello dear developper.

I would like to know if you planning to add Facebook vidéo at the synchronized source that Cytube can use. Because he add seek option in her API since little bit time so maybe it's possible.

It's would be great.

If not, can you tell me the name of files that i need to looking for and change if i would ask someone to add this feature.

Thank's for you're wonderful Cytube, it's working fuc**ing great.

**Comment by Taromis** [comment]
Up please :)

**Comment by Xaekai** [comment]
Dropping this here for convenience.
https://developers.facebook.com/docs/graph-api/reference/video

**Comment by Taromis** [comment]
Thank's for link :)

I understand that i have no answer. But please at least can you tell me which file i need to looking for, if i want to make this myself... 

it would give me a time saving.

Thank's sir

**Comment by salientnet** [comment]
Hello Dear

I am going to add support for facebook video too.
So please help me with any suggestions or others.
Looking forward to hearing from you.

Regards

**Comment by Taromis** [comment]
Hello salientroot 

Maybe we can take a look together ?

Because if we wait official answer, i think we will wait long time...

I have some friends that are looking for to do this so maybe at many it's best than alone ?

**Comment by calzoneman** [comment]
Copying from IRC

```
[22:21:06] <calzoneman> here are the commits I made to support vid.me: https://github.com/CyTube/mediaquery/pull/4 https://github.com/calzoneman/sync/pull/582 that's the most help I can provide right now, I know nothing about facebook's API and looking into it is pretty far in my backlog
```

**Comment by Xaekai** [comment]
Having reviewed Facebook's API docs a bit more, I believe this may be impossible to implement. Apparently Facebook does not allow you to make permanent API keys for server side usage. Their "long lived" "access tokens" only live for 2 months.

**Comment by Taromis** [comment]
Hello 

Thank's for you're answer guys, it's very cool to take time.

I have understand the link given by clazoneman and the part from Xaekai.

But i would like to know if the sudden change the API key every 2 months when it expires, is complicated? Because if it is not really possible because the API key expires every two months may be is not binding if it update each time ?

Thank you for your help anyway.
