### ISSUE TITLE
Weird footer position

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#59]
![footer](https://f.cloud.github.com/assets/3297156/435133/00954592-afa4-11e2-82f2-6db3806cb619.PNG)
Even with the latest commit.

**Comment by calzoneman** [comment]
Which browser are you using?  I am not having this issue on Firefox 20.

**Comment by ghost** [comment]
Chrome 26.0.1410.64

**Comment by calzoneman** [comment]
Confirmed in chromium.  I'll look into it.

On a side note, CSS is terrible.

**Comment by calzoneman** [comment]
Also note to self change footer color in dark theme CSS

**Comment by ghost** [comment]
#footer, .push {
 margin: 90px 0 0 0;
}
in ytsync.css works fine.
