### ISSUE TITLE
Disable sound when somebody joins a room (mainly guests)

### ISSUE THREAD

**Issue by brace110** [calzoneman/sync#595]
Can't seem to turn off the sound when a guests joins. Any channel options you can give me? I'm happy to code along with you if you need my help. I already got a script running for loads of other things in my room.

**Comment by calzoneman** [comment]
I'm not sure what you mean, CyTube does not play any sounds when users join.

**Comment by brace110** [comment]
I'll get back with a proper example, it might just be some code somebody else inserted. We work together on a script.

**Comment by calzoneman** [comment]
I don't provide official support for any user-maintained scripts.  Closing this issue for now.  If the issue occurs on an unmodified channel with no scripts running, then feel free to reopen it.
