### ISSUE TITLE
"TypeError: Cannot read property 'globalRank' of undefined" In Log

### ISSUE THREAD

**Issue by Rikudouu** [calzoneman/sync#600]
## Server Problem

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**
- [Done] Run `npm run build-server` to regenerate `lib/` from `src/`
- [Done] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
- [Done] Restarted the server
### Description of the Problem
- What triggers the problem?
  Changing channel settings.
- What happens?
  Nothing saves from channel settings. I try to make my channel public, but it doesn't go public. I try to type in chat but it doesn't let me (red circle with line though pops up instead). I try to browse for a youtube video but it tells me, the administrator with 255 rank, that I don't have permission to browse this channel's library, even though I made the channel.
### System Information
- **Operating System:** Ubuntu Gnome 15.04 64-bit
- **Node Version:** _(run `node -v`)_ v0.10.25
- **CyTube Version:** _(displayed at startup)_ v3.18.6
- **Error Messages Displayed:**
  `[Wed Jul 13 2016 20:30:51] TypeError: Cannot read property 'globalRank' of undefined
  at EventEmitter.<anonymous> (/home/sinusbot/sync/src/user.js:112:20)
  at EventEmitter.emit (events.js:95:17)
  at /home/sinusbot/sync/src/io/ioserver.js:232:18
  at process._tickDomainCallback (node.js:459:13)`

**Comment by ghost** [comment]
Upgrade your node. 0.10 no longer works. I had the same issue last week.

**Comment by calzoneman** [comment]
To add to what bush said, I only test the service on v4.x (LTS), and v6.x (current stable).  v0.12.x and v0.10.x may or may not work, I don't test them (evidently, 0.10.x doesn't work).

**Comment by Rikudouu** [comment]
Oh. Sorry, I'm very new to Linux and don't really understand it much, I've just been following the commands on installation tutorials. I guess it defaulted to an older version. I'll try updating.

Also, why doesn't the npm install work with a newer version of node? I was having difficulties because npm kept saying I had a legacy version of node, so then I did sudo apt-get install nodejs-legacy and it worked. :/

Very confused haha

**Comment by ghost** [comment]
You need to delete the node modules folder after upgrading node

**Comment by calzoneman** [comment]
What bush said.  `npm` is pretty fragile, you need to start from scratch by deleting `node_modules` or else it will get confused.

I recommend you install nodejs from nodesource: https://nodejs.org/en/download/package-manager/

**Comment by Rikudouu** [comment]
Now it works, thanks so much guys. I was getting a headache trying to solve it myself for these past 2 hours x.x

If anyone else has this problem: http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by calzoneman** [comment]
The installation wiki should probably be updated to reflect this.  Currently it recommends newer versions but does not explicitly say that v0.10 doesn't work.
