### ISSUE TITLE
Site annoucement deletion isn't synced across nodes

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#601]
- What triggers the problem?
  Creating a site announcement then deleting it.
- What happens?
  It gets deleted on the node of the ACP you're visiting but not on the others
- What do you expect to happen instead?
  The announcement deletion is broadcast to all nodes.

**Comment by calzoneman** [comment]
Yep this has been on my todo list, I'll pick it up now because I know the reason.
