### ISSUE TITLE
Escaping markdown.

### ISSUE THREAD

**Issue by dude22072** [calzoneman/sync#605]
In chat you should be able to escape the asterisks (aka putting a \ before them) so that it displays the asterisks instead of formatting the text.

i.e. displaying *punches wall* instead of _punches wall_.

**Comment by calzoneman** [comment]
This is actually a chat filter that is added by default to new channels.  If you prefer a different behavior, you can change or remove the filter from Channel Settings->Edit->Chat Filters.

**Comment by Xaekai** [comment]
It should also be noted that your example usage has it's own dedicated command

e.g `/me punches wall`
