### ISSUE TITLE
Supported Hosts

### ISSUE THREAD

**Issue by evrx** [calzoneman/sync#607]
Would it be possible to add support for files from
mp4upload.com and yourupload.com

**Comment by Xaekai** [comment]
http://www.mp4upload.com/faq.html
`No. Hotlinking is not allowed on any kind of files uploaded to our servers.`

As for http://www.yourupload.com/, the site seems barely functional. The only link on the bottom that even works is the blog.

So no. On both counts. It the future you can pretty much answer this question (Can this provider be added to CyTube?) yourself by looking for "developer docs" or references to something called an "API" in their FAQ/Help pages. If you see nothing like that, the answer is probably no.
