### ISSUE TITLE
RTMP with HTML5 player?

### ISSUE THREAD

**Issue by jarrpa** [calzoneman/sync#612]
## Server Problem

**Please confirm whether you've tried the following debugging steps:**
- [x] Run `npm run build-server` to regenerate `lib/` from `src/`
- [x] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
- [x] Restarted the server
### Description of the Problem

Browsing to my CyTube installation on a browser that doesn't support flash doesn't allow me to view RTMP streams playing in a channel. If I switch to playing a raw mp4 file it works. I imagine it should be possible to allow non-Flash browsers to view RTMP streams, given that youtube and twitch do it?
### System Information
- **Operating System:** Ubuntu 14.04
- **Node Version:** v6.2.2
- **CyTube Version:** v3.18.7
- **Error Messages Displayed:** On affected browser: "No compatible source was found for this video."

**Comment by calzoneman** [comment]
It's not possible to play RTMP with HTML5.  Websites that support HTML5 streaming are actually using a separate HLS stream, another streaming technology that can be played with HTML5.

I plan to support HLS at some point, however you would need to have an HLS source to take advantage of it; it wouldn't allow you to play existing RTMP streams with HTML5.

**Comment by jarrpa** [comment]
Gotcha. Thanks!
