### ISSUE TITLE
Embed player and playlist only

### ISSUE THREAD

**Issue by Taromis** [calzoneman/sync#617]
Hello to you it's me again.

Sorry for the inconvenience again but I have a question please.

Here I would like integrated on one page, only the third player and the playlist like the picture below (and let the copyright off course. )

https://s14.postimg.org/dvs07qni9/embede.png

Is this possible? Because I am having great difficulty in changing the whole aspect.

Would you have already some that the required code available for embed this type?

Or do you have a little help to make this possible please.

Thanks again.

**Comment by Xaekai** [comment]
The amount of work to strip down CyTube for this purpose is excessive, and I would have to question why you would ever bother rather than just writing a playlist app for VideoJS instead.

If you wanted to pull this off with simple hacks you could remove the chatwrap from the channel template.

**Comment by Taromis** [comment]
Thank's for quiclky answer.

It's because i already have a chat, and don't need a new one. But cytube it's perfect for all the option that he have.

i will test that you have tell me :)

Thank's alot because at this moment i try out in CSS and it's not bad but lost responsive for example. :)

**Comment by calzoneman** [comment]
For future reference, I am planning to split out some of the playlist timer logic into a separate module and the player itself is already pretty modular, so in the future it might be feasible to construct something simple out of the individual pieces.

But yeah, as Xaekai mentioned it would be more of a pain than it's worth to remove all the pieces you don't want from the backend, so you'd be better off just deleting the HTML for the parts you don't need and disabling the handlers for them on the backend (for example, by setting the permissions such that no one can use chat through other means).
