### ISSUE TITLE
Failed to require() lib/server.js

### ISSUE THREAD

**Issue by rh0die** [calzoneman/sync#621]
## Server Problem
- [x] Run `npm run build-server` to regenerate `lib/` from `src/`
- [x] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
- [ ] Restarted the server [can't start server!]
### Description of the Problem
- What triggers the problem?

Attempting to execute 'node index.js' to launch results in the error below.
- What happens?

Error messages; see below.
- What do you expect to happen instead?

Launch!
### System Information
- **Operating System:** Debian 8.5 x64
- **Node Version:** v4.5.0
- **CyTube Version:** the latest from git
- **Error Messages Displayed:**

```
FATAL: Failed to require() lib/server.js
Possible causes:
  * You haven't run `npm run build-server` to regenerate the runtime
  * You've upgraded node/npm and haven't rebuilt dependencies (try `npm rebuild` or `rm -rf node_modules && npm install`)
  * A dependency failed to install correctly (check the output of `npm install` next time)
Error: Cannot find module 'cytube-common/lib/metrics/metrics'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dan/sync/lib/database.js:5:38)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dan/sync/lib/channel-storage/dbstore.js:19:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

Also when I attempt to run 'npm rebuild' I get

```

Failed at the cytube-common@0.0.1 postinstall script 'babel -D --source-maps --out-dir lib/ src/'.
babel -D --source-maps --out-dir lib/ src/

```

Thanks for your help, I'm looking forward to getting started with CyTube!

**Comment by calzoneman** [comment]
`npm` is reporting that it failed, but I don't see the context.  Can you please record the full output using the following command, and then paste the log file into http://cryto.net/why-is-npm-broken/, and if that doesn't help diagnose it, you can attach it here?

```
rm -rf node_modules
npm install |& tee output.log
```

**Comment by calzoneman** [comment]
How much memory does your server have?

**Comment by rh0die** [comment]
http://cryto.net/why-is-npm-broken/ couldn't find the problem; I tried copying the full output from the command line and that didn't work either. I've attached the file.

> How much memory does your server have?
> 512MB

Thanks for your help!
[output.log.zip](https://github.com/calzoneman/sync/files/453583/output.log.zip)

**Comment by calzoneman** [comment]
I updated the wiki with some information about low memory systems:

https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#npm-performance

**Comment by rh0die** [comment]
Thanks cm!

pnpm started off promisingly but didn't work either. However your npmhax.sh script did! I got the server up and running on port 8080 but now I'm getting a 404 error that 'myurl:8080/js/jquery.js' is missing, which returns:
`Your browser attempted to submit form data to /register with an invalid authentication token.`

I searched through sync's issues history and found https://github.com/calzoneman/sync/issues/505, so I tried setting up my config.yaml properly and reinstalling jquery, but no luck.

I get the homepage an /register, but anything else 404's on me.

**Comment by rh0die** [comment]
It's working now; thanks!

**Comment by calzoneman** [comment]
What was the issue, so that future people searching and finding this issue will know how to solve it?

**Comment by rh0die** [comment]
I was mistaken, npmhax.sh worked perfectly. I'm working in a live environment and forgot to update my MX records; when I got up today they had updated and it worked just fine.
