### ISSUE TITLE
[Tracking] Investigate trimming the dependency tree

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#622]
The CyTube dependency tree has become quite large (the main culprit being subdependencies of certain modules), which results in `npm` using 10 times as much memory as the actual service requires to run just to install the dependencies.  This in turn has resulted in a number of emails/IRC contacts from confused people trying to figure out why `npm install` is failing (the error messages are not very clear).

Need to investigate:
- Which modules are bringing in the most dependencies
- Can we reduce this by upgrading or deduping somehow

**Comment by calzoneman** [comment]
```
./cytube-common 324
./babel 174
./pug 58
./socket.io 47
./express 42
./express-minify 21
./cheerio 20
./body-parser 20
./serve-static 19
./cytube-mediaquery 19
./socket.io-redis 18
./sanitize-html 17
./nodemailer 17
./compression 11
./yamljs 10
./mysql 8
./morgan 8
./csrf 6
./redis 4
./http-errors 4
./bcrypt 4
./source-map-support 3
./cytubefilters 3
./cookie-parser 3
./uuid 2
./status-message-polyfill 1
./q 1
./oauth 1
./lodash 1
./json-typecheck 1
./graceful-fs 1
./create-error 1
./coffee-script 1
./clone 1
./bluebird 1
```

**Comment by calzoneman** [comment]
And for `cytube-common`:

```
./babel-cli 218
./babel-preset-es2015 96
./babel-core 56
./knex 50
./mocha 19
./bookshelf 16
./winston 10
./mysql 8
./redis 4
./babel-plugin-transform-es2015-for-of 4
./babel-plugin-transform-es2015-destructuring 4
./JSONStream 3
./uid2 1
./toml 1
./lodash 1
./clone 1
./bluebird 1
```

218 submodules seems a little excessive for `babel-cli`.

**Comment by calzoneman** [comment]
Actually I realized that the way I'm calculating this is inaccurate.

**Comment by calzoneman** [comment]
Since CyTube only supports node.js v4.x+ anyways, it's probably worth checking on which ES2015 features are supported by 4.x and which are used in CyTube to minimize how much has to be transpiled.

**Comment by calzoneman** [comment]
Looks like getting rid of `babel-cli` from `cytube-common` and replacing it with a simple script for postinstall would save over 100 modules...

also should probably upgrade CyTube itself to babel 6 at some point

**Comment by Xaekai** [comment]
Is that all babel-cli was being required for? The post install?

**Comment by calzoneman** [comment]
Well, I use it locally for development (with the "watch filesystem and recompile" flag).  The main CyTube repo uses babel 5, where the cli is built in.  For babel 6, I made the false assumption that the cli package would just be a simple wrapper around the JS API, but it seems instead it has over 100 dependencies in the tree.

So it's probably better to just write a 10 line node script to call the API and compile on installation and require developers to manually install the cli on their machine if they want it.
