### ISSUE TITLE
Fucking 'www'

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#626]
I have determined that some of the users who've reported that the Google Drive userscript is non functional are experiencing this issue because they are connected to http://www.cytu.be/ not http://cytu.be/

I suggest the following remedy:
1. One normal include, this will give the userscript it's pretty favicon in the userscript manager dashboard. 
   `@include http://maindomain.tld/`
2. A regex include to cover everything else. 
   `@include /https?://(?:www\.)?(?:maindomain.tld|altdomain1.tld|altdomain2.tld)//`

This is how I do my userscripts. If you use the regex alone the script doesn't get the pretty favicon in the dashboard and that simply will not do. Regex includes are supported by both Grease and Tamper. The possible only complication I see is deployments who solely use a subdomain like I do with PonkTube, but I think that's a relatively minor issue.

**Comment by calzoneman** [comment]
Added the includes for www: https://www.cytu.be/js/cytube-google-drive.user.js#bypass=true
