### ISSUE TITLE
Hitbox HTTPS

### ISSUE THREAD

**Issue by TheKanten** [calzoneman/sync#627]
Has there been any news in regards to Hitbox functionality? Responses from Hitbox support have told me that HTTPS should be functional on the site now but cytube still intercepts requests with the old error popup telling everyone in the channel to swap over to plain HTTP.

**Comment by ghost** [comment]
Their website redirects ssl traffic back to http.

**Comment by calzoneman** [comment]
The website itself redirects, however it appears that HTTPS embeds do in fact work, so I'll go ahead and patch this.

**Comment by calzoneman** [comment]
This is up on http://beta.synchtube.me, but that's not really useful because I haven't set up SSL on beta yet.  But this will be included in the next live release.

**Comment by calzoneman** [comment]
This is live now.
