### ISSUE TITLE
Audio (Icecast2) stream support

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#63]
Is it possible for you to implement audio (in my case Icecast2) stream as another media source? Our society (vichan.net and generally all polish imageboards) has an internet radio that is occasionally on air, and we use the IRC to provide radiochat, but it would be nice to have everything in one place. That's our point of view, but i'm sure other people would love to use that feature i.e. to listen podcasts or livestreams from important events. There are also UVB maniacs or guys that are into online radio scanners (such as myself, i'm often listening to services radio with some ambiet music).

Below is our stream, in case you need to test the feature; if there is no DJ present, the jazz loop is playing:
http://64.191.102.135:8000/rcp.ogg

**Comment by calzoneman** [comment]
This should be working now.  In the queue box, type

`jw:http://64.191.102.135:8000/rcp.ogg`

I tested it and it appeared to be working.  I generalized it to JWPlayer rather than Icecast, because JWPlayer supports multiple filetypes

**Comment by ghost** [comment]
Thanks!

**Comment by hjri** [comment]
no longer works, jwplayer has been removed and trying to directly link to icecast ogg stream gives this error message:
```
The request for the audio/video link was rejected as invalid.  Contact support for troubleshooting assistance.
```

**Comment by calzoneman** [comment]
Yeah, JW was removed a long time ago.  There is an open issue for shoutcast (which I think is internally effectively the same format, but I don't recall): https://github.com/calzoneman/sync/issues/785, but this has never been followed up on because in the past 4 years I guess nobody cared to ask about it.

Is icecast something that you use regularly?

**Comment by hjri** [comment]
sorta. It's not that big of a deal tho, but cytube could potentially make it a bit more accessible. It's just an vorbis (or mp3) stream as far as I understand, it works (sorta) when just opening it in browser.
