### ISSUE TITLE
Can't see Google Drive video on chrome, but on firefox I can.

### ISSUE THREAD

**Issue by LukteDukte** [calzoneman/sync#631]
I went to my own channel adding a .mkv Google Drive video. 
I got the error message "The Media could not be loaded, either because the server or network failed or because the format is not supported".

On chrome I have Tampermonkey installed with the script as suggested, using script version 1.2.0. 
It still get that error message.
I also did clearing cache & disabling all browser extensions [except Tampermonkey]. Still the same error.

I then tested it on Firefox. I was using Greasemonkey, script version 1.2.0 as well and the google drive video works completely fine. 

Going to add a picture of the console (chrome) when the error occurred. 

![chrome proglem](https://cloud.githubusercontent.com/assets/20993132/19390496/a3594502-9228-11e6-9362-0f80eb1b3e6d.png)

**Comment by calzoneman** [comment]
Can you confirm that if you click on the video that was failing in the playlist, you are able to view it on Google Drive?

**Comment by LukteDukte** [comment]
No, I can't view the video on Google Drive on chrome. But on Firefox it works.
I also tested other videos on google drive and some works and some don't on Chrome.
I tried it on Firefox and every video on Google Drive works.

From what i'm guessing, It looks like Chrome is having issue showing Videos that's from Google Drive.
So this is maybe a Chrome thing this is happening for me.

**Comment by calzoneman** [comment]
Sounds like it.  If you can't view a Google Drive video on Chrome from their own website, I recommend you look around Google's troubleshooting for this; that means it probably isn't a problem with CyTube.

Feel free to reopen if you find that there is an issue with CyTube.

As an aside, @Xaekai was helping someone who was having Google Drive issues and found that it does not work if you disallow 3rd party cookies, so you can check if that setting may be causing issues for you.

**Comment by LukteDukte** [comment]
Yepp, I had the "disallow 3rd party cookies" on. Disabling it made the video work.

Thanks for the help, even though it wasn't Cytube's fault.
