### ISSUE TITLE
NAT loopback bypass feature

### ISSUE THREAD

**Issue by RblSb** [calzoneman/sync#635]
I would like to be able to add local video in a playlist. I'm creating a server using nodejs with the module node-static, which hosts the desired video and successfully add to the playlist by using my global IP address, but I myself can not play it, I need to use a local IP address.

It would be nice to have an extra check box when you add a video to a playlist - all customers receive video through your global IP, and you yourself - through localhost.

**Comment by calzoneman** [comment]
I'm struggling to understand the need for this feature.

>successfully add to the playlist by using my global IP address, but I myself can not play it, I need to use a local IP address.

Why not?  Unless you're using some bizarre routing/firewall rules, your router's public IP address should not behave any differently from any other public IP address, and your computer will connect to it normally.

>It would be nice to have an extra check box when you add a video to a playlist - all customers receive video through your global IP, and you yourself - through localhost.

I don't think it's necessary to implement this as a global feature when it seems to be a corner case with your specific system that can be solved pretty easily.

My recommendation would be, in this order:

  1. Verify that playback using your public IP actually does not work.
  2. Investigate why it does not work.  That would be a problem with your PC/router/firewall or your node daemon and not CyTube.
  3. Failing this, you could write a userscript or some channel JS to implement this.  It would be fairly trivial to intercept the `changeMedia` socket.io frame, match the URL against your IP address/domain, and replace it with "localhost" before forwarding it to the video player.
