### ISSUE TITLE
School firewall blocks CyTube from running?

### ISSUE THREAD

**Issue by Allanbuzzy** [calzoneman/sync#639]
I am on a school computer and I am trying to run CyTube via the school. The school, of course, has a firewall. But the firewall doesn't allow CyTube to run. Apparently, some socket.io problem is causing this and is there a way to fix it?

**Comment by calzoneman** [comment]
It's likely your school's firewall is either blocking websockets or nonstandard ports (I don't have socket.io running on port 80/443 with the other web traffic).  There's not really anything I can do to fix this -- you could talk to the IT department and ask them for more details.
