### ISSUE TITLE
Voteskip socket emit returns {count:0, need:0} twice on changeMedia when voteskip passes

### ISSUE THREAD

**Issue by h2v4c** [calzoneman/sync#641]
Looks like it's caused by playNext() being called before sendVoteskipData - thus calling  VoteskipModule.prototype.onMediaChange which sends its own     this.sendVoteskipData(this.channel.users);
`    if (this.poll.counts[0] >= need) {
        this.channel.logger.log("[playlist] Voteskip passed.");
        this.channel.modules.playlist._playNext();
    }

    this.sendVoteskipData(this.channel.users);

VoteskipModule.prototype.onMediaChange = function (data) {
    this.poll = false;
    this.sendVoteskipData(this.channel.users);
};`

**Comment by calzoneman** [comment]
Nice find!  Would you like to submit a PR to fix it?

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/pull/642
