### ISSUE TITLE
CyTube: Background image problems

### ISSUE THREAD

**Issue by Allanbuzzy** [calzoneman/sync#643]
I've got a problem with my background. The problem I am having is that I do not want a lot of versions of the gif in rows as I just want it to appear once, big in the background of the channel. I do not want it to look like this as it looks just messy.
![screen shot 2017-01-31 at 17 01 15](https://cloud.githubusercontent.com/assets/16272211/22475603/552eeae4-e7d7-11e6-884f-be60d6c9ea7c.png)

**Comment by h2v4c** [comment]
This would be a css issue. What you're looking for is roughly:
#wrap{background-repeat: no-repeat;background-size:100% 100%;} in your css
