### ISSUE TITLE
Ustream support?

### ISSUE THREAD

**Issue by Turkey56** [calzoneman/sync#644]
Hello. I've been using Cytube to stream video to some friends and noticed that Cytube does not show the Ustream video. The audio is able to be played but the only thing that appears is a play symbol. If you click the play symbol, it goes to the Ustream channel's page. This happens on both HTTP and HTTPs. It does seem like the official Ustream channels are able to show both the audio and video but not any of the user streams. I remember user streams from Ustream working on Cytube before so I was wondering if it was not supported anymore. 

Here is an example of what I mean.

This is what happens when you load a user stream.
![user](https://cloud.githubusercontent.com/assets/25919362/23152656/5f8fc18e-f7d1-11e6-93ab-83abcb224d73.JPG)

and this is what happens when you load a Ustream official stream.
![official](https://cloud.githubusercontent.com/assets/25919362/23152667/74fabcc2-f7d1-11e6-94c6-81331144028f.JPG)

**Comment by calzoneman** [comment]
Ustream is kind of weird in the way it handles different channels.  Do you have an example of a channel that doesn't work so I can see if it's fixable?  I've never actually used it myself, so whenever I test it I just grab something from the front page (like the NASA one in your screenshot) and those happen to work.

**Comment by Turkey56** [comment]
Sure. Here's channel that I used that also does not work. 
http://www.ustream.tv/channel/live-radar-and-nws-weather-radio-chicago

**Comment by calzoneman** [comment]
It looks like ustream silently doesn't support HTTPS embeds for those kinds of channels.  That's really unfortunate and kind of dumb, and I didn't realize that when I was moving CyTube to HTTPS only (I thought Hitbox.tv was the last remaining CyTube source that didn't support HTTPS, and they fixed that recently).

I'll see what I can do but I'm not sure this is fixable without undoing HTTPS-only on CyTube or convincing ustream to offer all embds on HTTPS.

**Comment by calzoneman** [comment]
Amusingly, their [help docs](https://support.ustream.tv/hc/en-us/articles/207851917-How-to-embed-a-stream-or-video-on-your-site) mention:

>Some sites will be sensitive to the player loading from http or https. Try adding http:// or https:// in front of the www on your embed code.

But I suppose maybe this doesn't apply to free accounts... I don't have an account handy to try at the moment but I may be able to register one this week and see if it's some specific embed flag.

**Comment by calzoneman** [comment]
Experimental fix: https://github.com/calzoneman/sync/commit/70be35e3fa1da60b91d7e62a76d5436c1b2c76c0

Beta server doesn't have HTTPS right now, but I'll let you know when I get this out to an HTTPS site for testing.

**Comment by calzoneman** [comment]
This ought to be working now, at least I tried it with your example link.
