### ISSUE TITLE
Twitch VODs not playing.

### ISSUE THREAD

**Issue by CLyonsDev** [calzoneman/sync#646]
I'm trying to throw in a twitch video to watch with friends, but the video player just idles on a black screen.
![Picture attached.](https://cloud.githubusercontent.com/assets/7199982/23283059/ea538298-f9d8-11e6-9b90-0cf8c86fbee8.png)

Here's the VOD I'm trying to embed: https://www.twitch.tv/videos/124158595

Was support for VODs dropped, or am I doing something wrong?

**Comment by CLyonsDev** [comment]
Here's some console output.

![image](https://cloud.githubusercontent.com/assets/7199982/23283106/1cfaaa5a-f9d9-11e6-8339-25ab518c48f2.png)

**Comment by Xaekai** [comment]
![image](https://cloud.githubusercontent.com/assets/594255/23284284/80431c9a-f9df-11e6-9cb2-4f261b386077.png)

Clean complete output from a browser with no extensions.

**Comment by CLyonsDev** [comment]
Thank you

**Comment by calzoneman** [comment]
OK, so basically what seems to be going on here is that when I added VODs, I thought they were always of the URL format

```
twitch.tv/{channel}/v/{videoId}
```

But this one is

```
twitch.tv/videos/{videoId}
```

So it's getting queued as a livestream for channel `videos` instead of as a VOD.  Manually queueing it appears to work:

```javascript
socket.emit("queue", { id: "v124158595", type: "tv", pos: "end" })
```

I don't know why Twitch can't decide on 1 URL scheme without changing it randomly, but at least it's easily fixable.

**Comment by calzoneman** [comment]
As an aside, does anyone have an example link to a 'clip'?  I have no idea what the difference is between that and a video, and there's no documentation on clips that I can find, so I need a test URL.

**Comment by calzoneman** [comment]
I hotfixed this on cytu.be, so if you clear your cache and refresh and re-add the video, it should work now.

**Comment by crock** [comment]
@calzoneman Here is an example of a Twitch clip.
https://clips.twitch.tv/aureylian/MushyChimpanzeeVoHiYo

It's in this format:
https://clips.twitch.tv/{username}/{RandomWordsIdentifier}
