### ISSUE TITLE
:[port] keeps getting added to url, even if it's port 80/443

### ISSUE THREAD

**Issue by Rikudouu** [calzoneman/sync#649]
Hello,

I'm attempting to use an apache reverse proxy with Cytube on my server. My reverse proxy works, but not entirely. I can access the page but all the CSS is missing. I believe it's because i'm using Location tags to define when Apache should proxy. Also, when I click login, it keeps adding a :PORT to the end of the url. It ends up looking like this: https://my.domain.net/sync:8082/login... Whereas I want it to look like this: https://my.domain.net/sync/login...
My current setup in virtualhosts:

```
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot "C:/wamp64/www/"
        SSLEngine On
	SSLProxyEngine on
        SSLCertificateFile "(removed)"
        SSLCertificateKeyFile "(removed)"
		<Location "/sync">
		    ProxyPreserveHost On
		    ProxyPass https://my.domain.net:8082
		    ProxyPassReverse https://my.domain.net:8082
		</Location>
        ServerName my.domain.net
</VirtualHost>
```
Obviously I have the values such as the certificate path and domain set to the right values.
Here's the relevant config:
```
listen:
# Default HTTP server - default interface, port 8080
  - ip: ''
    port: 8080
    http: true
    url: http://my.domain.net/sync
# Uncomment below to enable HTTPS/SSL websockets
# Note that you must also set https->enabled = true in the https definition
  - ip: ''
    port: 8082
    https: true
    io: true
    url: https://my.domain.net/sync
# Default Socket.IO server - default interface, port 1337
  - ip: ''
    port: 8081
    io: true
    url: https://my.domain.net/sync
# Example of how to bind an extra port to HTTP and Socket.IO
#  - ip: ''
#    port: 8081
#    http: true
#    io: true
#    url: 'http://my-other-thing.site.com:8081'

# HTTP server details
http:
  # Even though you may specify multiple ports to listen on for HTTP above,
  # one port must be specified as default for the purposes of generating
  # links with the appropriate port
  default-port: 8080
  domain: 'http://my.domain.net/sync'
  # Specifies the root domain for cookies.  If you have multiple domains
  # e.g. a.example.com and b.example.com, the root domain is example.com
  root-domain: 'my.domain.net'
  # Specify alternate domains/hosts that are allowed to set the login cookie
  # Leave out the http://
  alt-domains:
    - '127.0.0.1'
  # Use express-minify to minify CSS and Javascript
  minify: false
  # Max-Age for caching.  Value should be an integer in milliseconds or a string accepted by
  # the `ms` module.  Set to 0 to disable caching.
  max-age: '7d'
  # Set to false to disable gzip compression
  gzip: true
  # Customize the threshold byte size for applying gzip
  gzip-threshold: 1024
  # Secret used for signed cookies.  Can be anything, but make it unique and hard to guess
  cookie-secret: '(removed)'
  index:
    # Maximum number of channels to display on the index page public channel list
    max-entries: 50

# HTTPS server details
https:
  enabled: true
  # Even though you may specify multiple ports to listen on for HTTPS above,
  # one port must be specified as default for the purposes of generating
  # links with the appropriate port
  default-port: 8082
  domain: 'https://my.domain.net/sync'
  keyfile: 'server.key'
  passphrase: ''
  certfile: 'server.cert'
  cafile: ''
  ciphers: 'HIGH:!DSS:!aNULL@STRENGTH'
  # Allow certain account pages to redirect to HTTPS if HTTPS is enabled.
  # You may want to set this to false if you are reverse proxying HTTPS to a
  # non-HTTPS address.
  redirect: true

# Page template values
# title goes in the upper left corner, description goes in a <meta> tag
html-template:
  title: ‘Sync’
  description: 'Watch Videos in Sync'

# Socket.IO server details
io:
  # In most cases this will be the same as the http.domain.
  # However, if your HTTP traffic is going through a proxy (e.g. cloudflare)
  # you will want to set up a passthrough domain for socket.io.
  # If the root of this domain is not the same as the root of your HTTP domain
  # (or HTTPS if SSL is enabled), logins won't work.
  domain: 'https://my.domain.net/sync'
  # Even though you may specify multiple ports to listen on for HTTP above,
  # one port must be specified as default for the purposes of generating
  # links with the appropriate port
  default-port: 8081
  # limit the number of concurrent socket connections per IP address
  ip-connection-limit: 10
  # Whether or not to use zlib to compress each socket message (this option is
  # passed through to socket.io/engine.io).
  # Note that while this may save a little bandwidth, it also consumes a lot
  # more CPU and will bottleneck pretty quickly under heavy load.
  per-message-deflate: false
```
The config doesn't seem to be adjusting any settings for CSS and I can't figure out a way to remove the :8082 from the url.

I'm running the webserver on Wampserver on Windows (Apache 2.4.17, PHP 7.0.0), and Cytube on Ubuntu 15.04.

Any help is appreciated, thanks!

**Comment by calzoneman** [comment]
You need to set `full-address` under `http`, as briefly mentioned on [the installation wiki](https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#configuration-file).  It goes right below where you have `root-domain`.

This is an artifact of the link generation that tries to be smart but is actually dumb and I intend to at some point remove it and require the server admin to configure the base URL manually.

**Comment by Rikudouu** [comment]
Damn, not sure how I missed that, I went over the installation wiki several times. Thanks though, it appears to have fixed the port issue.

Unfortunately, I still have a problem with loading CSS. For some reason, it directs the URL to the root directory of the domain, not to /sync. I tried putting the all the files in /www into /www/sync but that didn't work either.

Let me know if there's a way to fix that, too.

Thanks!

**Comment by calzoneman** [comment]
Oh, I don't think CyTube works in subdirectories.  Everything is written under the assumption that it's running on the root subdomain (which is another thing that might be better fixable with config upgrades).

You may be able to get around the lack of native support by patching [the HTML templates](https://github.com/calzoneman/sync/blob/3.0/templates/head.pug) yourself.

**Comment by Rikudouu** [comment]
Thanks!

Editing the HTML Templates worked for me. I'm going to have to go and edit all the other templates though, because sometimes it's taking me to /login on root instead of /sync/root, but that can be dealt with.

Is there an easy way to update without having git override my templates?

**Comment by calzoneman** [comment]
Git won't overwrite your changes, it'll cause a merge conflict that you'll have to fix.

Or, since you're using a vhost anyways, you could just set up the site on its own subdomain instead of playing whack-a-mole with anything that generates rooted paths.

**Comment by Rikudouu** [comment]
Unfortunately, I'm very limited in running a subdomain at the moment, and don't have the liberty to create another one, so it'll have to be whack-a-mole for me. As long as there's a way to fix it, I will. I appreciate your help!

**Comment by Rikudouu** [comment]
Alright, I went through and change the links accordingly. The only thing that's not working are the dropdown and option menus. I'm unsure how to fix it, because all I see is a '#' for the link.

If you could assist me with this, I would appreciate it.

Thanks for the help thus far.

EDIT: Nevermind, it was just an issue of not linking the javascript files correctly. If anyone else is going to do what I do, here's a tip: don't. But if you absolutely must, then open a web browser and just look through the network inspector for 404's, and then replace them in the templates.

**Comment by calzoneman** [comment]
Likely the JS isn't being loaded because you might have missed some of those links when changing the path.

**Comment by Rikudouu** [comment]
Yep. One thing I noticed is that it's still requesting socket.io.js from the :port, and not using the full-address that I defined :/

It's requesting from the HTTPS port, 8082.

**Comment by calzoneman** [comment]
Yes, socket.io paths are always generated to connect directly, because there's not really any reason to proxy them (and the fact that it has an appended port doesn't really matter because it's not a user-visible link like the main webpage).  You'd have to patch the code to change that behavior.

**Comment by Rikudouu** [comment]
Ok, so I'm nearing the finish, but I've still got a couple problems. 
jquery-1.11.0.min.js is requesting a link to socketconfig/Videos.json and boop.wav. I couldn't find these in the templates, so I just hosted them outside of the app. The only problem i'm having is that I can't find Videos.json. Any ideas?

**Comment by calzoneman** [comment]
On page load, the client makes a request to `/socketconfig/<channel name>.json` to fetch the socket.io connection information.  This is not a static file, it's an application route.  So you'll have to update the client to read from your subdirectory.

**Comment by Rikudouu** [comment]
Ok, so I tried to edit socketconfig.js in /src with the correct link and ran 'npm install', but it still requests from the root directory.

**Comment by ghost** [comment]
Need to run 'npm run build-server' not npm install i believe

**Comment by Rikudouu** [comment]
I tried both, but neither one worked.

**Comment by ghost** [comment]
Did you restart afterwards to reload the files?

**Comment by Rikudouu** [comment]
I did everything, including npm install, while the server was off, so I effectively _did_ restart it. Eventually got it working though, thanks for all your help guys!

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/blob/3.0/www/js/callbacks.js#L1269

I'm going to go ahead and mark this issue as 'closed' since at this point the discussion is unrelated to the original issue.
