### ISSUE TITLE
Chat Filters in control panel modifiable only by Channel Administrators

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#65]
Moderators' job is to maintain peace on channel and manage the playlist, they shouldn't meddle with wordfilters (mostly creating useless ones).

**Comment by calzoneman** [comment]
Yeah that's probably a good idea.

**Comment by uchigawa** [comment]
May I suggest also custom CSS and custom JS inaccessible for moderators, only for channel owners?

**Comment by ghost** [comment]
> May I suggest also custom CSS and custom JS inaccessible for moderators, only for channel owners?

That too.
