### ISSUE TITLE
stay fullscreen

### ISSUE THREAD

**Issue by katzekatze** [calzoneman/sync#651]
Hi,

Is there a way to stay in fullscreen mode when a new video starts?
I noticed the extension does it with youtube vids, but not with the google drive player or whatever its called.

**Comment by Xaekai** [comment]
It should stay fullscreen if you use the fullscreen button that's present in the playlist controls bar, not the one on the video pane.

**Comment by katzekatze** [comment]
HOLY SHIT THANK YOU SO MUCH!!
im an idiot, i never noticed the button in the playlist controls bar -.-
THANKS!
