### ISSUE TITLE
Feature Request: Max total playtime by user

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#654]
CyTube currently supports limiting the following per-user:

  * Number of videos added to the playlist
  * Duration of an added video

But there is no option to limit the total playtime per user.  A channel moderator requested an option to limit this to prevent a single user from hogging the playlist by adding a lot of long videos (for example, it may be permissible for a user to add one 20-minute video, but not 5 of them).

**Comment by Xaekai** [comment]
![image](https://cloud.githubusercontent.com/assets/594255/24189026/b4b003dc-0ea0-11e7-9107-0b6a5bdaf176.png)

**Comment by doonoo** [comment]
[cytube plus](https://github.com/zimny-lech/CyTube-Plus)

**Comment by calzoneman** [comment]
I don't think that cytube plus is relevant here.  The feature request is for CyTube to support serverside validation of the total runtime of a user's videos in the channel playlist.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/b1a328d2e08f0d3fc5094a9482e2bea93ec77bf9

**Comment by calzoneman** [comment]
This is now available for testing on beta.synchtube.me

**Comment by calzoneman** [comment]
This is now deployed to live (notwithstanding a bug in the time parser), so resolving this.
