### ISSUE TITLE
Voteskip button stays disabled after going afk

### ISSUE THREAD

**Issue by h2v4c** [calzoneman/sync#656]
Extremely minor issue - replication: voteskip a video via button, then type /afk as many times as you like in chat. Easy to fix within channel scripts but thought I'd bring it up here as well.

Fix being used in our channel:
```
    'setAFK':(data)=>{
        if(data.name==CLIENT.name && data.afk==true){$('#voteskip').attr('disabled',false)}
    },
```

**Comment by calzoneman** [comment]
This should be resolved once the above commit goes out to live.

**Comment by 2Karol** [comment]
'setAFK':(data)=>{
        if(data.name==CLIENT.name && data.afk==true){$('#voteskip').attr('disabled',false)}
    },
