### ISSUE TITLE
Twitch Clip Support

### ISSUE THREAD

**Issue by AKPWebDesign** [calzoneman/sync#659]
I've got some information on Twitch clips, if it helps. URLS seem to be `https://clips.twitch.tv/SomeRandomWords`. You can take any clips url and go to its associated API info at `https://clips.twitch.tv/api/v2/clips/[Clip ID]`. As an example, you can look at https://clips.twitch.tv/api/v2/clips/ColorfulBlushingHarePogChamp. To get the mp4 videos associated with a clip, you can get the status API call for the clip: https://clips.twitch.tv/api/v2/clips/ColorfulBlushingHarePogChamp/status. They've also got an `embed_html` property in the clip information, which may be helpful.

**Comment by calzoneman** [comment]
Unfortunately, according to the [Twitch developer documentation](https://dev.twitch.tv/docs/v5/guides/embed-video/#non-interactive-frames-for-clips), Clips do not support the JavaScript API that is used for VODs currently.  This means it would not be possible to synchronize (maybe not an issue for short clips, I don't know how long clips are allowed to be?).

I'll have to look into this more.

>Embedding a Clip is different than embedding a live stream or VOD. The embedded Clips player uses a different set of query parameters and does not support the JavaScript interactive embed.

**Comment by nduriez** [comment]
I think Twitch clips record the last 30s when you press the button

**Comment by calzoneman** [comment]
Oh, so actually I was a little mistaken.  Twitch's *embed* player doesn't support JS operations on Clips, but since there is apparently an API to get the raw MP4 URLs, it should be possible to just plug them into the existing Video.JS player.  I'll take a look at it.

**Comment by irufus** [comment]
Trashy twitch clip HYPE

**Comment by calzoneman** [comment]
I'm hoping to take a look at this this weekend.

**Comment by calzoneman** [comment]
Now available for testing on http://beta.synchtube.me.

**Comment by calzoneman** [comment]
This is live now as of a few days ago.  Closing.
