### ISSUE TITLE
Can't write in chat as guest after logout from account with changed options

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#66]
Looks like a cookie issue for me, since clearing them helps.

**Comment by calzoneman** [comment]
This should only happen if you set the modflair option, which is an easy fix on my end.  Please confirm other options don't affect it.

**Comment by ghost** [comment]
I do confirm, modflair is the only cause.

**Comment by calzoneman** [comment]
Yeah, what's happening is that when USEROPTS.modhat is true, "/m " is automatically prepended to the outgoing message.  Since guests can't use /m, the result is that nothing happens.

I just need to add a rank check before prepending /m and it should be fine.
