### ISSUE TITLE
[User-reported] Chat is not auto-rescrolled following window resize event

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#666]
When resizing the window, the height of the chat buffer may change, which causes the scroll position to change.  The scroll position is not automatically reset to the bottom of the buffer until the next chat message is sent.

Should be easily fixable by listening to the resize event on the `window` object and calling `scrollChat()`.

**Comment by calzoneman** [comment]
Also, issue #666 😈

**Comment by Xaekai** [comment]
Damn it, I wanted #666 for a PR.

**Comment by calzoneman** [comment]
Rekt.
