### ISSUE TITLE
Error: Cannot find module 'cytube-mediaquery/lib/provider/twitch-clip'

### ISSUE THREAD

**Issue by Rikudouu** [calzoneman/sync#673]
I just ran git pull and npm run build-server, and now when I try to launch Cytube, I get the following error:

Error: Cannot find module 'cytube-mediaquery/lib/provider/twitch-clip'

And I get a 503 error.

**Comment by Xaekai** [comment]
You probably need to do `npm update` to touch up the dependencies

**Comment by calzoneman** [comment]
As Xaekai mentioned, most "Cannot find module" errors after pulling the latest code are due to out of sync or outdated dependencies.

My deployment process for updates is to completely remove `node_modules` and reinstall the dependencies from scratch, but `npm update` probably also works.

**Comment by Rikudouu** [comment]
Yep, it worked, thanks.
