### ISSUE TITLE
Live updating User Profile Changes

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#677]
Channel.prototype.sendUserProfile is lonely.
It would be lovely if it had some visitors. Maybe from the faraway land of `web/account.js`

**Comment by calzoneman** [comment]
This was first [added](https://github.com/calzoneman/sync/commit/0f82faaef8c96ff981d63b9909a9f4047f90c2fe) in January 2014 and then [removed](https://github.com/calzoneman/sync/commit/9ea48f58cf2020b05aa64f6fa0cd4eed2b3d1007) 4 months later.  It hasn't been used in 3 years, so I think it's safe to just deprecate this method.

Updating profiles on the fly is trickier than just calling this from another place, because with sharding the user may update their profile on a different server than the channel is on.  Personally, I consider profile information to be infrequently-changed enough that not taking effect until the next connection is fine, but that can be considered as a separate feature request if needed.

**Comment by Xaekai** [comment]
Yes, consider this a feature request for live updating user profiles. I know it's an infrequent action, but it feels like implementing this would be the proper way to do things.

Also, I thought the code for dealing with cross-shard communication was already in place, how are cross-shard channel deletions handled?

It seems to me the only thing we need is a `sv.getChannelsUserConnectedTo()` type method.

**Comment by calzoneman** [comment]
>I know it's an infrequent action, but it feels like implementing this would be the proper way to do things.

Is there any evidence that this is something people want, or that inconveniences them by not being implemented?  Or is it going to end up as another ghost feature that is maintained for years and doesn't really bring any value?

>Also, I thought the code for dealing with cross-shard communication was already in place, how are cross-shard channel deletions handled?

Currently, they are not.  It's a known issue/bug that deleting a channel that's loaded on another server doesn't unload it, and logs a lot of foreign key errors when it continues to try to save state.

**Comment by Xaekai** [comment]
I've been asked why this doesn't exist about 5 times in the past two years. (Well more like "how come I have to refresh to see changes?") Not exactly overwhelming demand, but not exactly silence on the issue either.

It's not critical, but it would be nice to have and if I didn't think it had value, I wouldn't have brought it up. I also believe it probably won't require much maintenance if we wait to implement it until after you've settled how cross-shard communications are going to be resolved.

**Comment by d-dd** [comment]
I think I asked once a long time ago too after it went away. My use case would be using it for the bot as a fluff feature where it would change its profile picture depending on its mood. Nothing critical but would be fun to have.

**Comment by calzoneman** [comment]
I have a plan to work on a generic message bus for cross-server communication which should make this pretty easy to implement.

**Comment by Xaekai** [comment]
A generic method to find out what channels a user is currently connected to would be useful for some other reasons too.

**Comment by calzoneman** [comment]
>A generic method to find out what channels a user is currently connected to would be useful for some other reasons too.

The solution to this issue does not provide that.  If knowing what channels a user is in is desirable, that will have to be tracked in a separate issue with an explanation of the requirement and the rationale.

**Comment by calzoneman** [comment]
Available for testing on beta.

**Comment by calzoneman** [comment]
Just confirmed this is working on live.
