### ISSUE TITLE
Single Source Of Truth issue with AFK status

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#678]
There are several members involved in this gang of chaos

But first, a picture says a thousand words.
![image](https://user-images.githubusercontent.com/594255/26962933-7d4edca6-4c9e-11e7-80b4-c3820beb39fb.png)

When addUser handler builds the userlist object, it assigns a seperate "afk" property from the meta, and also assigns meta to a property directly. [line 509 callbacks.js](https://github.com/calzoneman/sync/blob/00a65a1584bf3e2dd78efb1a678829b935814ee0/www/js/callbacks.js#L509)

the setAFK handler only modifies the separate AFK property
the setUserMeta handler only modifies the real meta property

This can lead to the following situation:
User joins room. `afk` and `meta.afk` are both `false`
User goes afk. `afk` is true. `meta.afk` is `false`
User is then muted while afk. `afk` and `meta.afk` are both `true`
User voteskips. `afk` is `false`, `meta.afk` is `true`

I propose disposing of setAFK entirely, and leaving metadata in the meta property where it belongs. Anything that needs to access the AFK of a user can do so via `findUserlistItem(username).data().meta.afk`

**Comment by calzoneman** [comment]
I think it would be fine to change `setAFK` and `formatUserlistItem` to use `meta.afk` instead of a top-level `afk` property (this would be consistent with mutedness).  `setAFK` can't be removed without breaking backwards compatibility so that frame will have to stick around for now.

**Comment by Xaekai** [comment]
Backwards compatibility with what? Nuke's bot never even handled it, so that just leaves channel scripts. I can't image many people added their own listener for it. But we can still get rid of it and account for that.

Drop it on the server side, and just emulate on the client like so:

```
// within setUserMeta
socket.listeners('setAFK').forEach(function(listener){
    listener(meta.afk)
})
```
