### ISSUE TITLE
Dotations <div> right above footer

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#68]
Just like here http://synchtube.6irc.net/ - I suggest adding a placeholder div with dotations code and with proper id (so the channel owners can easily hide it in custom css) right above the footer - preferably containing a HTML from external file, so the git merges won't prompt about the conflicts.

**Comment by calzoneman** [comment]
The only way to include an external HTML would be to use an `iframe`, since I'm serving files statically.  It can be a pain in the butt to get the styling to look right, but it might be possible.

**Comment by ghost** [comment]
What about jquery .load() ?

**Comment by calzoneman** [comment]
I'll look into that

**Comment by ghost** [comment]
it's as simple as `$('#dotations').load('dotations.html');`

**Comment by calzoneman** [comment]
Yeah, it shouldn't be hard to implement, I'm just recovering from dealing with a situation on my server right now.

**Comment by calzoneman** [comment]
I named it more generally as a site footer, so admins can add whatever they want to the bottom of the page.
