### ISSUE TITLE
Tor block affects non-exit relays

### ISSUE THREAD

**Issue by frh** [calzoneman/sync#688]
The Tor block gets its list of IP addresses to block from https://www.dan.me.uk/torlist/. This list includes all Tor relays, including those that aren't exit nodes. These relays can't be used by Tor users to connect from, so there is no reason to block them. It only affects users who run relays on the same connections the use to access the channels.

It would be better to instead use a list of exit nodes, either using the list at https://check.torproject.org/exit-addresses, or the list at https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=123.123.123.123 to get a list of exit nodes that can connect to the server, of course using the server's IP address instead of 123.123.123.123.

**Comment by calzoneman** [comment]
Changed in the above commit.  Will resolve this issue once the code lands on the live server.

**Comment by frh** [comment]
Confirmed, works great. Thanks!
