### ISSUE TITLE
WYSIWYG MOTD Editor and a few improvements

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#69]
Firstly, moderators of http://synchtube.6irc.net/r/rcp are allowed to modify the MOTD in order to fill the radio schedule, however it would be better if they could use a table, yet there are some people who can't use html. Secondly, people from synchtube.6irc.net/r/ponenyymit suggested that MOTD field is a good place to put a banner. Thirdly, is there any (safe) way to enable script tags in the MOTD? I have got a script that prints out a radio status in realtime, and it would be easier to include it directly in the MOTD than using custom JS option.
BTW, is or could be MOTD transmitted via JSON too?

**Comment by calzoneman** [comment]
Embedding scripts wouldn't be hard, it's just a matter of changing the `<p>` tag.  As for making the editor a WYSIWYG, that sounds greatly overcomplicated.  Tables are pretty easy as far as HTML goes (especially given that I'm using Bootstrap so they're already nicely formatted).

**Comment by calzoneman** [comment]
I actually tried, and I couldn't get `script` tags to work in the MOTD.  I have a feeling it's probably a browser security feature that disallows injecting arbitrary Javascript.
