### ISSUE TITLE
JWPlayer not working anymore?

### ISSUE THREAD

**Issue by m05h1** [calzoneman/sync#694]
When giving a JWPlayer link adding to it the precursor `jw:`, as it used to work before, now it doesn't.
All it does is give this error:
`Error
Unknown media type 'jw'`

**Comment by Xaekai** [comment]
JWPlayer was deprecated long long ago and then completely removed in https://github.com/calzoneman/sync/commit/8d40c87dda8b12a49d0512483a8a092682202fbb
