### ISSUE TITLE
Bitwarden add-on for Firefox gets you kicked from any channel

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#699]
If you try to enter any channel on https://cytu.be/ or https://synchtu.be/ where you aren't a moderator with the https://addons.mozilla.org/pt-BR/firefox/addon/bitwarden-password-manager/ add-on enabled, the channel kicks you out and gives you this message "Kicked: Attempted setOptions as a non-moderator".

**Comment by calzoneman** [comment]
There's a channel settings modal (which is hidden on page load) which
includes a password field for setting a password users must enter to join
the room. My guess would be your extension is eagerly walking the page
(even hidden elements) and filling in every password field it can find.

Now, there are a few possible workarounds within CyTube itself, but
honestly this seems like a huge vulnerability in your password manager --
someone could easily read your password simply by creating a password input
and watching for its value to change (as CyTube does for that particular
settings menu).

**Comment by ghost** [comment]
Looks like this add-on doesn't have an option to disable the autofill. So, if I request this option with the Bitwarden team, this could potentially solve the problem, right?

**Comment by calzoneman** [comment]
Yeah, that seems like the best solution.  Password managers should probably not be filling in random hidden text fields without the user's knowledge; that seems easily abusable and also prone to accidental input like this.

**Comment by ghost** [comment]
Ok then, I'll take a look at that. Closing the issue, thx.
