### ISSUE TITLE
Empty strings in the filters list

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#70]
However, their number is alright and all of them work just fine.
![image](https://f.cloud.github.com/assets/3297156/440601/83420b2e-b102-11e2-9967-552e7ee8376c.png)

**Comment by calzoneman** [comment]
Check for Javascript errors, and clear your cache to make sure your browser is using the updated `functions.js`.  I extensively tested locally (including with dumps of the old format to be imported) and I did not experience this issue.

**Comment by ghost** [comment]
Ok, it's alright now.
