### ISSUE TITLE
Vid.me Videos No Longer Play

### ISSUE THREAD

**Issue by Saberleo456** [calzoneman/sync#703]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x ] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ x] Disabling all browser extensions
  - [ x] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem?
Adding Vid.me videos to Cytu.be
  - What happens?
The video does not play and instead shows a black rectangle
  - What do you expect to happen instead?
The video from Vid.me to play

### System Information ###

  - **Operating System: Windows 10:**
  - **Web Browser: Chrome:**
  - **Error Messages Displayed: None**
  - **Screenshot of JavaScript Console:**
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._
https://i.imgur.com/Ne8k1tt.png
  
### Description of the Problem ###

  - What triggers the problem?
Adding a video from Vid.me
  - What happens?
No video displayed
  - What do you expect to happen instead?
The video from Vid.me to play
  
### System Information ###

  - **Operating System: Windows 10**
  - **Node Version:** _(run `node -v`)_
  - **CyTube Version:** _(displayed at startup)_
  - **Error Messages Displayed:**

**Comment by calzoneman** [comment]
It looks like for newer uploded videos, vidme is no longer including a plain MP4 link in the API response, only HLS and DASH manifests, which is unfortunate.

I do have a video.js plugin for HLS, but that's only used for livestreams currently and I haven't tested whether that would work for vidme.  Failing this, it may be possible to hack the video URLs out of the returned HLS manifest but I'm skeptical that solution would be stable.

All around disappointing and work I'd rather not have to do, just for a meme technology...

**Comment by calzoneman** [comment]
Ok, so luckily it turns out the HLS manifest works as-is when given into the videojs-hls plugin.  It isn't compatible with CyTube's quality selection preferences because the distinction between quality levels is internal to the HLS manifest rather than a separate source, but that maybe isn't the end of the world because the plugin [tries to be smart and automatically adjust the bitrate](https://github.com/videojs/videojs-contrib-hls/blob/master/docs/bitrate-switching.md) based on the viewer's internet speed and viewport size.

That being the case, it should be relatively simple to put out a patch for this.

**Comment by calzoneman** [comment]
This autoclosed because I pushed a fix commit.  Reopening until this is deployed to the live server.

**Comment by calzoneman** [comment]
I've pushed this to https://beta.synchtube.me.  Could you please test if the videos you were having trouble with are working there?  My test video (arbitrarily chosen from one of the front page channels on vid.me) seems to be working.

**Comment by Saberleo456** [comment]
Yes, it works using a video I put up myself, thank you for the work you've done

**Comment by calzoneman** [comment]
Closing since this has been live for a while with no complaints.
