### ISSUE TITLE
Socket.io library could not be loaded

### ISSUE THREAD

**Issue by emoyly** [calzoneman/sync#704]
## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [x] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [x] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [x] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem? Joining a channel
  - What happens? https://i.imgur.com/OLpyiU2.png - The io socket is not created at the expected address. It does work with http://website.domain:1337/socket.io/socket.io.js, but it still displays the message, since it can't connect to a non ssl secured webpage. (https://i.imgur.com/xTt1Syv.png)
  - What do you expect to happen instead? It should create a secured socket with ssl, and then work.
  
### System Information ###

  - **Operating System:** Ubuntu 16.04
  - **Node Version:** _(run `node -v`)_ v6.11.3
  - **CyTube Version:** _(displayed at startup)_ v3.47.2
  - **Error Messages Displayed:** The socket.io library could not be loaded from https://website.domain:1337/socket.io/socket.io.js. Ensure that it is not being blocked by a script blocking extension or firewall and try again.

**Comment by Xaekai** [comment]
You are missing [https io](https://github.com/calzoneman/sync/blob/3.0/config.template.yaml#L30) in the `listen` block of your `config.yaml`.
It should be trying to load from https://radio.stavox.com:8443/socket.io/socket.io.js

**Comment by emoyly** [comment]
@Xaekai 
I'm pretty sure it's already enabled, or am i completely lost?
https://i.imgur.com/MMddL5S.png

**Comment by emoyly** [comment]
@Xaekai Nevermind.
I got it working, by changing my domain under the io block https://i.imgur.com/HNQe7sg.png
