### ISSUE TITLE
Issue with emotes containing username

### ISSUE THREAD

**Issue by Yaanu** [calzoneman/sync#705]
## Website Problem ##

  - [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  
### Description of the Problem ###

(What triggers the problem?)
Using a custom emote with a name the same as your own username.
In /r/FreedomChat, there is a custom emote called /blameyaanu. When I or others use the emote, for me the text of the emote appears, but the image does not. Other users can see the emote on their end; this issue affects me. I believe it might have to do with the highlighting/mention feature in CyTube cancelling out the use of the emote, but I can't confirm.

(What happens?)
The text of the emote appears, and the image itself does not.

(What do you expect to happen instead?)
I expect the image to appear.

### System Information ###

  Operating System: Windows 10
  Web Browser: Chrome
  Error Messages Displayed: None

**Comment by AssTractionHero** [comment]
What I can tell you is that using a slash as the trigger for an emote is probably going to interfere with some of the other commands that use slash as a trigger. Have you tried adding the emote without the slash? e.g. "blameyaanu", without the leading slash?

**Comment by Yaanu** [comment]
I'm not an admin, so I'll have to remember to ask about that when one appears. 
However, the room does use slashes for all our other emotes and they've worked without issue.

**Comment by calzoneman** [comment]
I'm unable to reproduce this issue in my test channel, emotes with names in them work normally.  I did notice that FreedomChat is using a third-party script called CyTube Plus from August 2014, which is now 3 years ago, so it's plausible that something has changed since then which causes the script to malfunction.

Can you try in a different channel with no scripts, or disable scripts on FreedomChat (from Options -> Script Access) and try again?

**Comment by Yaanu** [comment]
I tried, and yet the problem persists.

Here, you can see that I both denied script access and ignored custom Javascript/CSS settings, to no avail.
![fc-denyscriptaccess](https://user-images.githubusercontent.com/2125527/30518102-a6024216-9b39-11e7-9411-df950928d072.png)
![fc-ignorecssjavascript](https://user-images.githubusercontent.com/2125527/30518104-a97a9c7c-9b39-11e7-96f7-17fcffdce895.PNG)

This one is from a channel for which I have admin access; I never installed any scripts, so it's entirely clean. The emote was added right then and there, but it still didn't show.
![sm-adminaccess](https://user-images.githubusercontent.com/2125527/30518105-ac9db0b0-9b39-11e7-8366-a43b70144266.PNG)

If it weren't for others being able to see the emote, I'd have started to think that it might be a denial from GfyCat.

**Comment by calzoneman** [comment]
I've replicated your setup identically on my test server (including registering an account as "Yaanu" and using the same image) with both Firefox and Chromium and it works as expected:

![2017-09-16-220125_1916x1041_scrot](https://user-images.githubusercontent.com/385672/30518167-9a753822-9b2a-11e7-8e0f-8ffcb9a97101.png)

>If it weren't for others being able to see the emote, I'd have started to think that it might be a denial from the host.

You should be able to check this by opening the image link manually.  However, it may also be possible that some browser extension is interfering, although I don't know why it would impact this emote specifically and not others.

Can you try opening your browser's debug console with F12 and looking at the Console and Network tabs?

**Comment by Yaanu** [comment]
I figured out what the problem was.

Opening the debug console showed that the image was attempted to be loaded, but was denied. I poked through some of my browser extensions again and realized that Privacy Badger was blocking all requests from thumbs.gfycat.com. Setting it to only block cookies has fixed the problem.

Thanks for the advice, and I'm sorry to have troubled you guys with this.
