### ISSUE TITLE
Streamable broken

### ISSUE THREAD

**Issue by CLyonsDev** [calzoneman/sync#706]
Whenever we put a streamable link (such as https://streamable.com/a94or), we get an error saying the media could not be loaded because "the server or network failed or because the format is not supported". If you need any more information I'm happy to provide it. We all use chrome.

**Comment by calzoneman** [comment]
CyTube actually does support streamable (this is how it adds to the playlist at all), however it appears that streamable's video links are returning 403 Forbidden when the `Referer` header indicates the video is embedded outside of streamable.com:

```
» curl -IH "Referer: https://example.com" "https://cdn-e2.streamable.com/video/mp4/a94or.mp4?token=1506875923_6826a1d2159ceb52c54195d5eed0aa568422902b"
HTTP/2 403 
```

```
» curl -IH "Referer: https://streamable.com" "https://cdn-e2.streamable.com/video/mp4/a94or.mp4?token=1506875923_6826a1d2159ceb52c54195d5eed0aa568422902b"
HTTP/2 200 
```

I'll have to do some investigation to see if they no longer support embedding.

**Comment by calzoneman** [comment]
I've submitted a support request to streamable regarding the change in behavior and will report back the results once I hear back (I assume they will probably not answer on Sunday).

>The CDN URLs returned from the JSON API are now returning 403 Forbidden of the Referer is not streamable.com; e.g.:
» curl -IH "Referer: https://example.com" "https://cdn-e2.streamable.com/video/mp4/a94or.mp4?token=1506875923_6826a1d2159ceb52c54195d5eed0aa568422902b"
HTTP/2 403 
Is this no longer supported?  The use case is that I need to both embed the video and control the playback from JavaScript.  From what I can tell, the embed iframe provided does not provide an API for this, but if it does (like YouTube, Vimeo, Dailymotion, etc. do) then I'd be happy to use that instead.

**Comment by calzoneman** [comment]
Pinged support again.

**Comment by calzoneman** [comment]
https://twitter.com/CyTubeDev/status/911075462620733440

**Comment by CLyonsDev** [comment]
Interesting. Here's hoping you can finally get a response out of them.

**Comment by calzoneman** [comment]
Received an email response:

>Hi Calvin,
>Sorry for the delay here. The embed iframe can be controlled via javascript according to the PlayerJS spec.
>Here is an example:
http://playerjs.io/test.html?url=https%3A%2F%2Fstreamable.com%2Fe%2Fmoo
>Hope that helps!
>Armen

Haven't looked in detail yet, but it looks like playerjs should be CyTube compatible (albeit yet another JS dependency).

**Comment by calzoneman** [comment]
I've got a patch up on https://beta.synchtube.me/.  As long as there are no problems with that, I'll push it to live ASAP.

**Comment by calzoneman** [comment]
Deployed to live.
