### ISSUE TITLE
Userscript Issue with Chrome

### ISSUE THREAD

**Issue by MonfGeiger** [calzoneman/sync#708]
## Website Problem ##
cytu.be/r/Doomhole
and every channel so far that uses google drive videos

**Please confirm whether you've tried the following debugging steps:**

  - [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  - [x] Using a clean channel with no customizations
And yes, I did test this out in microsoft edge with tampermonkey and the google drive script installed, no dice
### Description of the Problem ###

  - What triggers the problem? I try watching ANY video from google drive through cytube
  - What happens? Nothing, literally no video, stuck on however long it is
  - What do you expect to happen instead? The script working, like it should, but it don't

### System Information ###

  Operating System (Windows 10 Pro 64-Bit)
  - **Web Browser (Chrome, updated to latest stable version)
  - **Error Messages Displayed:** (None directly from the website itself, which is weird, just a blank area where the video SHOULD load)
Javascript Screenshot
![cytube javascript error](https://user-images.githubusercontent.com/28603306/31042943-5f95794c-a570-11e7-81e7-10b9ec314b60.PNG)
  
So just as my little addition, I don't know WHERE it all started to mess up, but I can't watch any google drive video from cytube, I tried uninstalling the script from violentmonkey and re-installing, even setting the cytube website in the include list in the google script and the exclude list in the other scripts I have, whitelisted cytube in ublock origin, and added cytube in the allow cookies list in google chrome, and tested it in microsoft edge with tampermonkey, but nothing

**Comment by calzoneman** [comment]
>I tried uninstalling the script from violentmonkey and re-installing

I'm not familiar with violetmonkey; I only have tested the script with Tampermonkey on Chromium, and Tampermonkey and Greasemonkey on Firefox.  Have you tried with one of these supported configurations?

**Comment by MonfGeiger** [comment]
violentmonkey is a userscript manager like tampermonkey and greasemonkey, but no ads and/or links to other various stuff floating about; its on the chrome extensions store, and its worked just fine for me in the past with cytube; as for browsers, ill try this one more time with firefox (greasemonkey and the script), see if it works, and if not, then ill post the javascript screenshot and hope something can be done

**Comment by MonfGeiger** [comment]
so at this time, im in the same doomhole room, just loaded up and allowed an embedded script to run, and after waiting, then reloading the room, it works in firefox now? Using greasemonkey, and the google script, with firefox's history settings at custom, allowing cytu.be as a site-wide exception
![google script firefox](https://user-images.githubusercontent.com/28603306/31051179-a1149ce6-a61e-11e7-83a2-78eb229ce7a6.PNG)
I think for whatever reason, the embedded script that shoud show doesn't proc, and I guess that script allows the google userscript to run correctly, so if there's any setting I need to change in any of my extensions or chrome itself, im willing to try it, because im not sticking with one browser for one website, and another for everything else

its either one, or none

**Comment by calzoneman** [comment]
The warning messages you are seeing in this case are not related to the video; it's simply Firefox warning you that some images are being loaded over plain HTTP while CyTube is using HTTPS.

>I think for whatever reason, the embedded script that shoud show doesn't proc, and I guess that script allows the google userscript to run correctly

The embedded script is not impacting the video playback in this case.  I checked and all Doomhole's script is doing is loading some additional poll functionality from one of Xaekai's plugins.

>if there's any setting I need to change in any of my extensions or chrome itself, im willing to try it, because im not sticking with one browser for one website, and another for everything else

Tampermonkey is available for both Firefox and Chrome and is supported by this userscript.  It should not be necessary to use a different browser; many CyTube users are using the Google Drive userscript on Chrome without issue.

For more information, please see the [installation guide](https://github.com/calzoneman/sync/wiki/Google-Drive-Userscript-Installation-Guide) that was contributed by a CyTube user.

**Comment by MonfGeiger** [comment]
only other way to see is to uninstall and reinstall chrome; maybe that will help; ill try using chrome beta and see if that does anything; if not, then normal chrome, if not, then I'll try tampermonkey instead of violentmonkey

if all of that does nothing, then I have no idea what to do; will post later on with results

**Comment by MonfGeiger** [comment]
so I haven't tested beta or the canary versions of chrome; switching to tampermonkey fixed it

seems like violentmonkey is broke for newer versions of chrome and there's no issue with tampermonkey; sorry for wasting everyone's time

**Comment by calzoneman** [comment]
I see, thanks for the update.
