### ISSUE TITLE
Emotes are no longer case-insensitive

### ISSUE THREAD

**Issue by 165your4** [calzoneman/sync#711]
This changed fairly recently - a few months ago at most. Is this a bug? It seems like a weird change to make and it's really annoying for typing out emote codes on phones because of AutoCorrect. If this was an intended change, is there any chance that we could have a channel-side option to turn it off?

**Comment by calzoneman** [comment]
>It seems like a weird change to make

It was a side effect of switching to a different way of handling emotes that's more efficient.  However, it was not intended that emotes were case-insensitive before.  In fact, the server has always allowed you to add multiple emotes named `emote`, `EMOTE`, `eMoTe` (for example), but before, the client matched case-insensitively so which emote actually ended up being used was more or less random from the user's perspective.

Only 1 channel reported being affected by case-sensitivity so Xaekai helped them with a script and I didn't consider case-sensitivity a regression.  Now that there is another report, it may be worth looking into whether removing case-sensitivity would meaningfully break anyone and change it back to case-insensitive (with appropriate server-side checks as well).

>it's really annoying for typing out emote codes on phones because of AutoCorrect

The tab-completion in the chat line works case-insensitively, although I grant that tab completion may not work on mobile devices with soft keyboards that lack a tab key.

**Comment by calzoneman** [comment]
I did a little investigation and it seems that there are 200+ channels with at least one emote that has different images for different capitalizations.  While the total number of such emotes is quite small, the spread across channels makes me a little uneasy about making a breaking change.

Making it a channel-specific setting could be an option.

**Comment by calzoneman** [comment]
This is now 3 years old, changing the behavior is likely to break someone's emote list.
