### ISSUE TITLE
Issues with RTMP streams

### ISSUE THREAD

**Issue by Kamikze-1** [calzoneman/sync#712]
Please fill out the templates below to the best of your ability, based on whether your problem is with **using the website** or --with running your own server--.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [YES] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [YES] Disabling all browser extensions
  - [YES] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem?
Adding a rtmp livestream on the playlist
  - What happens?
Error shows up: No compatible source was found for this media.
  - What do you expect to happen instead?
Livestream should load like it was doing a week ago.

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows
  - **Web Browser (Firefox / Chrome / Other):** Firefox, Chrome and Internet Explorer show the same issue.
  - **Error Messages Displayed:** No compatible source was found for this media.
  - **Screenshot of JavaScript Console:** https://i.imgur.com/5anM3jD.png
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

**Comment by calzoneman** [comment]
Hi,

I checked on the link you included in your screenshot, and it looks like the rtmp server hosting that stream is not responding:

```
» mpv rtmp://streams.v4c.life/live/autism
Playing: rtmp://streams.v4c.life/live/autism
[ffmpeg] tcp: Connection to tcp://streams.v4c.life:1935 failed: Connection refused
[ffmpeg] rtmp: Cannot open connection tcp://streams.v4c.life:1935
Failed to open rtmp://streams.v4c.life/live/autism.
```

Please check with the operator of the stream -- CyTube does not host RTMP content, it only embeds RTMP streams hosted by users.

**Comment by Kamikze-1** [comment]
It should be on now for you to test, Ive left it up streaming some random vid.

Some more info:

On the players (VLC, MPC-HC) both of these methods work for opening the stream:
rtmp://streams.v4c.life/live/autism
http://streams.v4c.life:8080/live/autism.m3u8

On cytube, however:
rtmp shows the error I commented on the OP across all browsers

http method works on microsoft edge, 
fails in firefox with this message https://i.imgur.com/air9C8n.png ; 
and on chrome gives no error message, never loads, and the following error can be seen on the console https://i.imgur.com/4aYCQxz.png
seems to be because im not hosting it on https, really makes me wonder why does it work on edge though


Hope this helps. I'll leave it on

**Comment by calzoneman** [comment]
I have confirmed that the RTMP stream is functioning normally for me in Chromium.

Please check your browser's settings as many browsers are now blocking Flash Player by default, which is required for RTMP:

In Chromium, you can find the Flash setting under Settings -> Advanced -> Privacy and security -> Content settings.  I have mine set to "Ask first" on this browser, and I had to confirm that I wanted to enable Flash before the video would play.

**Comment by Kamikze-1** [comment]
Updated the last comment with HTTP method

**Comment by Kamikze-1** [comment]
Still not working after specifically whitelisting flash on chrome https://i.imgur.com/hQNKNwA.png

**Comment by Kamikze-1** [comment]
Got it working on chrome after correcting the whitelist, 
At least for me it doesnt work unless explicitly whitelisting https://cytu.be

**Comment by calzoneman** [comment]
OK, that sounds like it is either a bug or intended feature of Chrome; I recommend you follow up on their bug tracker for further information about this.

CyTube is not doing anything unusual here, just embedding a SWF the same way that has been standard for many years.  Unfortunately it is not possible (to my knowledge) to play RTMP streams without Flash Player (an alternative is to use HLS, which is supported in HTML5).
