### ISSUE TITLE
Add support to Violentmonkey

### ISSUE THREAD

**Issue by KingThunder** [calzoneman/sync#713]
### Description of the Problem ###

  - What triggers the problem? Not working
  - What happens? Nothing
  - What do you expect to happen instead? To work, please check [violentmonkey#274](https://github.com/violentmonkey/violentmonkey/issues/274)

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows 7 x64
  - **Web Browser (Firefox / Chrome / Other):** Firefox and Chrome
  - **Error Messages Displayed:**
  - **Screenshot of JavaScript Console:**
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

**Comment by Xaekai** [comment]
This was on my TODO anyway. I suppose I'll get to it sooner rather than later.

**Comment by Xaekai** [comment]
Well, when I alter the script to treat Violentmonkey the same as Tampermonkey in Firefox, it fails miserably at loading the needed data. So the insinuation that it's Tamper compatible that @gera2ld seemed to make appears to be false.

![image](https://user-images.githubusercontent.com/594255/32689223-27e6aff2-c695-11e7-82c1-91ab8032fb12.png)

Violentmonkey doesn't appear to support `GM_xmlhttpRequest` properly.

**Comment by Xaekai** [comment]
Hmm. Looks like it's getting the responseText block ok actually.
![image](https://user-images.githubusercontent.com/594255/32689290-89448c28-c696-11e7-98e3-a6fb65cb558a.png)

But that appears to be a redirect for Google login.

After logging into a Gmail in another tab then refreshing it works.

**Comment by Xaekai** [comment]
@calzoneman 

I think we are gonna have to start detecting if `accounts.google.com/ServiceLogin` is present in the response, and prompt the user in some fashion to log into their Gmail in another tab. This same problem presents on Chromium too.

But outside of that there is no issue treating Violentmonkey like Tampermonkey.

@KingThunder 
If you don't want to wait, you can just alter your copy of the script right now:
![image](https://user-images.githubusercontent.com/594255/32689333-6de7fd10-c697-11e7-84ac-28957fe47c45.png)

![image](https://user-images.githubusercontent.com/594255/32689335-7fc43058-c697-11e7-835d-3ec99ec2f71b.png)

![image](https://user-images.githubusercontent.com/594255/32689337-8e16b518-c697-11e7-9334-add7b26180ec.png)

**Comment by calzoneman** [comment]
>I think we are gonna have to start detecting if `accounts.google.com/ServiceLogin` is present in the response, and prompt the user in some fashion to log into their Gmail in another tab. This same problem presents on Chromium too.

Is this an issue with other script managers or only Violentmonkey?  Is Violentmonkey sending some funky headers or something that causes Drive to flag it as bot traffic?

Other than that question, I'm fine with adding additional error messaging to the user if there are known failure cases.

**Comment by Xaekai** [comment]
It happens with Tamper as well. It's what made me dig deeper.

**Comment by KingThunder** [comment]
When the script will be updated?

**Comment by KingThunder** [comment]
Created a pull request to support it, if that helps.

**Comment by Xaekai** [comment]
That's fine, I'll make a separate issue and PR for the Google login cookie issue.

I'd have gotten to this myself, but taking care of my elderly stepfather is consuming more and more of my time.

**Comment by calzoneman** [comment]
Moved discussion of the login issue to #718

**Comment by calzoneman** [comment]
Deployed to live.
