### ISSUE TITLE
New version of Firefox (57.0 64bit) Does not load Google Drive videos at all

### ISSUE THREAD

**Issue by Shaxio** [calzoneman/sync#714]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [X] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  - [X] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? 
Any google drive video playing (Yes the userscript is installed, this worked fine until the last firefox update)
  - What happens?
The video does not replace the last video displayed for anyone on Firefox
  - What do you expect to happen instead?
The video to display and replace the last video played

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):**
Windows 10 Pro version 1709
  - **Web Browser (Firefox / Chrome / Other):**
Firefox 56.0 with Greasemonkey 4.0 running Google Drive Video player version 1.3.0
  - **Error Messages Displayed:**
Nada
  - **Screenshot of JavaScript Console:**
https://puu.sh/yn29J/788dc80ba3.png
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

**Comment by calzoneman** [comment]
This looks related to Greasemonkey 4 being backwards-incompatible: https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

I've confirmed that Tampermonkey works fine on Firefox 57 (at least, the beta version of FF57 that I have); Greasemonkey will require some changes to get working again due to the above.

**Comment by calzoneman** [comment]
Can you check if it's working on https://beta.synchtube.me/ now?  You'll have to upgrade the script; a prompt will appear under the video on this site.

**Comment by Shaxio** [comment]
Userscript gotten from https://beta.synchtube.me/google_drive_userscript here
Channel was a temp channel
Video worked fine
did not upgrade Greasemonkey or change to tampermonkey

**Comment by Shaxio** [comment]
Confirmed tampermonkey works, Thanks!

**Comment by Xaekai** [comment]
I've gotten 5 people coming into my personal channel asking about this.

I'm reopening this issue until the fix is live on the main site.

**Comment by calzoneman** [comment]
This is live.
