### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by werthog2994** [calzoneman/sync#72]
I've noticed that a few of the rooms I'm going to get spammed with no end in sight. Banning has been ineffective so far, what do?

**Comment by calzoneman** [comment]
Which rooms?  If there's moderators there, have them find the culprits in the "Connection Log" tab and Ban Range on them.

Otherwise I'll come take care of it.  vidya4chan found out that this exists and some idiot kid's been going after channels all day.

**Comment by werthog2994** [comment]
Can't spam be dealt with without manually banning people? Like some sort of detection?

**Comment by calzoneman** [comment]
You can enable the "prevent chat flood" option to throttle people.  However, I'd rather not autoban people because automatic systems are prone to failure.

**Comment by werthog2994** [comment]
Chances are if someone's sending a 300 character message 20 times a second there is room to  increase detection a little

**Comment by ghost** [comment]
Dnsbl could block many already reported botnets and spammers.
http://www.projecthoneypot.org/

**Comment by calzoneman** [comment]
Today's attack appeared to be one guy who ported a synchtube spam script and posted it on v4c.  Judging by the IPs there weren't many people involved, but if it happens continually I'll look into it.
