### ISSUE TITLE
[Feature Request] Synchronize video position changes and video pausing

### ISSUE THREAD

**Issue by laurenzcodes** [calzoneman/sync#725]
When someone clicks on the pause button or skips forward in the video, it doesn't get synced with the rest of the channels users. I'd like this to be an option.

Thanks.

**Comment by calzoneman** [comment]
This is already supported. Click your name in the userlist and "give leader"

**Comment by laurenzcodes** [comment]
Thanks for the fast response. I was dumb for not checking the FAQ first.
