### ISSUE TITLE
Feature: Ability to unmute a disconnected user

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#728]
What it says on the tin.

Sometimes a moderator mutes / smutes someone who later disconnects, but the moderator didn't wish the mute to be permanent and doesn't want to stand by for that user to connect again to undo it.

**Comment by calzoneman** [comment]
As far as I can tell, this actually already works: https://github.com/calzoneman/sync/blob/3.0/src/channel/chat.js#L672-L685

It's just that it doesn't send the message telling you it worked unless the user is present.  But I'm fine with leaving this open to fix that messaging.
