### ISSUE TITLE
Connection Logs only visible by Channel Administrators and up

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#73]
I think that IPs are too important data to let regular moderators see them - that's my opinion, can we debate about that?

**Comment by calzoneman** [comment]
The easy way to do this would be to mask it clientside- this wouldn't make it impossible to find, but it would make it difficult for people who don't know Javascript.

I'll see what I can do, I was just trying to get something out quickly.

**Comment by calzoneman** [comment]
Rearranged how some of the stuff is done serverside so IPs aren't sent to non-siteadmins.
