### ISSUE TITLE
Tracking issue for imgur ban

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#732]
It looks like the imgur hotlink ban is back.  Opening an issue to track necessary work to handle that.

  1. Disallow new emotes to be created using imgur links (and come up with a plan for existing ones)
  2. ~~Detect and replace `.pic`-filter image embeds and replace imgur hotlinks with their "embed card"~~

**Update:** using the embed card is infeasible -- resizing the iframe doesn't work correctly, and the embed card requires JavaScript to embed (which also loads other tracking scripts).

**Timeline**

*2017-12-25*: imgur begins returning 403 for hotlinks with `cytu.be` in the referrer.

*2017-12-26*: support agent confirms the website is blocked from hotlinks

*2017-12-26*: hotlinks magically start working again

*2018-02-28 01:30 UTC*: imgur begins returning 403 again for hotlinks with `cytu.be` in the referrer.

**Problems**

| Feature | Approximate # of imgur images |
| -- | -- |
| Channel Inline JS | 1,704 |
| Channel MOTD | 2,303 |
| User Avatars | 5,058 |
| Channel Inline CSS | 6,335 |
| Chat Filters | 30,015 |
| Channel Emotes | 659,540 |

**Comment by calzoneman** [comment]
Rolling out the following clientside patch to stop people from adding Imgur emotes (and `<img>` tags in chat filter replacements):

```diff
diff --git a/www/js/data.js b/www/js/data.js
index e71bfeb..41d3469 100644
--- a/www/js/data.js
+++ b/www/js/data.js
@@ -196,6 +196,15 @@ var Rank = {
     Siteadmin: 255
 };
 
+var IMGUR_EMOTE_MSG = "Emotes and other channel content cannot be hosted" +
+                      " on Imgur due to Imgur" +
+                      " banning hotlinking from cytu.be.  Imgur's terms" +
+                      " of service prohibit '[using] Imgur to host image" +
+                      " libraries you link to from elsewhere, content for" +
+                      " your website, advertising, avatars, or anything" +
+                      " else that turns us into your content delivery" +
+                      " network.'";
+
 function createCookie(name,value,days) {
     if (days) {
         var date = new Date();
diff --git a/www/js/ui.js b/www/js/ui.js
index 52ba5b9..687138b 100644
--- a/www/js/ui.js
+++ b/www/js/ui.js
@@ -683,6 +683,17 @@ $("#cs-chatfilters-newsubmit").click(function () {
               "match.");
     }
 
+    if (/<img src=[^>]*?imgur\.com[^>]*?>/i.test(replace)) {
+        Callbacks.validationError({
+            target: "#cs-chatfilters-newreplace",
+            message: IMGUR_EMOTE_MSG
+        });
+
+        return;
+    } else {
+        Callbacks.validationPassed({ target: "#cs-emotes-newimage" });
+    }
+
     socket.emit("addFilter", {
         name: name,
         source: regex,
@@ -703,6 +714,17 @@ $("#cs-emotes-newsubmit").click(function () {
     var name = $("#cs-emotes-newname").val();
     var image = $("#cs-emotes-newimage").val();
 
+    if (/imgur\.com/i.test(image)) {
+        Callbacks.validationError({
+            target: "#cs-emotes-newimage",
+            message: IMGUR_EMOTE_MSG
+        });
+
+        return;
+    } else {
+        Callbacks.validationPassed({ target: "#cs-emotes-newimage" });
+    }
+
     socket.emit("updateEmote", {
         name: name,
         image: image,
```

Will work on serverside checks as well, but this can be rolled out without any downtime and stops the bleeding.

**Comment by Xaekai** [comment]
CyTube clone operators may raise issue if such things are not behind a config flag. Just a thought.

**Comment by calzoneman** [comment]
What gets deployed to CyTube's servers is a private fork that merges from this repository but contains a few minor site-specific tweaks (such as this, the Soundcloud API proxy, the support IRC link, etc.).

I don't plan on merging this into the public repo, although on the other hand even though others may not be big enough to attract attention, they are still violating Imgur's ToS presumably.

**Comment by CoolOppo** [comment]
Just so you know, the link in the alert on cytube to get to this issue is broken. I had to inspect the element to get here.

_Resolved._

**Comment by twilight-sparkle-irl** [comment]
It might be prudent just to have it so that it warns you but doesn't stop you, I have a proxy that just serves the imgur link going and I had to evade the filter.

**Comment by calzoneman** [comment]
Which filter are you referring to?

CyTube prevents you from adding imgur links as emotes because imgur have made it very clear in their communications with me that using imgur as a CDN is prohibited.  Channels must find other places to host their emotes.

**Comment by calzoneman** [comment]
Please don't evade the filter.  Intentionally evading filters put into place by the server is a bannable offense.

**Comment by Xaekai** [comment]
If you're running your own Imgur image caching proxy, the filter shouldn't stop you from using such links, as links similar to `https://your.proxy/imgur_image_ID` wouldn't trip it.

**Comment by sawwashere** [comment]
Would it be possible to add referrerpolicy=same-origin to allow the adding of imgur links. [Support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Browser_compatibility) isn't universal which may pose a challenge. AFAIK if the site operator isn't adding emotes, then it's just user-generated content and not the responsibility of the site owner/operator. IANAL

**Comment by calzoneman** [comment]
Imgur made it clear to me that this type of usage violates their terms of
service.

While it is user generated content and individual channels violating the
ToS, I am not interested in providing mechanisms that enable people to
violate other websites' terms of service.

Don't use imgur on CyTube nor attempt to circumvent the checks added to
prevent using imgur for emotes.

**Comment by sawwashere** [comment]
I understand and respect your position on this issue. But I feel I would be remiss if I failed to mention that setting referrerpolicy, while it may alleviate the imgur issue, has other privacy related benefits as well. I doubt this will sway your decision and I will say that the imgur ban is the primary reason for my involvement in this situation.
