### ISSUE TITLE
IPFS support

### ISSUE THREAD

**Issue by fusir** [calzoneman/sync#733]
I'd love to get a channel running IPFS.  That can be done in javascript but the playlist would have to support uploading empty urls, which would act as a token instructing the javascript where the file is.

**Comment by calzoneman** [comment]
Hi,

If you use an HTTP gateway for IPFS-hosted videos, they should just work with the existing support for self-hosted files (provided the video has an acceptable coding and HTTP `Content-Type` header).

If you mean supporting a native client for the IPFS DHT, their [javascript client](https://github.com/ipfs/js-ipfs) is in Alpha, so I'd rather not integrate with it now.
