### ISSUE TITLE
Change active poll answer at any time.

### ISSUE THREAD

**Issue by programnoir** [calzoneman/sync#736]
This isn't a bug, merely a feature request.

A friend has asked me to put in a feature request calling for unlocked poll answering, or better described as the ability to switch your poll answer (or clear it) before the poll ends. I'd also like to suggest an option in the channel settings to turn said answer locking on and off.

**Comment by calzoneman** [comment]
Users have always been able to change their vote by refreshing the page, which clears the old vote on disconnect, but I think it would be reasonable to allow changing votes while remaining on the page.

>I'd also like to suggest an option in the channel settings to turn said answer locking on and off.

Not sure why this would be desirable?  The current behavior was never meant to "lock users in" to their vote; it was just an arbitrary decision back when the feature was implemented.

**Comment by programnoir** [comment]
In my head I was imagining a possible scenario, but I think you're right. Ignore my suggestion, and thank you for considering my friend's request.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/d179cd896fc9bae0581f7e4f6610c9efe266ca10
