### ISSUE TITLE
Querystring is removing from direct url

### ISSUE THREAD

**Issue by seiya-git** [calzoneman/sync#738]
## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [+] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [+] Disabling all browser extensions
  - [+] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem?
  - What happens?
  - What do you expect to happen instead?

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows
  - **Web Browser (Firefox / Chrome / Other):** Firefox
  - **Error Messages Displayed:**
  - **Screenshot of JavaScript Console:**
  
When adding direct url, querystring is missing

**Comment by calzoneman** [comment]
Can you provide an example?  I just tried appending a querystring to a direct link and confirmed that once the video plays, the original querystring is present in the URL requested by my browser.

**Comment by seiya-git** [comment]
`https://cloclo17.datacloudmail.ru/weblink/media/240p_0_1/TFp6Uy8xcDR2aUhNTjEvUG9rJUMzJUE5bW9uJTIwLSUyMFMxMyUyMC0lMjBEUDE1OCUyMCU1QjEwODBwJTVEJTVCQU1aTiU1RCU1QkFUVEtDJTVEJTVCM0ZFMzYwQjYlNUQubWt2.m3u8?double_encode=1`

**Comment by calzoneman** [comment]
That's actually an HLS manifest, which is slightly different than a direct file link.  I can confirm that the querystring is being dropped for those, but that's not actually your problem: even when I fix that locally, the remote server is returning a 403:

```
» curl -iH 'Origin: https://cytu.be/r/test' 'https://cloclo17.datacloudmail.ru/videowl/0p/TFp6Uy8xcDR2aUhNTjEvUG9rJUMzJUE5bW9uJTIwLSUyMFMxMyUyMC0lMjBEUDE1OCUyMCU1QjEwODBwJTVEJTVCQU1aTiU1RCU1QkFUVEtDJTVEJTVCM0ZFMzYwQjYlNUQubWt2.m3u8?double_encode=1'
HTTP/1.1 403 Forbidden
Server: nginx/1.12.1
Date: Sat, 17 Mar 2018 17:46:39 GMT
Content-Type: application/octet-stream
Content-Length: 0
Connection: keep-alive
Keep-Alive: timeout=20
X-Trace: hQGP#KeSnA
X-Host: cloclo17.i
Strict-Transport-Security: max-age=31556926; includeSubDomains
X-XSS-Protection: 1; mode=block; report=https://cspreport.mail.ru/xxssprotection
X-Content-Type-Options: nosniff
```

So it looks like the host you are trying to use does not permit embedding on third-party websites.

**Comment by calzoneman** [comment]
(The querystring thing is fixed in https://github.com/calzoneman/sync/commit/304a6c9cfa15264f4247e46f2c65d3dbd2772e96 but doesn't resolve your problem)
