### ISSUE TITLE
Custom footer appearance fix

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#74]
Originally there is a gap between custom and normal footer, that doesn't look good.
Just move `<div id="sitefooter">` right below `<div class="push"></div>`
After that little change, it looks like that:
![image](https://f.cloud.github.com/assets/3297156/445442/32534c72-b1bc-11e2-88ef-d50edeef3077.png)

**Comment by calzoneman** [comment]
`#sitefooter` is below the `.push` by default: https://github.com/calzoneman/sync/blob/master/www/index.html#L268

Is there something else you changed?

**Comment by ghost** [comment]
For me it is:
`<div class="push"></div>
<div id="sitefooter">
</div>`

**Comment by calzoneman** [comment]
Yes, and that's what your original suggestion says: "move #sitefooter below .push". I suggest you check your suggestion for typos, because right now the code matches your suggested change.

**Comment by ghost** [comment]
There's one more `</div>` (line 269) below `<div class="push"></div>` in the repo's code. You can swap line 269 with line 270.
