### ISSUE TITLE
Found a rather disturbing channel the other day

### ISSUE THREAD

**Issue by TheLightOfDayOne** [calzoneman/sync#745]
**REMOVED (off topic --cal)**

**Comment by StormedJF** [comment]
By ignoring them.

**Comment by Xaekai** [comment]
1.) The sync repo is only for issues related to the software itself. Concerns such as these can be addressed in email or on the support IRC or support Discord.
2.) CyTube only hinders speech so far as the law requires within the jurisdictions the servers operate. Nothing in your screenshots violates any laws of Washington state or the USC.

**Comment by calzoneman** [comment]
The public GitHub tracker is not an appropriate place to discuss this.  This forum is for discussion of technical issues and features, not content administration.

There is a Contact page linked from the footer on the website.  Please email me for further comments.
