### ISSUE TITLE
Audio tracks in Google Drive 

### ISSUE THREAD

**Issue by ZenoNiQ** [calzoneman/sync#746]
Does any possibilities to change audio tracks in files?

**Comment by calzoneman** [comment]
When you upload a video to Google Drive, Drive transcodes it into a set of files of different sizes/qualities that are suitable for playing in a browser.  Each one of these can only have one audio track, so if your source file contains multiple audio tracks, Drive will pick one (I don't know how it decides).

If you have videos with multiple audio tracks and you want to ensure the correct one is used, you can process the file yourself before uploading it, using a tool such as ffmpeg or handbrake to produce a copy that only contains the desired audio track.
