### ISSUE TITLE
Okay what happened to Synchtu.be

### ISSUE THREAD

**Issue by CyrusTheAcceptable** [calzoneman/sync#748]
It's been down for over a week.

http://www.websitedown.info/synchtube.net

**Comment by calzoneman** [comment]
Synchtu.be is not directly affiliated with this project, other than that it
used this software.  I do not own it nor do I have administrative access.

My contact from synchtu.be has not responded to emails, and the IRC network
that was affiliated with it has also disappeared.

**Comment by CyrusTheAcceptable** [comment]
I see. Thank you
