### ISSUE TITLE
Initial userlist population quadratically sorts

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#749]
As brought to attention by Enzi on the Discord.

The list should be fully populated and then sorted once.

**Comment by calzoneman** [comment]
The particular sort implementation probably also ought to be reviewed as it is 5 year old cruft.

**Comment by calzoneman** [comment]
This has been deployed to https://beta.synchtube.me.

**Comment by calzoneman** [comment]
This has been deployed live.
