### ISSUE TITLE
Feature Request: Mixer Support

### ISSUE THREAD

**Issue by Gelmo** [calzoneman/sync#757]
Skipping the template since this is NOT an issue.

Does anyone else have interest in getting Mixer (the streaming platform) support in Sync? They offer embeds, which work great when posted from the embed tab. Would be great if we could get it to go automatically without needing to manually allow at the top, like with Twitch.

**Comment by calzoneman** [comment]
Just realized I forgot to comment on this.  Seems reasonable.

Merging https://github.com/calzoneman/sync/issues/576 into this.

**Comment by calzoneman** [comment]
API: https://dev.mixer.com/rest.html#channels

I don't have a Mixer account so I'll have to look into creating one to access their developer "lab"

**Comment by calzoneman** [comment]
This is available for testing on https://beta.synchtube.me/

**Comment by calzoneman** [comment]
This is now live.

**Comment by Gelmo** [comment]
Awesome! Thank you for spending time on this @calzoneman!
