### ISSUE TITLE
Add support for videos on rutube.ru

### ISSUE THREAD

**Issue by OddBloke** [calzoneman/sync#759]
Adding videos from rutube.ru is not currently supported, and it would be great if it were.

(Thanks for a great project!)

**Comment by henke37** [comment]
Cytube needs three things to add a new hosting service:
* An embedable player
* A way to control said player
* A API to fetch video titles and lengths

Please provide api documentation, in english, on these three items if you want the service added.

**Comment by OddBloke** [comment]
Hmm, the only API documentation I can find is http://rutube.ru/info/to_developers which is in (I assume) Russian. It's readable via Google Translate, but that's not a great basis for development.

**Comment by calzoneman** [comment]
The other thing to consider is how much demand there is and how much value adding it will realistically bring.

I did a quick back of the envelope calculation of channel playbacks over 24 hours; ~88% were YouTube, ~8% were Google Drive, ~2% were self-hosted, and the rest of the ~10 supported types of videos combined took up <2%.  Even if I farmed out the work to implement the support initially by accepting a pull request, that's still another provider I'd have to maintain for the foreseeable future (performing upgrades when necessary, providing support to users, etc.).  The last provider I added by user request, Streamable.com, had just 2 plays out of >20,000 CyTube videos in the last 24 hours, and I've spent more time fixing issues with that implementation than more popular providers.

A separate issue is whether the site will even be around for very long.  I added support for vid.me and the service shut down a little over a year later so I had to go back and remove it.

**Comment by Xaekai** [comment]
The separate issue seems non-applicable in this case, given RuTube has been [around since 2006](https://en.wikipedia.org/wiki/Rutube). I don't think it's gonna fly by night and then disappear. The API appears stable.

**Comment by kr4ssi** [comment]
I would appreciate this too

**Comment by Xaekai** [comment]
I have examined the API and did not find the necessary prerequisites to support this site. There is no way to directly acquire streamable mp4 links, and the iframe embed links they provide had no documented command passing for pause or seek.

If this changes in the future, feel free to reopen this issue.
