### ISSUE TITLE
[Feature Request] YouTube Live blocking not working

### ISSUE THREAD

**Issue by azumukupoe** [calzoneman/sync#766]
We need an option to deal with trolls.
It would help pretty much if you could do it.
Thank you!

**Comment by Xaekai** [comment]
There is already permission for this in channel settings.

**Comment by calzoneman** [comment]
I assume this ticket is reporting that that permission doesn't apply to
youtube, in which case this is actually a bug report.

**Comment by azumukupoe** [comment]
Actually, I didn't know that a setting existed.
Thanks for letting me know.

**Comment by calzoneman** [comment]
Confirmed fixed in latest deployment to cytu.be; for third party sites you'll have to bug the admin to merge the change.
