### ISSUE TITLE
An option to hide video

### ISSUE THREAD

**Issue by azumukupoe** [calzoneman/sync#769]
Audio only mode?

**Comment by calzoneman** [comment]
I'm not sure I quite understand the goal here.  With the exception of Soundcloud, all the other sources CyTube supports are video-based websites that don't offer an API for an audio-only stream.  You could try to write a script to cover up the video with a blank rectangle, but it'd still be downloading and rendering the video underneath that.

**Comment by azumukupoe** [comment]
Would be nice for saving data connection but if it's impossible it's okay

**Comment by Xaekai** [comment]
Your only real option there is to tell YouTube to use 240p if that's your primary playlist media source, which would save a significant amount of data, but would not eliminate the video data wastage.

**Comment by calzoneman** [comment]
Closing since avoiding loading the video from video websites is not doable with their existing APIs.
