### ISSUE TITLE
Undo skip?

### ISSUE THREAD

**Issue by azumukupoe** [calzoneman/sync#771]
Would be very nice because I sometimes press skip on accident

**Comment by Xaekai** [comment]
Yeah, this seems like a reasonable request.

In the meantime your can just do `/afk` twice.

**Comment by calzoneman** [comment]
Merging with #736 since voteskips are implemented as polls.

**Comment by calzoneman** [comment]
Although, I would also be interested in more information about how you "press skip on accident", because if that happens enough for it to be a problem, there's a deeper UI issue than just not being able to undo it once you've done it.

**Comment by azumukupoe** [comment]
My finger dances on my phone thats all
