### ISSUE TITLE
Play only voted videos from channel library

### ISSUE THREAD

**Issue by azumukupoe** [calzoneman/sync#773]
I want it to play only videos with more than ten upvotes. 
Is this a possible feature?

**Comment by calzoneman** [comment]
I'm not sure what you mean -- the channel library doesn't "play" anything, it just keeps a record of anything added to it that is searchable (currently, anything added without having "add as temporary" gets added, but I'd like to replace that with an explicit "add to library").

Also, CyTube has no concept of "likes".

**Comment by azumukupoe** [comment]
I mean voteup as of likes

**Comment by calzoneman** [comment]
CyTube does not have the concept of up- or down-voting videos, either.  So I'm really confused what you are actually referring to.

**Comment by azumukupoe** [comment]
is it only in cytube.xyz ?

**Comment by calzoneman** [comment]
I have not heard of this website before.  The software in this repository has been forked into many websites, with the only officially supported one being https://cytu.be.  Normally I don't mind when people fork and add their own features, but it is irritating that cytube.xyz stole the same name...

**Comment by azumukupoe** [comment]
Oh I thought this was the official Japanese server
you should contact the admin then 
admin@cytube.xyz

**Comment by calzoneman** [comment]
Closing since this feature request relates to a third-party feature.  Please reach out to the owners of forked repositories about features specific to those forks.
