### ISSUE TITLE
Updating CSS reprompts inline JS acceptance

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#779]
If you edit a channel's custom CSS and that channel has any inline JS the users get re-prompted to accept and execute said JS.

These frames should either be split, or a hash of the JS should be sent and compared to previous, and if the same the JS part is ignored. The latter is behavior I did in my own custom JS already, but I think other channels could benefit for this feature being in core.

**Comment by calzoneman** [comment]
I think the hash/checksum solution would be appropriate.  I might have time to work on this next week.
