### ISSUE TITLE
Add owner_last_seen column to channels table in ACP

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#786]
A lot of times we get requests for things such as rank promotion in channels where the original owner seems to have vanished. It would be nice to a way to quickly confirm the validity of such requests to ensure it's not a social engineering attack.

**Comment by calzoneman** [comment]
The channels table has owner_last_seen which I think is what you want for
what I think you're referring to

**Comment by calzoneman** [comment]
To expand a bit:

`last_loaded` was added in https://github.com/calzoneman/sync/commit/8f266ccd4428d1a76fbeb860c234a5066a0e3f4a to assist with resolving disputes around abandoned channels.  It is updated whenever the channel is loaded from the database.

`owner_last_seen` was added in https://github.com/calzoneman/sync/commit/9239c2d465d28828348f621f301f0b13f17452c3 to assist with resolving disputes around channels that remain active, but whose owners have disappeared.  It is updated whenever the channel owner joins the channel.

I think these are sufficient to resolve channel ownership disputes.  Feel free to reopen if not.

**Comment by Xaekai** [comment]
I will repurpose then. These columns should be present in the ACP.

**Comment by calzoneman** [comment]
I think you need to rename the title again.  These are channel-level columns, not account-level.
