### ISSUE TITLE
YouTube API change?

### ISSUE THREAD

**Issue by b4** [calzoneman/sync#792]
### System Information ###

  - **Operating System:** Ubuntu 16.04
  - **Node Version:** _v8.15.0_
  - **CyTube Version:** _v3.63.1_
  - **Error Messages Displayed:** Forbidden (when adding youtube video)

Hi, 

Any time I try to add a youtube video with a key that previously worked, and no changes aside from updating cytube...every attempt returns Forbidden.

Has there been a change to youtube's API?

I've tried going to the youtube API URL to re-follow the instructions to try and change the key ... except the entire interface has changed drastically.  Did the API increment a version again?

I've cleared out and reinstalled all node modules and did the build-server command.

**Comment by calzoneman** [comment]
Did your server's IP address change? YouTube keys are permissioned by IP
which you can whitelist from the API console

**Comment by b4** [comment]
Yes, my IP did change. I didn't know that was a thing. Thanks for the
pointer, i'll look that over when i get a chance

**Comment by b4** [comment]
I created a completely new project, new API key, and everything (as I can't find the IP restrictions page) and the same issue presents itself. What magical page am I missing?

**Comment by calzoneman** [comment]
Apparently they don't require you to restrict your API key by IP anymore, although you can still do this and the key shows a warning if you haven't done so.

To register an API key:

1. Go to https://console.developers.google.com/, create a new "project" (or choose an existing one)
2. Make sure the YouTube Data v3 API is "enabled" for your project: https://console.developers.google.com/apis/library/youtube.googleapis.com
3. Go to "Credentials" on the sidebar of https://console.developers.google.com/, click "Create credentials" and choose type "API key"
4. Optionally restrict the key, or just copy the key.

You can test your key like so:

```
$ export YOUTUBE_API_KEY="your key here"
$ curl "https://www.googleapis.com/youtube/v3/search?key=$YOUTUBE_API_KEY&part=id&maxResults=1&q=test+video&type=video"
{
 "kind": "youtube#searchListResponse",
 "etag": "\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/qxXalBgF7OxddF2n1i8bg3At2p8\"",
 "nextPageToken": "CAEQAA",
 "regionCode": "US",
 "pageInfo": {
  "totalResults": 1000000,
  "resultsPerPage": 1
 },
 "items": [
  {
   "kind": "youtube#searchResult",
   "etag": "\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/cvEhfQJOem9LxDWKxQPMCN9p7Cs\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "Bey4XXJAqS8"
   }
  }
 ]
}
```

It may take a few minutes before your key starts working.

**Comment by b4** [comment]
Key works fine in curl but not when adding a video via the web...is there a means of enabling further debugging so I can see what is returning Forbidden?

**Comment by calzoneman** [comment]
Have you double checked that there are no stray spaces or punctuation around the key in config.yaml?

Have you double checked that you restarted the process after changing the config file?

**Comment by b4** [comment]
Copy and pasted the key directly from the config file for the curl test.

Looks like one final restart has it all sorted. Restarted earlier but maybe I just didn't wait long enough after key recreation.

**Comment by b4** [comment]
Right. this is sorted. closing. thanks for the help.

**Comment by calzoneman** [comment]
I originally left it open because I think there is still something to be
fixed here which is to update the config.template.yaml comments so that it
matches what is required today.

Feel free to submit a PR if you'd like to do that.

**Comment by calzoneman** [comment]
Fixed instructions in https://github.com/calzoneman/sync/commit/66d81ffb22ebcb6257bb17d891983cc3bca8165e
