### ISSUE TITLE
HLS playback fails due to non-HTTPS link

### ISSUE THREAD

**Issue by refriedfood** [calzoneman/sync#798]
Let's say I setup an nginx rtmp server off unix and have it spit out a m3u8. How can I utilitize the site to play the stream in its own player without compromising the streams real IP, etc. Is this possible? If not is there an alternative?

Thanks.

**Comment by henke37** [comment]
There is no way to let clients connect to a server without revealing the address of the server to the client. At best you can give the clients the address of a middleman server that restreams the data.

**Comment by calzoneman** [comment]
Can you explain what you mean by "in its own player"?

>without compromising the streams real IP, etc.

As Henke mentioned, the stream server IP will always be exposed to clients.  CyTube isn't a streaming service, it can only embed streams hosted by 3rd parties.  The HLS support is provided so that users who wish to host a stream themselves can do so (e.g. by using nginx-rtmp) rather than having to use an officially supported provider like Twitch.

**Comment by refriedfood** [comment]
That answers my question about the ip, but more so I want to know how certain videos are using clappr js. I don't know how, even if I had a 3rd party host, I can embed a js script with css functionality. For instance, if I had a server and nginx running, spitting out an m3u8 to a apache page with the js, how can I embed that into the sites function (all source hiding aside)?

I hope that made sense.

**Comment by calzoneman** [comment]
>For instance, if I had a server and nginx running, spitting out an m3u8 to a apache page with the js

This doesn't make sense.  HLS uses m3u8 playlists as a manifest for the individual video segments in the stream.  It's just a pointer to MPEG-TS files, all the logic for playing them back is the responsibility of the HLS client.  CyTube uses a generic HLS player which goes to the M3U8 file you specify to pull the live video segments.  https://en.wikipedia.org/wiki/HTTP_Live_Streaming

If you want an *entirely custom video player* then you need to write and host the video player yourself and embed it as an iframe (all users will see an untrusted content warning), or else you need to fork CyTube and host your own modified copy which implements the player you want.

**Comment by refriedfood** [comment]
How doesn't that make sense? That's what I'm currently doing. I have nginx running in hls to split ts files, as you understand, and then they're sequenced in an m3u8 which is grabbed by a generic site on my apache server, using a clappr js. This isn't important as we're talking about the same thing. 

What is important is how you go about getting cytube to grab my m3u8 - as it doesn't. The latter which you wrote must mean that the default hls player I'm seeing on the site is using the sites own css for its design. That makes sense, what doesn't is why I'm not seeing anywhere to embed or even give it my own m3u8 or variables. Maybe this is on my end, I'll have to try another comp.

**Comment by calzoneman** [comment]
If you enter a URL ending in ".m3u8" in the add video box (the same one
used to add YouTube or other videos), it should be added to the playlist as
a Livestream. By default, it requires moderator permissions in the room to
add a Livestream. If there is a specific error you see when trying to add a
self-esteem HLS link, please paste it here and we can discuss what the
problem is.

**Comment by calzoneman** [comment]
Self-hosted link, not self-esteem. Dang autocorrect

**Comment by refriedfood** [comment]
@calzoneman 

> 429 Too Many Requests
> 
> The server has rejected your request for exceeding the configured rate limit. Please slow down and wait a while before trying again.

I receive this error using both firefox and chrome. Strangely it happens when I tried to log in with firefox v62, but it happens when I try to save channel config on chrome.

**Comment by calzoneman** [comment]
Can you clarify where the error appears?  Is it when you try to load the CyTube page?  Is it when you try to add the m3u8 file to the playlist?  Is it after the file is added to the playlist and you try to watch it?  A screenshot would be helpful.

>Strangely it happens when I tried to log in with firefox v62, but it happens when I try to save channel config on chrome.

Logins have a low rate limit due to historical abuse.  If you try to login multiple times within a minute, or if you are using a shared IP (e.g. a proxy or VPN), you are likely to encounter this limit.  I can't think of any situation in which saving channel configuration would cause a rate limit error.  Either way, that sounds unrelated to your question about HLS.  It may be better to take this discussion off of GitHub to email or IRC.

**Comment by refriedfood** [comment]
@calzoneman I receive the error when adding the m3u8 on chrome. I receive that error when I try to log in the very first time on firefox (i.e. I can't get in at all). I'm not using a vpn or proxy with either browser. I'm not sure what might be causing it. Going to try Pale Moon.

Pale moon (27.9.2 64b) works fine. I'm at a loss. But at least my questions have been answered!

**Comment by calzoneman** [comment]
>I receive the error when adding the m3u8 on chrome.

Can you send me the m3u8 link?  You can email cyzon@cytu.be if you don't want to share publicly on github.

**Comment by calzoneman** [comment]
Discussed via email.  There is a legit bug here, which is that plain HTTP links aren't rejected for HLS (but they will definitely fail to play in a browser).

HLS links should be validated and reject non-HTTPS links, with an explanation of why it's required.

**Comment by calzoneman** [comment]
Updating title and tagging as a bug
