### ISSUE TITLE
[feature request] Global Chat on Index Page

### ISSUE THREAD

**Issue by frobby** [calzoneman/sync#800]
How about an option to have a chat window on the main Channel Index page?

**Comment by calzoneman** [comment]
I didn't get a chance to respond to this earlier this week.

Can you explain a little more about why you're interested in this feature and what the purpose is?  My first thought is it's just going to end up being spammed with channel advertisements, emojis, and offensive slurs.

**Comment by calzoneman** [comment]
I haven't heard back in the past week.  I don't think I'm interested in moderating such a global chat, however, feel free to comment if I misunderstood the request.
