### ISSUE TITLE
[User Request] Direct URLs without file extension

### ISSUE THREAD

**Issue by clshtws** [calzoneman/sync#801]
Every so often I've come across this issue when adding videos to the queue. I have a video URL such as below, it does not end in a .mp4 extension:
"https://example.com/blahblah123"
When opening the URL in a regular browser, it plays normally. Adding the video through cytube however always gives the unsupported filetype error, despite the URL linking to a brower-compatible video. I can provide actual URL examples if requested.

**Comment by Xaekai** [comment]
you can prepend such URLs with `fi:` to inform the link parser to bypass it's check.

`fi:https://example.com/somevidURL`

**Comment by calzoneman** [comment]
To give some context, there are actually 2 checks for raw files:

1. The UI matches on the file extension as a fast-filter for links that are not direct links to videos.  The intention was to both prevent the server from making unnecessary requests that will ultimately fail, and also to provide an immediate feedback with a sensible error message for non-technical users -- "File must end in .mp4" is easier for an end-user to verify than whether the video server is setting the `Content-Type` header to `video/mp4`, and also avoids having people think that CyTube can magically pull embedded videos off of HTML pages (this is not me projecting onto the masses, this is an actual question that people were confused about on multiple occasions, and who can blame them?).
2. Once a URL is accepted, either by matching a supported extension, or by overriding with `fi:`, the server makes a request to that URL to validate that it is accessible and has an acceptable MIME type.

Unfortunately, (1) has become problematic over the years as dropping file extensions has been the hip new trend.  It'd probably be best to remove (1) entirely and attempt to improve the error messaging for (2) to suggest how to verify that it's actually a direct link and not a page embedding an iframe from somewhere else.

**Comment by MulverineX** [comment]
yes this would be very helpful, some urls just don't have extensions and it would be fantastic if they could be played

**Comment by calzoneman** [comment]
Closing since this is now deployed.
