### ISSUE TITLE
[User Suggestion] rclone support

### ISSUE THREAD

**Issue by MulverineX** [calzoneman/sync#803]
There is a fairly new library made that decrypts rclone based media from any source within the browser, I think this would be especially helpful for Google Drive based sharing.
https://github.com/FWeinb/rclone-js

**Comment by calzoneman** [comment]
I'm struggling to think of a reason you would want to do this besides copyright evasion, which is prohibited by the ToS.

**Comment by MulverineX** [comment]
It's for further security so users can't just grab the drive Link and give to others. That has happened in my community before and it was a huge mess.

**Comment by MulverineX** [comment]
It's not about evasion, I just don't want it to be easy for malicious people to take the videos and give them to others, besides, Google shouldn't be sniffing around my files in the first place

**Comment by Xaekai** [comment]
This is not feasible.

When you upload a video file that has been encoded with a codec that Google Drive, or any other video host for that matter, can decode it takes that video and reencodes multiple copies optimized for streaming at different resolutions (360 720 1080 etc) readily consumed by browsers. These copies are what actually gets streamed, not the original file.

If you upload some encrypted stream to Google Drive, it can not do this processing. Only the original encrypted contents can be acquired as-is. To be able to support playing such a file CyTube would have to act as an intermediate cache of the decoded stream, something we absolutely will not do.

**Comment by MulverineX** [comment]
Well at that point it's up to the sharer/provider of the file to have the original be as optimized as possible, and for a lot of people quality adjustment is a non issue as you're usually just doing cytube if you're going on cytube

**Comment by MulverineX** [comment]
The point is the intermediary cache is stored in the runtime of the client, so it doesn't even hurt the host

**Comment by MulverineX** [comment]
If you're saying intermediary cache for other resolutions well :up:

**Comment by calzoneman** [comment]
Hi,

Thank you for clarifying this feature request.  Even if you don't plan to abuse it to evade Content ID, it sounds like this would essentially be adding DRM to CyTube's player which is not something I would like to add.

As for "Google shouldn't be sniffing around my files in the first place", feel free to [host with different providers](https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#which-media-providers-are-supported), or [host the videos yourself](https://github.com/calzoneman/sync/blob/3.0/docs/custom-media.md).
