### ISSUE TITLE
Add support for Annotations Restored

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [calzoneman/sync#804]
While there's no official server for AR yet, https://github.com/afrmtbl/AnnotationsRestored should document the stuff needed for it to work, and it has the link to the archive server in the source. Perhaps it'd be possible to overlay onto the embed? This might be nice as an option.

**Comment by calzoneman** [comment]
Can you clarify what would be required from CyTube here?  According to the documentation, it appears to be a browser extension, in which case it should work on embedded videos independently of the embedding site's code.

**Comment by calzoneman** [comment]
Closing because it's not clear this is a request that requires work in this repository.  Feel free to reopen with a clearer description of the requested work.
