### ISSUE TITLE
[Feature Request] Playlist ordered by votes

### ISSUE THREAD

**Issue by Crydsch** [calzoneman/sync#805]
I´d be nice, if we could change a playlist to be ordered by user votes.
This would give users more power over the playlist, without allowing abuse (ex. moving items).

For example could permissions be: everyone can add items and vote, no one can move items.

- Give each item a vote counter
- Order playlist by votes first, then queue-time
- Each (logged-in / permissions?) user has 1 vote per item

Considerations:
- disable queue next?
- disable manuall movement / manuall vote-count manipulation?
- have vote-count start at 1 (since the adding user would upvote his items anyway)

**Comment by calzoneman** [comment]
Hi,

Thank you for submitting this feature request.

Have you considered accomplishing this by having a bot to track votes and move the playlist items accordingly?  I try to keep CyTube core pretty lean and provide the primitive operations (add/remove/move) that people can use to customize their channel for specific needs, rather than implement many different use cases directly into core.

**Comment by Crydsch** [comment]
Thanks for the fast reply. I get your point.
I like the idea with the bot.
I found nuclearace bot, but i´m not sure if i can use is to do this...

Is there an official api?
How could I show the current votes in the playlist? (items title maybe?)
Can i add buttons or do i have to use chat commands?

Another aproach could be an external client using a bot as interface kinda...
I´d really like to know your view on this.

**Comment by calzoneman** [comment]
I don't think any existing bots implement this functionality, but you could probably use one as a base to build it.

The "official" API is the websocket (socket.io) protocol used by the browser when communicating with the server.  Unfortunately, it's not really documented, but the existing bots and the source in this repo are a good start and I can answer questions about specific socket messages.

If you don't want to vote via chat commands, you would also need to set up some channel JS for your channel to modify the page (perhaps by communicating with the bot).

**Comment by Crydsch** [comment]
Thank you very much on your input!
I'll have a look at it and see where i can get

You can close this issue as its not really an issue regarding this repo

**Comment by Crydsch** [comment]
Turn out I can close it :P
