### ISSUE TITLE
Enhancement: Advance playlist when live youtube videos finish

### ISSUE THREAD

**Issue by CuckooRules** [calzoneman/sync#809]
### Description of the Problem ###

  - When the current media is a Live streaming youtube video
  - The playlist becomes stuck and does not advance to the next video automatically.
  - Advance the playlist when the video is completed.

**Comment by calzoneman** [comment]
Given quota constraints, and the fact there is no way (I know of) to be asynchronously notified that the stream is over, I don't think this is going to be implemented.
