### ISSUE TITLE
Make custom css on channel force usage of default (white) theme

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#81]
Default (white) theme is a base for most custom css. You can see what happens when you enable dark theme on channels with such approach here: http://synchtube.6irc.net/r/ponenyymit and here: http://synchtube.6irc.net/r/azjatube

**Comment by calzoneman** [comment]
I have decided to revert this behaviour.  It needlessly interferes with a user's theme choice on channels which have custom CSS but do not change the color scheme.

If you need this behaviour, add the following to your Javascript:

``` Javascript
$('#usertheme').remove();
```
