### ISSUE TITLE
failed to require() lib/main.js

### ISSUE THREAD

**Issue by is33** [calzoneman/sync#810]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [N/A ] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ N/A] Disabling all browser extensions
  - [ N/A] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? node index.js
  - What happens? output 

`FATAL: Failed to require() lib/main.js
Possible causes:
  * You haven't run `npm run build-server` to regenerate the runtime
  * You've upgraded node/npm and haven't rebuilt dependencies (try `npm rebuild` or `rm -rf node_modules && npm install`)
  * A dependency failed to install correctly (check the output of `npm install` next time)
TypeError: Cannot read property 'replace' of undefined
    at replace (/home/is33/sync/src/config.js:270:17)
    at Object.preprocessConfig [as load] (/home/is33/sync/src/config.js:176:5)
    at Object.load (/home/is33/sync/src/main.js:9:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
`
  - What do you expect to happen instead? The app to run

### System Information ###
  - **Operating System (Windows / Mac / Linux / Android / iOS): Ubuntu 18.04
  - **Web Browser (Firefox / Chrome / Other):** N/A
  - **Error Messages Displayed:** (see above)
  - **Screenshot of JavaScript Console:** N/A
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [ Y] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [Y ] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [ Y and reinstalled ] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem? node index.js
  - What happens? Crash/fail to include output
  - What do you expect to happen instead? app runs
  
### System Information ###

  - **Operating System:** ubuntu 18.04
  - **Node Version:** _(run `node -v`)_ 8.10.0
  - **CyTube Version:** _(displayed at startup)_ Not getting that far yet m8 lol
  - **Error Messages Displayed:**

**Comment by calzoneman** [comment]
Can you paste your `config.yaml` (you can replace any passwords or other sensitive values with 'xxxxxx' or a similar placeholder string)?

**Comment by is33** [comment]
Yeah, I'm actually about to go to bed. I will do it when I get some free
time tomorrow. Ty for taking the time to look over this.

**Comment by is33** [comment]
Attached below
[config.yaml.bak.txt](https://github.com/calzoneman/sync/files/3143361/config.yaml.bak.txt)

**Comment by is33** [comment]
Just as an update, I have tried using 0.0.0.0 for the binding IP address, same error

**Comment by is33** [comment]
I am closing this out. This was a full dumb error. 

Where you are defining the actual objects (e.x. binding http:) I was putting my stuff.
