### ISSUE TITLE
[suggestion] Milkdrop visuals for audio files

### ISSUE THREAD

**Issue by Dr-Flay** [calzoneman/sync#811]
Would it be possible to add Butterchurn?
It is a JScript WebGL implementation of Milkdrop 1 visualiser from Winamp.
If clients advance through the same presets at the same time, the "random" visuals will not be random as they will be generated from the same audio stream.
This is an active project with new presets added regularly.
https://github.com/jberg/butterchurn
To try a working copy visit https://webamp.org

**Comment by henke37** [comment]
Already made a general request in issue #534.

**Comment by calzoneman** [comment]
Thanks for providing the previous issue for context.

To expand upon the rather terse closing comment on that issue, my preference is to keep the core functionality limited and allow users to customize via userscripts/channel scripts.  To me, visualizations are not considered core functionality, but you can feel free to experiment with adding it as a customization.

**Comment by Dr-Flay** [comment]
Fair point
