### ISSUE TITLE
Shuffle Playlist shouldn't shuffle the currently playing item

### ISSUE THREAD

**Issue by Scritches** [calzoneman/sync#812]
When you click the 'Shuffle Playlist' button while a video is playing, that video is included in the shuffle - instead it should leave the currently playing video alone and shuffle the rest of the playlist.

**Comment by calzoneman** [comment]
I'm not sure I follow. Even when shuffling the same item continues playing
even though the list is reordered.

**Comment by calzoneman** [comment]
Apparently I remembered incorrectly and it does jump to a new video

**Comment by Scritches** [comment]
I could see about putting in a pull request to fix this behavior some time in the next couple days, if you like.
