### ISSUE TITLE
custom embed is missing the allow autoplay attribute in iframe tag

### ISSUE THREAD

**Issue by mrx1983** [calzoneman/sync#814]
### Description of the Problem ###

if you insert a custom embed, it gets included in cytube without the allow autoplay attribute.
i have found out that it makes a bit of a problem. even if one interacts with the frame, autoplay only works for a very short time and then it is forbidden again. i think autoplay is very strictly managed without an allow autoplay attribute in the iframe tag.

at the moment cytube includes a custom embed like this:
`<iframe src="XXX" frameborder="0" allowfullscreen="1" id="ytapiplayer" height="608" width="1080"></iframe>`

but it should better be like this:
`<iframe src="XXX" frameborder="0" allow="autoplay" allowfullscreen="1" id="ytapiplayer" height="608" width="1080"></iframe>`

so autoplay works as expected in this custom embeds.

**Comment by calzoneman** [comment]
Hi,

Can you cite where you found the recommendation to add `allow="autoplay"`?  The `allow` attribute is used to set the feature policy for the iframe, to allow/disallow certain APIs such as geolocation, but I can't find any reference in the HTML5 living standard about using it to control autoplay.

If you are using Chrome, you are likely being hit by https://developers.google.com/web/updates/2017/09/autoplay-policy-changes -- there's nothing I can do to work around that since it gets blocked at the browser level.

**Comment by mrx1983** [comment]
yes the site that you linked describes the autoplay policy, and that this attribute is needed for correct autoplay. adding it would let the browser autoplay content within the iframe.
i don't know if it is an html5 standard, but some browsers now refuse autoplay if this attribute is not present. i can also confirm that it not works correctly without attribute. i had build an embed and it refused to autoplay, it just paused it. when i added the autoplay parameter on the cytube iframe with the help of the console, it worked without problem. it is also mentioned on some player sites now, that this attribute is needed for autoplay.

https://faq.dailymotion.com/hc/en-us/articles/360000106708-Update-existing-manual-embed-iframes-to-allow-autoplay

https://www.radiantmediaplayer.com/blog/iframe-autoplay-policy.html

https://vimeo.zendesk.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos

it gets of course blocked on the browser level. but if the attribute is added to the generated iframe tag, then the browser knows that it is okay to allow autoplay with cytube on this iframe.
i think its some kind of safety feature, probably if sites are not happy if the iframes play something automatically. but i think cytube has nothing against it if autoplay is happening.
so if you generate the iframe tag with the allow autoplay attribute then it would work with autoplay.

**Comment by calzoneman** [comment]
Thanks for pointing that out; I don't think that was there the last time I had read that Chrome announcement.

I don't see any harm in trying `allow="autoplay"`, although I can't guarantee results.  Is that something you'd be interested in submitting a pull request for?

**Comment by mrx1983** [comment]
i maybe sound dumb, but what is a pull request? i'm not that often here on github, i have an account to make comments but other then that, i have no idea how i can pull requests etc.
but it would be really awesome if you could include this change, it would help me a lot.
at the moment i build on a little javascript driven site, which allows to generate a list of videos and one can use it as standalone, and the other thing would be to run it with cytube. so generating and including it in cytube. since many people of my fandom really like cytube, i thought that would be a great idea.
i have also made a video that shows how it works, and how the allow attribute affects its function.
http://sendvid.com/fltjx385
if the countdown is a bit smaller it also works somehow, but if its to long after the button press, it just refuses to play, at least if the frame not has this attribute. must be some crazy google magic.

**Comment by calzoneman** [comment]
Pull requests are how you can propose changes by submitting code to this repository -- see https://help.github.com/en/articles/about-pull-requests

**Comment by mrx1983** [comment]
i done it now, hopefully correct. i forked it and added the change and then
pulled it. oh well, this is all new stuff to me XD

**Comment by calzoneman** [comment]
Closing via #816

**Comment by mrx1983** [comment]
hopefully it was the correct file that i fixed. it was the only file that looked like it generates the custom iframe.
