### ISSUE TITLE
failed to build-player script

### ISSUE THREAD

**Issue by VillainXII** [calzoneman/sync#817]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [ ] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ ] Disabling all browser extensions
  - [ ] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem?
  - What happens?
  - What do you expect to happen instead?

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):**
  - **Web Browser (Firefox / Chrome / Other):**
  - **Error Messages Displayed:**
  - **Screenshot of JavaScript Console:**
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [ ] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [ ] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [ ] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem?
  - What happens?
  - What do you expect to happen instead?
  
### System Information ###

  - **Operating System:**
  - **Node Version:** _(run `node -v`)_
  - **CyTube Version:** _(displayed at startup)_
  - **Error Messages Displayed:**

**Comment by calzoneman** [comment]
Please fill out the details of the problem you're having, otherwise I can't help you.
