### ISSUE TITLE
SQL Error on Channel Creation

### ISSUE THREAD

**Issue by DryWood** [calzoneman/sync#822]
Hello,

I have deployed Cytube to a Ubuntu Server 19.04 VM. Using a separate VM (192.x.x.12) that hosts my mysql server 8.0.16. Connection from Cytube VM to SQL VM works as intended for most operations. 

All initial tables are generated upon launch and 

User generation works as intended.

## Server Problem ##

  - [x] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [x] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [x] Restarted the server
  
### Description of the Problem ###

When I try to create a Channel I receive this error : ![chrome_Fb1mhAJq4E](https://user-images.githubusercontent.com/43630241/62345746-15405d80-b4b9-11e9-8779-53c56e8083df.png) 

Console Error : ![chrome_krrJWFkYPC](https://user-images.githubusercontent.com/43630241/62345748-15405d80-b4b9-11e9-98a7-d7106a442c2d.png)
`
[ERROR] database: Legacy DB query failed. Query: INSERT INTO 'channel_ranks' VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE rank=?, Substitutions: ["UserName",5,"ChannelName",5], Error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank=5' at line 1.
`

In the MySQL Server, the `channel_ranks` table contains no info : ![RDCMan_hAYbcpPcHk](https://user-images.githubusercontent.com/43630241/62345750-15405d80-b4b9-11e9-9c95-5dc4cfa3a9dc.png)

On page refresh, you can see that it does create the channel (test2) : ![chrome_h8PoNJ8AkD](https://user-images.githubusercontent.com/43630241/62345747-15405d80-b4b9-11e9-89d2-f190b6bf35ef.png)

The channel is also created in the Channel Table in MySQL. : ![RDCMan_M4MOn29IyV](https://user-images.githubusercontent.com/43630241/62345753-15d8f400-b4b9-11e9-9da9-4d42d8a20570.png)

But once you enter the channel. as the creator, my user does not have Channel Admin authority : ![chrome_yFvoIoCP9y](https://user-images.githubusercontent.com/43630241/62345749-15405d80-b4b9-11e9-94c4-259e9a0cbf11.png)

### System Information ###

  - **Operating System: __Ubuntu Server 19.04__**
  - **Node Version:** __12.7.0__
  - **CyTube Version:** __3.66.0__
  - **MySQL Version:** __8.0.16__**

![RDCMan_Hr0eK2Y7uc](https://user-images.githubusercontent.com/43630241/62345751-15d8f400-b4b9-11e9-9645-d35adbf0e4b6.png)
![RDCMan_iAGfBddYvG](https://user-images.githubusercontent.com/43630241/62345752-15d8f400-b4b9-11e9-89b1-8f5947f282bd.png)
![RDCMan_qgCTu8pSme](https://user-images.githubusercontent.com/43630241/62345754-15d8f400-b4b9-11e9-9777-f990b9e1e05c.png)

**Comment by calzoneman** [comment]
I actually see the problem here: the `ON DUPLICATE KEY` references a column called `rank`, but `rank` is a reserved word in MySQL 8 (specifically, the name of a window function).

Changing this line to explicitly quote the column name in backticks should fix it: https://github.com/calzoneman/sync/blob/08f9feef7479c09e932377b57409ce2e5ce76fe2/src/database/channels.js#L381
