### ISSUE TITLE
Global Pause / Resume Button

### ISSUE THREAD

**Issue by Saladoc** [calzoneman/sync#825]
I have begun hosting my own instance on my server and for now it works like a charm. However, I'm really missing an ability for anyone with a given permission to pause and unpause the video.

So my suggestion is: Add a pause/resume button to the UI that will explicitly tell the server to pause the video. It can be rendered meaningless if there currently is a leader, but it would be a nice touch to enable pausing. I understand the problem with unintentional vs intentional seeking and the distinction thereof, but pausing can guaranteed to be intentional if it is done via a separate button.

**Comment by Xaekai** [comment]
You can set the permission for "setLeader" to registered users instead of moderator.

If you'd like a simple solution, this is what I use in my channel JS.

```js

    /*!
    **|   Simplied Leader
    **@
    */
    void (()=>{
        if(CHANNEL.perms.leaderctl > CLIENT.rank){ return }

        $("<button>")
            .prop("id","leader")
            .attr("title","Control current time of media")
            .addClass("btn btn-sm btn-default")
            //.text("Seek Control ")
            .append($("<span>").addClass("glyphicon glyphicon-transfer"))
            .insertAfter($("#qlockbtn"))
            .on("click", function(){
                if(CLIENT.leader){
                    socket.emit("assignLeader", { name: "" });
                } else {
                    socket.emit("assignLeader", { name: CLIENT.name });
                }
            })
            ;
        socket.on("setLeader", function(name){ 
            if(name === CLIENT.name){
                $("#leader").removeClass("btn-default").addClass("btn-warning")
            } else {
                $("#leader").addClass("btn-default").removeClass("btn-warning")
            }
        })
    })();

```

**Comment by calzoneman** [comment]
It's not just an issue of imprecision (it's actually not as hard to detect legitimate pauses as it is for seeks), but in public channels and/or channels with more than a handful of users it becomes anarchy with people fighting over the pause button to troll other people (this is already an issue with voteskips).

It might be possible to make it a configurable option -- really the next version of CyTube should allow you to pick what kind of channel you have and use that to drive more sensible defaults, given the preferences for public channels/large channels is different from people just wanting to use it to share with 1 other person.
