### ISSUE TITLE
Unable to view Google Drive Videos through Cytube

### ISSUE THREAD

**Issue by DiegoFleitas** [calzoneman/sync#826]
## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [Yes] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [Yes] Disabling all browser extensions
  - [No idea how to check this] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? Using Firefox Developer Edition
  - What happens? Videos posted to Google Drive return "The media could not be loaded, either because the server or network failed or because the format is not supported." instead of playing
  - What do you expect to happen instead? Play the video

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows 10
  - **Web Browser (Firefox / Chrome / Other):** Firefox Developer 70.0b4 (64-bit)
  - **Error Messages Displayed:** The media could not be loaded, either because the server or network failed or because the format is not supported.
  - **Screenshot of JavaScript Console:** 
![firefox_qqet4rOeKX](https://user-images.githubusercontent.com/15369935/64471331-c07eab00-d126-11e9-88fe-b9f591c29572.png)

  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

**Comment by calzoneman** [comment]
Please follow the troubleshooting steps on https://github.com/calzoneman/sync/wiki/Google-Drive-Userscript-Installation-Guide#troubleshooting

If that doesn't work, you're SOL.

**Comment by DiegoFleitas** [comment]
Yeah tried again with the same result, seems like Google is not authorizing the request for some reason, I get a 302 response on Chrome with the Location to the video but on Firefox I just get a 403.
Even with  [https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=devtools-netmonitor&utm_campaign=default](tracking protection)  disabled

I found out a cookie is sent on Firefox while on Chrome its not and also the request Headers differ, but I don't really know how to approach this but I guess its not worth the effort

**Comment by calzoneman** [comment]
Outside of tracking protection, did you also enable 3rd party cookies (the UI may not exactly match the screenshot from that wiki)?

I also generally recommend users troubleshoot this type of problem by disabling all browser extensions and re-enabling them 1 by 1 until you find which one is breaking it.  Generally it is some kind of privacy/adblocking extension.

However, my overall recommendation would be not to use Google Drive at all on CyTube.

**Comment by DiegoFleitas** [comment]
Its working now, tested on https://cytu.be/r/Think . I must have done something wrong the first time, toggling off the tracking protecting on cytube fixes it.

![image](https://user-images.githubusercontent.com/15369935/64480355-60c2e700-d19c-11e9-8518-1b0cf6a07879.png)

- I removed all the site cookies
- added an exception for tracking protection on cytube (toggling it back on reproduces this problem)

I also use Ublock Origin and it's active but doesn't seem to be interfering with it. 
Thanks for your help and developing this amazing project my dude, I like it a whole lot
