### ISSUE TITLE
Chat timestamp is off

### ISSUE THREAD

**Issue by Xars1** [calzoneman/sync#827]
The timestamp on messages in the chat are off by about 2 minutes.
![time](https://user-images.githubusercontent.com/49294535/64480487-85b45b80-d196-11e9-9cd7-8f43b3dcf02b.png)

Checked this on several channels, and it's consistently about 2 minutes off from real time.

**Comment by calzoneman** [comment]
Note this is not an issue with the code but rather the clock on one of cytu.be's servers, which has been corrected.
