### ISSUE TITLE
Allow custom metadata on video which gets sent to clients

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [calzoneman/sync#828]
Okay, so, I was trying to set something dumb up so that if a video needed some specific thing to look right, I could just add it to the queue as, say
> https:/\/video.com/vid?id=funny#[url parameters]

Unfortunately, I quickly realized that this wouldn't even work on providers that didn't give the raw URL as mediaId. 

So, it'd be nice if there was some dumb way for me to tag videos with custom metadata so I didn't have to deal with any of this. I dunno, have a "advanced mode" button in the options menu.

**Comment by calzoneman** [comment]
>if a video needed some specific thing to look right

I don't follow, how does adding extra metadata solve this given that CyTube's player doesn't know how to do anything with the extra metadata?  Can you give an example?

**Comment by henke37** [comment]
When I needed to attach data for my own purposes I just setup a mapping between the video id and the url of the data I add.

**Comment by twilight-sparkle-irl** [comment]
@calzoneman It'd be for any userscripts or CSS on the page, not cytube itself

@henke37 That's what I'm currently doing, but it's a bit of a pain.

**Comment by calzoneman** [comment]
Can you provide a concrete example of exactly what you're trying to pass through?
