### ISSUE TITLE
Error when trying to load in twitch vlogs

### ISSUE THREAD

**Issue by KanchiMoe** [calzoneman/sync#830]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [X] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [X] Disabling all browser extensions
  - [X] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? - when trying to add a twitch vlog, such as `https://www.twitch.tv/videos/481487919` for example, it throws up an error unable to add it. 
  - What happens? - It throws an error, listed below.
  - What do you expect to happen instead? - it should add and then play the video. It did work in the past but Twitch must have changed something which causes it to fail.

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows
  - **Web Browser (Firefox / Chrome / Other):** Firefox 69.0.1
  - **Error Messages Displayed:** Error Cannot read property 'length' of undefined

**Comment by calzoneman** [comment]
Looks like Twitch deprecated the version of the API that CyTube depended on; need to migrate to v5 - https://dev.twitch.tv/docs/v5/guides/migration

**Comment by calzoneman** [comment]
Easy fix: https://github.com/CyTube/mediaquery/commit/724e228e5dcafa9cb2bdc1644ac2d8ec4a4baac6

Need to deploy (have some stacked up changes anyways)

**Comment by calzoneman** [comment]
Confirmed above test case now works on https://beta.synchtube.me, looking into updating live servers.
