### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#833]
`knex` has a security advisory; it's only relevant to MSSQL (which CyTube doesn't support) but probably wise to upgrade anyways.  https://github.com/knex/knex/blob/master/UPGRADING.md lists some things that may break across versions.

Other deps probably need upgrades as well

**Comment by calzoneman** [comment]
Knex upgraded in https://github.com/calzoneman/sync/commit/40b5a0fe83b0b829a2b587e1feb40b933c11c7a5

**Comment by Olie440** [comment]
Have you tried Greenkeeper?

**Comment by calzoneman** [comment]
I don't know what that is so I suppose I haven't tried it.

**Comment by Xaekai** [comment]
Greenkeeper is a github bot that opens issues to inform you that there are npm dependencies you may upgrade. It checks package.json against npm. For packages that are already in range for the versions allowed in the package.json, it opens new branches on your repo, waits on ci testing for that branch. If it passes, it just deletes that branch, if it fails the bot opens an issue. **For out of range packages it opens a PR**, and the ci testing gets done there.

That last part makes it seem like it would initially be very noisy. But perhaps it would be worth considering.

**Comment by calzoneman** [comment]
That does seem theoretically useful, I'm a little skeptical that it requires granting write access to the repo though:

![screenshot-2019-12-05_19-50-52](https://user-images.githubusercontent.com/385672/70294517-9c1f8280-1798-11ea-9096-ef100f8cde44.png)

**Comment by Olie440** [comment]
I have a folk so I could test it on that?

**Comment by Xaekai** [comment]
Ahaha. It was wise not to [spend effort on that](https://greenkeeper.io/).
