### ISSUE TITLE
[Bug] Google Drive Video Controls

### ISSUE THREAD

**Issue by BiatuAutMiahn** [calzoneman/sync#834]
## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [True] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [True] Disabling all browser extensions
  - [True] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem?
Nothing specific. Play the video after the userscript is installed.
  - What happens?
Pause after play does not pause the video, after the sync point the video is played again. Seeking does not work either. After the 2 second default the video seek resets back to where it was normally playing. Even is only one player is connected.
  - What do you expect to happen instead?
Pause should pause the video, seek should set the position, THEN the player's state should propagate to other players.

### System Information ###

  - Windows v10.0.18362.10024
  - Chrome v78.0.3904.70 (Official Build) (64-bit)
  -None
  -Nothing in response to player controls interaction.

**Comment by calzoneman** [comment]
Please read https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#how-do-i-pause-or-seek-the-video and then see whether this answers your question.

**Comment by BiatuAutMiahn** [comment]
lol, ty

**Comment by BiatuAutMiahn** [comment]
Can you implement enabling multiple leaders? or allow multiple users to control the playback?

**Comment by calzoneman** [comment]
You could open a feature request issue, but it's unlikely to be worked on
anytime soon so I'd recommend finding another way around it.
