### ISSUE TITLE
Requesting Write access

### ISSUE THREAD

**Issue by Olie440** [calzoneman/sync#838]
I would like to make a PR

**Comment by Xaekai** [comment]
You shouldn't need special permissions to make a PR. You just do it, and then calzoneman can examine your code for suitability, and if it's acceptable, allow the PR to proceed.

**Comment by calzoneman** [comment]
Hi,

You don't need to have write permission in the target repository to open a pull request.  You can push the changes in your own fork and then GitHub provides a button to compare and open a pull request in the upstream repository.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
