### ISSUE TITLE
[Suggestion/Question] Audio Only

### ISSUE THREAD

**Issue by seniorm0ment** [calzoneman/sync#841]
I was wondering if there was a way to have it do audio only, just hide the video for lower resource usage. If not I am suggesting it.

Also on a sidenote, I couldn't figure out how to get the video to sync with other users. I see in the wiki it says there's a button that synchronizes the video, but I don't see that button? When I skipped a video it didn't skip to my other users. Would appreciate the help, thanks!

**Comment by calzoneman** [comment]
>I was wondering if there was a way to have it do audio only, just hide the video for lower resource usage. If not I am suggesting it.

This would depend on each individual video service to implement this functionality into their embed player.  For example, you would need to ask YouTube to add support for this (in my experience, they will probably not do it).

>I couldn't figure out how to get the video to sync with other users

The video is synchronized automatically based on a timer run by the server, so all clients are synchronized to the same server-defined timestamp -- there is no manual sync button.  Can you please link the wiki that described the manual sync button?

>When I skipped a video it didn't skip to my other users. 

Can you describe how you initiated the skip?  There is a voteskip button below the video, but that does not immediately skip the video, it requires a majority vote (depending on the settings in place by the channel owner).  Mods can skip a video by clicking "Play" on the desired item in the playlist.

**Comment by seniorm0ment** [comment]
@calzoneman 
>Can you please link the wiki that described the manual sync button?

"Synchronize video playback
This checkbox controls whether or not your video will be synchronized with the server."
https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide

>Can you describe how you initiated the skip? There is a voteskip button below the video

I should've been more clear by what I meant by skip, sorry. I meant if I skipped to a certain part in a video, it didn't move the other users to that part (Watch2gether can achieve this)

>Audio Only | This would depend on each individual video service to implement this functionality into their embed player. For example, you would need to ask YouTube to add support for this (in my experience, they will probably not do it)

Not too familiar with how this stuff works, but is it not possible to fetch the video but just have the video itself not show and just have the audio play? I know it's possible for yt-dl to extract audio only.

**Comment by calzoneman** [comment]
By default the server controls the synchronization.  If you wish to manually pause or seek the video, you can follow the instructions here: https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#how-do-i-pause-or-seek-the-video

>Not too familiar with how this stuff works, but is it not possible to fetch the video but just have the video itself not show and just have the audio play? I know it's possible for yt-dl to extract audio only.

youtube-dl bypasses YouTube's official APIs and relies on undocumented internal workings to achieve this.  The officially supported YouTube embed API does not support audio-only functionality: https://developers.google.com/youtube/iframe_api_reference.  Again, you could ask them to support this, but I highly doubt they will do it.
