### ISSUE TITLE
Playlist Randomizer Option.

### ISSUE THREAD

**Issue by Bj007pro** [calzoneman/sync#844]
As much as I like the shuffle option in media players, I would prefer if there was a playlist randomizer option. What this option would do, just like it does in media players that have the option, would list the videos in a randomized order.

**Comment by calzoneman** [comment]
There is a button for this below the video, with this icon: 

![screenshot-2020-01-29_17-41-54](https://user-images.githubusercontent.com/385672/73412918-1236f600-42bf-11ea-9e80-672e23f97a63.png)

Clicking this button will randomize the position of each item in the playlist.
