### ISSUE TITLE
The socket.io library could not be loaded

### ISSUE THREAD

**Issue by AmadeusTrill** [calzoneman/sync#847]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [ ✔️] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ ✔️] Disabling all browser extensions
  - [✔️ ] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? Going to channel
  - What happens? The error at the following paste https://hastebin.com/gikosuxute.coffeescript
  - What do you expect to happen instead? Channel to work as normal
not using any browser extensions or antivirus

### System Information ###

  - **Docker on Linux**
  - **Chrome**
  - **https://hastebin.com/gikosuxute.coffeescript**
  - **https://i.ibb.co/f4bN8LL/error.png**
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [ ] Run `npm run build-server` to regenerate `lib/` from `src/`: Happens every time container is rebooted
  - [ ] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies: entire container is rebuilt at every reboot
  - [ ] Restarted the server: yes
  
### Description of the Problem ###

  - What triggers the problem? Going to channel link
  - What happens? error stated above
  - What do you expect to happen instead? channel to function
  
Looking for advice on how to set up the io section essentially, registering logging in and creating channels is all working. I am behind a reverse proxy if that helps at all.

**Comment by calzoneman** [comment]
Please explain what you have already tried to troubleshoot the problem.

**Comment by calzoneman** [comment]
For reverse proxying HTTPS, you can refer to the examples on https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#appendix-a-example-config-using-nginx-with-ssl

For reverse proxying socket.io, I don't do this on my instances (it's just extra overhead copying sockets from one process to another), so I don't have advice on how to configure it.  If you find a way to do it, updating the wiki with an example (and if necessary, contributing a patch to fix any missing functionality) would be appreciated.

**Comment by calzoneman** [comment]
I added an FAQ because this has come up before and it's now been several years and the crappiness of config.yaml still hasn't been fixed.  This might help you understand why it's not working:

https://github.com/calzoneman/sync/wiki/Server-Hosting-FAQ#why-do-i-get-an-error-loading-socketio-when-i-use-a-reverse-proxy-for-https

**Comment by calzoneman** [comment]
I'm resolving this question since I haven't heard back in a couple days.  If you need further clarification, feel free to comment and I can reopen it.
