### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by Aersaud** [calzoneman/sync#848]
Good Evening,

I have been working on a docker image for this project. I have compiled it successfully into a container/Dockerfile and using docker-compose currently have a live production version in use with mariadb. I will be testing this further with my buddies that have been looking for a rabb.it substitute since it went downhill. This seems to be a good alternative. 

I would like to contribute the image once I sanitize it and set up some more env variables to allow customization. I will upload it to my github once that has been done. 

I am not sure if this is the proper way to get in contact with you but it seemed the easiest. I appreciate all your time that has been devoted to this project.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by calzoneman** [comment]
Hi,

About once a year someone comes along and starts a Docker image and then they usually get bored and abandon it: https://github.com/CyTube/cytube-docker

You are welcome to submit a pull request in that repository to submit an updated image; if it's something that you want to continue updating going forward we can discuss further.  I'll provide the same support I provided the previous authors: I can review pull requests and publish to the dockerhub integration (which I think is blank at the moment?), but I probably can't promise to keep the image updated myself since I don't use it in production.

Previous discussion: #774

**Comment by Aersaud** [comment]
Thanks for replying. I did see that repo, honestly I built this one completely different it clones the entire repo and then builds from that. With the current set up I have you must mount your own config file and certs into their directory. I believe this will keep it more future proof since it is not reliant on one specific commit. The mysql container is creating a volume at ./mysql for data retention and using enviroment variables to connect with the config from sync. It was actually fairly simple to set up. I would need some help testing it to verify if it will indeed work universally or if it was just specific to my use case. It is much easier to separate the containers and have docker-compose handle them rather than trying to build an all in one container in my opinion.

**Comment by calzoneman** [comment]
You can still PR it in that repo if you want, like I said I don't think anyone is using it right now so if there's a simple way to get it working equivalently to a standard install that may be better for future people looking to use it.

**Comment by Aersaud** [comment]
I apologize I am not very familiar with how to do that, I normally do not use github too much. Here is a link to the repo if you want to take a look: [https://github.com/Aersaud/sync-docker-compose](https://github.com/Aersaud/sync-docker-compose)


yes I copy and pasted everything and then sanitized :laughing:

**Comment by calzoneman** [comment]
GitHub has guides about how to submit pull requests that you can follow: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by Aersaud** [comment]
I have submitted the pull request.

**Comment by calzoneman** [comment]
I'm going to close this issue in this repo because the relevant conversation is happening at https://github.com/CyTube/cytube-docker/pull/3
