### ISSUE TITLE
error.log needs datestamps

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#85]
trying to get the server running on a test environment and as I was running through logs, I noticed that the error.log and sys.log have time stamps but not date stamps.

**Comment by calzoneman** [comment]
Hmm yes, that's a good idea.  I might just make it print the date when it changes though.

**Comment by coconono** [comment]
I would prefer time with the date or starting new logs daily.

daily would be nice so I can purge logs from time to time.
