### ISSUE TITLE
NOT PLAYING FREE YOUTUBE MOVIE

### ISSUE THREAD

**Issue by antonpictures** [calzoneman/sync#850]
- What triggers the problem?
NOT PLAYING FREE YOUTUBE MOVIE

  - What happens?
SEE SCREENSHOT
  - What do you expect to happen instead?
  TO PLAY THE FILM
![Screen Shot 2020-03-27 at 4 51 16 PM](https://user-images.githubusercontent.com/4306109/77809584-8555b200-704d-11ea-8f8c-520a9869641c.png)
GREAT CODE THANK YOU
![Screen Shot 2020-03-27 at 5 04 56 PM](https://user-images.githubusercontent.com/4306109/77809586-88e93900-704d-11ea-86aa-9280ce214fa8.png)

**Comment by calzoneman** [comment]
Please avoid typing in all caps lock.

From the screenshots you linked, you are having the same issue on OpenTogetherTube so I don't think this is a CyTube specific problem.

One issue certain users have been having recently is with certain AdBlock extensions causing problems for YouTube's embedded player, so I recommend to try disabling that: https://github.com/calzoneman/sync/wiki/Troubleshooting-common-issues-in-the-browser#youtube-player-shows-an-error-occurred-please-try-again-later

**Comment by antonpictures** [comment]
Sorry for the caps. Thank you for writing the code!
