### ISSUE TITLE
Problematic z-index on div#needpw

### ISSUE THREAD

**Issue by rnkn** [calzoneman/sync#852]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  - [x] Using a clean channel with no customizations
  
### Description of the Problem ###

- What triggers the problem?
Opening a channel requiring a password on a small screen (e.g. phone).

- What happens?
The password prompt appears behind the guest login name box.

- What do you expect to happen instead?
The password prompt appears above the guest login name box.

The issue seems to be because the `div#needpw` element has an element style including `z-index: auto` overriding its CSS `z-index: 9999`.

<img width="317" alt="Screen Shot 2020-03-29 at 9 33 32 pm" src="https://user-images.githubusercontent.com/1256849/77848090-8af5f800-7205-11ea-9eee-791897c9e307.png">

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):**
iOS / macOS (with responsive design mode)
  - **Web Browser (Firefox / Chrome / Other):**
Safari

**Comment by Xaekai** [comment]
Yeah, given the purpose of the chan pass request box and how it stops loading until provided, it's z-index should probably be inlined. I'll get this done shortly.

**Comment by Xaekai** [comment]
Strange this didn't autoclose. Resolved by #853
