### ISSUE TITLE
How to embed the youtube 

### ISSUE THREAD

**Issue by antonpictures** [calzoneman/sync#856]
how to embed the youtube TV window on the main cytu.be channel list?
so i can change the channels and Watch TV on ONE single PAGE.

1. Home page
- UI Bring “the Video” module on Home Page. To be embedded near the Channels List
- Hide # Connected
- Hide Chat module, Hide Poll module
2. Admin page: https://cytu.be/account/channels
- UI add Edit Playlist button for every channel
- only admin can add/remove channels & modify all playlists
DREAMS:
- channel admins can manage only certain channels playlists (to be added later)
- the Channel List to become Channel Grid, cable box like see Pluto.tv  (to be added later)
- iOS and Android Apps (to be added later)
Thank You so much!

![main page - watch tv and change channels](https://user-images.githubusercontent.com/4306109/78078805-bab91300-735f-11ea-8450-126e9cb8f6cd.png)
![pluto](https://user-images.githubusercontent.com/4306109/78078807-bb51a980-735f-11ea-993a-5e79c459a5f8.png)
![admin panel - edit channels and playlists copy](https://user-images.githubusercontent.com/4306109/78078810-bc82d680-735f-11ea-8521-138984caf2f1.jpg)

**Comment by calzoneman** [comment]
It looks like the features you requested here are targeted towards a different type of site -- CyTube is more focused on user generated content/channels whereas your proposal sounds more like a "curated" (for lack of a better term) site where a small group of admins organizes content for viewers and optimizes the user experience of interacting with it like a TV.

The changes probably aren't super difficult (except making mobile apps...), but it doesn't really match the direction I'm taking the project and wouldn't be something I'm able to maintain right now.  CyTube is released under a permissive license which welcomes users to create their own "forks" that are customized to their needs.

**Comment by antonpictures** [comment]
Great, Thank You for your answer.
