### ISSUE TITLE
The Disappearance of Xaekai (2020) by Shitposter Studios, coming to a theater near you

### ISSUE THREAD

**Issue by antonpictures** [calzoneman/sync#857]
The gentleman Xaekai offered me to install cytu.be for $20 on my AWS account, then he disappeared. I hope you are healthy Sir. Will you still do it?

**Comment by Xaekai** [comment]
Sorry, I forgot to check back on Keybase.

I thought this request you made was what it said on the tin, to login into your AWS and get you a basic CyTube installation up and running.

Instead you immediately asked me to turn CyTube into a TV Station, with a TV Guide interface on the index. Once you recurse everything such a request prerequisites, the scale of the request has increased by three orders of magnitude.

To me these are completely separate distinct activities, and I refuse to be captured by conflation. So I was waiting for your complete "TV Channel website" specifications before getting back to you, then got distracted with my own sufff.
