### ISSUE TITLE
unable to register users

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#86]
using:
CentOS 6.4
node.js 0.10.5
MySQL 5.1.69

threw the following warnings when running 'npm install':
npm WARN package.json methods@0.0.1 No README.md file found!
npm WARN engine formidable@1.0.13: wanted: {"node":"<0.9.0"} (current: {"node":"v0.10.5","npm":"1.2.18"})

../src/mysql_bindings_result.cc: In static member function ‘static MysqlResult::fetch_options MysqlResult::GetFetchOptions(v8::Localv8::Object)’:
../src/mysql_bindings_result.cc:235: warning: missing initializer for member ‘MysqlResult::fetch_options::results_as_array’
../src/mysql_bindings_result.cc:235: warning: missing initializer for member ‘MysqlResult::fetch_options::results_nest_tables’
../src/mysql_bindings_result.cc: In static member function ‘static v8::Handlev8::Value MysqlResult::FetchAll(const v8::Arguments&)’:
../src/mysql_bindings_result.cc:461: warning: missing initializer for member ‘MysqlResult::fetch_options::results_as_array’
../src/mysql_bindings_result.cc:461: warning: missing initializer for member ‘MysqlResult::fetch_options::results_nest_tables’
../src/mysql_bindings_result.cc: In static member function ‘static v8::Handlev8::Value MysqlResult::FetchRowSync(const v8::Arguments&)’:
../src/mysql_bindings_result.cc:720: warning: missing initializer for member ‘MysqlResult::fetch_options::results_as_array’
../src/mysql_bindings_result.cc:720: warning: missing initializer for member ‘MysqlResult::fetch_options::results_nest_tables’

I'm able to fire up sync, create a room, chat as a guest user but if I want to register a user it gives an error "something went wrong"

**Comment by calzoneman** [comment]
Anything in error.log or printed to the console?  It sounds like the database connection is failing.

**Comment by calzoneman** [comment]
Please note that this software doesn't create the database or database user for you, it only creates the tables needed given the database info.

You need to set up a database user, create a new database and give this user full permissions on the database, and then put the appropriate database details into `config.js`.  I use phpMyAdmin to do this, as it is more convenient than using the MySQL command line.

**Comment by calzoneman** [comment]
Ah, tried a fresh installation and found the problem.  A while back I updated the login system, and existing installations could apply a patch to migrate, but I never patched the initial generation.

You can either update, drop your `registrations` table and restart to regenerate it, or run the following SQL:

``` SQL
ALTER TABLE `registrations` ADD `session_hash` VARCHAR( 64 ) NOT NULL ,
ADD `expire` BIGINT NOT NULL
```
