### ISSUE TITLE
YouTube free movies video streaming issue

### ISSUE THREAD

**Issue by antonpictures** [calzoneman/sync#864]
An error occurred. Please try again later. (Playback ID: Ns7_ZMklG76xsnC6) 
none of Youtube Free Movies below work embedding. Why?
https://www.youtube.com/feed/storefront?bp=kgEmCGQSIlBMSFBUeFR4dEMwaWJWWnJUMl9XS1dVbDJTQXhzS3VLd3iiBQIoAg%3D%3D

Thank You

**Comment by calzoneman** [comment]
Please check if https://github.com/calzoneman/sync/wiki/Troubleshooting-common-issues-in-the-browser#youtube-player-shows-an-error-occurred-please-try-again-later answers your question.
