### ISSUE TITLE
Feature request: Bandcamp embeds

### ISSUE THREAD

**Issue by iatenothingbutriceforthreedays** [calzoneman/sync#868]
Would love to embed albums + tracks from bandcamp.com!

hope it won't be too hard: https://get.bandcamp.help/hc/en-us/articles/360013561254-How-do-I-create-a-Bandcamp-embedded-player-

**Comment by AssTractionHero** [comment]
They do have an API, although I'm technically ignorant, and I don't know how difficult it would be to implement into CyTube:

https://bandcamp.com/developer

**Comment by iatenothingbutriceforthreedays** [comment]
I think that API is for the server – for doing stuff like account management or tracking stats or whatever. Unlike Youtube and Soundcloud, it looks like Bandcamp has no JS API for controlling the embedded player. It might be possible to find a hacky way to control playback but i haven't figured it out.

**Comment by iatenothingbutriceforthreedays** [comment]
btw, i'd be more motivated to work on this myself if i could get the sync client running locally, but so far i can't. I cloned the repo, is there a way to point that at the cytu.be server without having to run my own server for dev?

**Comment by calzoneman** [comment]
>it looks like Bandcamp has no JS API for controlling the embedded player. It might be possible to find a hacky way to control playback but i haven't figured it out.

In that case we won't be able to support it, unfortunately.

**Comment by calzoneman** [comment]
GitHub ate my comment when I clicked close.

>it looks like Bandcamp has no JS API for controlling the embedded player. It might be possible to find a hacky way to control playback but i haven't figured it out.

In that case, unfortunately, we won't be able to support it.
