### ISSUE TITLE
Feature: Show thumbnail as poster when playing audio only files

### ISSUE THREAD

**Issue by Crydsch** [calzoneman/sync#870]
We have been using CyTube for ages and its awesome! :D

Especially the raw/selfhosted media feature is used a lot.
When adding .mp3 files we would like to see a poster image.
Maybe this could be done by using the existing thumbnail specified in the .json?

We would love to see such a feature.

**Comment by Xaekai** [comment]
Using the thumbnail in the CyTube-specified JSON format for custom media as a surrogate video feed when the media consists of audio only definitely seems within scope. :ok_hand:

**Comment by Xaekai** [comment]
Just to confirm, for my own peace of mind if nothing else, there are no showstoppers and it's possible:
* MDN confirms video element can be used for [audio only](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Usage_notes).
* [VideoJS surfaces the relevant API](https://github.com/videojs/video.js/blob/master/docs/guides/player-workflows.md#dealing-with-the-source-or-the-poster-on-the-player)

**Comment by Piruruk-tan** [comment]
I agree, I want this feature!  Would be great!

**Comment by calzoneman** [comment]
I think this and #535 are duplicates, but I'm going to close #535 in favor of this one because supporting this in custom media manifests seems more viable than extracting the image from an audio file.

**Comment by Xaekai** [comment]
Resolved in pending CyTube 3.90-rc release.

You may see a working example [here](https://resources.pink.horse/js/cytube.song.poster.example.json).
