### ISSUE TITLE
Adding admin as channel mod produces error. [Bug]

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [calzoneman/sync#872]
To replicate, just add an site administrator as an ranked user in a channel.

This can be 100% ignored and is not a priority, but figured since I noticed it I'd put it here so I don't forget to look at it later.

`Updating user rank failed: You can't promote or demote someone with equal or higher rank than you.`

The desired action does work though, so again, there's no priority in this.

**Comment by calzoneman** [comment]
I think I'm misunderstanding what makes this a "bug".  You are intentionally prevented from changing the rank of someone who has a higher effective rank than you (where effective rank = max(account rank, channel rank, leader rank)).

What is the "desired action"?

**Comment by ZizzyDizzyMC** [comment]
I guess I should have been more clear, I created a channel and set Xaekai as a channel administrator in my channel.  This produces an error up top, however it still places Xaekai as a channel admin.  So the desired action (Set site admin as channel admin, so they have the usercolor) still works.

**Comment by calzoneman** [comment]
Does it persist if you refresh the page?  I actually suspect it's not updating anything but just missing a return before sending you the updated rank.

**Comment by calzoneman** [comment]
Confirmed my suspicion it was a UI edge case and did not actually result in improperly updating the rank database.

**Comment by ZizzyDizzyMC** [comment]
You're right it was UI only, though this means I legit can't add a site admin as a channel mod - the admin would have to set themselves as mod / admin of the channel in order to receive the name color.
But it's good to know that UI bug is fixed.

**Comment by calzoneman** [comment]
Rank assignment is done by the max calculation I described previously so
even if you were to manually insert a database row for the channel admin
rank, the site admin rank would take priority.

Site admins have their own mechanism to borrow different ranks and change
name color but it's temporary (session local).

**Comment by calzoneman** [comment]
Fixed in latest release
