### ISSUE TITLE
Feature request: List percentage video viewed

### ISSUE THREAD

**Issue by choltz95** [calzoneman/sync#875]
Great project - couldn't see a dup issue & thought I would just throw this out there: 
listing the current proportion of video watched alongside the video/channel.

Sometimes I see a video & channel listed that I'm interested in, but I don't typically want to enter
into the middle/end of the video. Having the above would save a couple clicks.

Not sure what this would generally entail (e.g. recovering current time & total video duration), 
but at least for youtube it looks like there is some api support:
https://stackoverflow.com/questions/11775207/calculate-percentage-of-youtube-video-viewed-with-api

**Comment by calzoneman** [comment]
Dupe of https://github.com/calzoneman/sync/issues/709 (not that I blame you -- it doesn't come up under the search keywords you might expect).

**Comment by choltz95** [comment]
Perfect - thanks!
