### ISSUE TITLE
Getting a "Don't have permission to download video" But My Media Player Can Stream/Download It.

### ISSUE THREAD

**Issue by Bj007pro** [calzoneman/sync#880]
![image](https://user-images.githubusercontent.com/24400879/86987605-92f10b00-c1ea-11ea-9e50-3c96ae8922b7.png)
I am not too sure what the difference is, but my media player (PotPlayer) can stream the links from the site that I use.

**Comment by calzoneman** [comment]
I have just added an FAQ entry for this: https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#why-am-i-getting-an-error-message-access-to-the-link-was-denied-even-though-it-plays-correctly-for-me.

Please reference that to answer your question.
