### ISSUE TITLE
How to Enable Raw Video?

### ISSUE THREAD

**Issue by campbell910** [calzoneman/sync#886]
I have installed ffmpeg to my server and so far that is the only kind of possible documentation that I can find about this issue.

How to enable raw video?

Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x ] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ x] Disabling all browser extensions
  - [x ] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? Unable to add raw video despite ffmpeg being on server.
  - What happens? Error Raw file playback is not enabled on this server
  - What do you expect to happen instead? Raw videos to work

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Ubuntu 18.04
  - **Web Browser (Firefox / Chrome / Other):** Chrome/Safari/Firefox
  - **Error Messages Displayed:** Error Raw file playback is not enabled on this server
  - **Screenshot of JavaScript Console:**
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [ x] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [ x] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [x ] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem? Raw Videos will not add
  - What happens? Error Raw file playback is not enabled on this server
  - What do you expect to happen instead? 
  
### System Information ###

  - **Operating System:** Ubuntu 18.04
  - **Node Version:** _(run `node -v`)_ 14.5.0
  - **CyTube Version:** _(displayed at startup)_
  - **Error Messages Displayed:**

**Comment by calzoneman** [comment]
Have a look at the relevant configuration: https://github.com/calzoneman/sync/blob/3.0/config.template.yaml#L181-L188

Edit that and restart your server, and if you're still having problems please clarify them here.

**Comment by campbell910** [comment]
Done, thank you.
