### ISSUE TITLE
Detect age restricted videos and block them from being queued because youtube sucks

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#891]
https://support.google.com/youtube/answer/2802167?hl=en

>What happens if content is age-restricted?

>Age-restricted videos are not viewable to users who are under 18 years of age or logged out. Additionally, age-restricted videos cannot be watched on most third-party websites. Viewers who click on an age-restricted video on another website, such as an embedded player, will be redirected to YouTube, where they will only be able to view the content when signed-in and over 18. This will help ensure that no matter where content is discovered, if a video is hosted by YouTube it will only be viewable by the appropriate audience.

**Comment by Xaekai** [comment]
It would probably be wise to mention Google's Fault on this matter in the wiki and link the wiki in the error message presented on site to minimize needless inquiries from disgruntled users.

**Comment by calzoneman** [comment]
Closed via https://github.com/calzoneman/sync/pull/894
