### ISSUE TITLE
Google Drive lookup failed

### ISSUE THREAD

**Issue by dinatural** [calzoneman/sync#893]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [ X] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ X] Disabling all browser extensions
  - [ X] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? When adding a Google Drive link
  - What happens? Get red box error with text "Google Drive lookup failed for ..."
  - What do you expect to happen instead? Adding the link to the queue

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Linux Ubuntu 20.04.
  - **Web Browser (Firefox / Chrome / Other):** Firefox
  - **Error Messages Displayed:** redbox error
  - **Screenshot of JavaScript Console:** 
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [ X] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [ X] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [ X] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem? When adding a Google Drive link
  - What happens? Get red box error with text "Google Drive lookup failed for ..."
  - What do you expect to happen instead? Adding the link to the queue
  
### System Information ###

  - **Operating System:** Linux Ubuntu 20.04.01
  - **Node Version:** _(run `node -v`)_ tried with LTS v14.15.2 and v15.4.0
  - **CyTube Version:** _(displayed at startup)_ v.3.74.1
  - **Error Messages Displayed:** no log error, only red box

**Comment by calzoneman** [comment]
I don't support google drive anymore, if it works it works, if it doesn't
it doesn't.

https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#what-should-i-use-instead-of-google-drive

**Comment by dinatural** [comment]
Okay thanks for the quick reply, I think it's great software, I was just
trying to install it on my own server. Keep up the good work!

**Comment by calzoneman** [comment]
Sure, thanks for understanding.
