### ISSUE TITLE
Google drive userscript doesn't like multiple google accounts.

### ISSUE THREAD

**Issue by Renari** [calzoneman/sync#896]
### Description of the Problem ###
  - What triggers the problem? Attempting to use the google drive userscript while logged into multiple google accounts.
  - What happens? The player never loads and the script crashes with the following stack trace.
![image](https://user-images.githubusercontent.com/1839179/104147487-7ce02500-539c-11eb-9883-65e526242530.png)
  - What do you expect to happen instead? The video plays.

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** W10
  - **Web Browser (Firefox / Chrome / Other):** Brave
  - **Error Messages Displayed:** None
  - **Screenshot of JavaScript Console:**
![image](https://user-images.githubusercontent.com/1839179/104147525-b2850e00-539c-11eb-99f7-4b1dac6ebdd8.png)

Here's a sample response where I removed my information:
[response.txt](https://github.com/calzoneman/sync/files/5794024/response.txt)

Strangely enough I was getting the same response in an incognito window while not logged into a google account.

**Comment by calzoneman** [comment]
Hello,

I don't provide support for Google Drive anymore.  Please refer to https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#what-should-i-use-instead-of-google-drive for alternatives.
