### ISSUE TITLE
SocketIO is significantly out of date

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#899]
Version 3 is out, and it brings a new wildcard event emitter which would be super handy for simplifying the bot.

**Comment by calzoneman** [comment]
It warrants investigation whether socket.io 3.0 is backwards compatible for existing clients or not.  If it's a breaking change, I'd be tempted to just go ahead and migrate to plain uWebSockets.js instead.

**Comment by calzoneman** [comment]
socket.io 3 uses engine.io 4 which is a breaking protocol change, so this will definitely break existing socket.io clients.

**Comment by calzoneman** [comment]
Apparently socket.io 4 is already out now.  I need to check if it has any backwards compatibility for 2.x clients.

**Comment by Xaekai** [comment]
I was surprised you didn't bump it up to 2.4.1 in the meantime when you did that recent dependency bump.

It does look like there is some sort of compat flag
https://socket.io/docs/v3/server-initialization/#allowEIO3

**Comment by calzoneman** [comment]
>I was surprised you didn't bump it up to 2.4.1 in the meantime when you did that recent dependency bump.

That was because they made breaking changes to the server initialization that I didn't feel like fixing at the time.
