### ISSUE TITLE
sitewide moderation

### ISSUE THREAD

**Issue by coconono** [calzoneman/sync#90]
it would be cool if there was a SQL table that that all chan_NAME_ranks inherited on creation. 

This way I can designate user accounts to have automatic moderation powers on a room when they are created. right now I have to perform a SQL table update like this:

``` mysql
update chan_NAME_ranks set rank='255' where name='coconono';
```

and then refresh the room page for it to take effect. 

if I can update this table from within the Sync web interface, that would be dandy.

**Comment by calzoneman** [comment]
This is what the `global_rank` field is for in the `registrations` table.  When calculating a user's rank, the maximum of the user's channel rank and global rank is used.

``` SQL
UPDATE registrations SET global_rank=255 WHERE name='coconono'
```
