### ISSUE TITLE
Feature: Batch registration of videos to playlist

### ISSUE THREAD

**Issue by eggplants** [calzoneman/sync#909]
I would like to see the ability to add to the playlist in batches.
Specifically, I'd like to be able to give the URL as a comma-separated string.
e.g.) `https://www.youtube.com/watch?v=-8OqFcLyA8o,https://www.youtube.com/watch?v=XBM40-Aj9ZA,...`

**Comment by calzoneman** [comment]
You can already do this in that exact format...have you tried it?

**Comment by eggplants** [comment]
How?

**Comment by calzoneman** [comment]
The same way you described in the issue description.  Here is an example adding the two videos you used as an example above:

![screenshot-2021-05-11_17-57-38](https://user-images.githubusercontent.com/385672/117902507-79917300-b282-11eb-8684-df8f20e791a6.png)
![screenshot-2021-05-11_17-58-03](https://user-images.githubusercontent.com/385672/117902510-7a2a0980-b282-11eb-8b18-1a2377b36ff7.png)

**Comment by eggplants** [comment]
Thank you so much for your answering for my silly question...
