### ISSUE TITLE
Install fails while building cytubefilters

### ISSUE THREAD

**Issue by mariowo** [calzoneman/sync#927]
## Server Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [✓] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [✓] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [✓] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem?
    Trying to install like explained in the wiki.  
    Clone the repo, run `npm install` as a non-root user. 
  - What happens?
    Installation fails at building cytubefilters with the error stack below.
  - What do you expect to happen instead?
    The installation to finish successfully.
  
### System Information ###

  - **Operating System:** Arch Linux
  - **Node Version:** v14.18.1
  - **CyTube Version:** 3.82.8
  - **Error Messages Displayed:**
  ```
    npm ERR! code 7
    npm ERR! path /opt/cytube/node_modules/cytubefilters
    npm ERR! command failed
    npm ERR! command sh -c node-gyp rebuild
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@7.1.2
    npm ERR! gyp info using node@14.18.1 | linux | x64
    npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
    npm ERR! gyp ERR! UNCAUGHT EXCEPTION 
    npm ERR! gyp ERR! stack Error: Cannot find module 'request'
    npm ERR! gyp ERR! stack Require stack:
    npm ERR! gyp ERR! stack - /usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js
    npm ERR! gyp ERR! stack - /usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js
    npm ERR! gyp ERR! stack - /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
    npm ERR! gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    npm ERR! gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    npm ERR! gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:974:19)
    npm ERR! gyp ERR! stack     at require (internal/modules/cjs/helpers.js:93:18)
    npm ERR! gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:10:17)
    npm ERR! gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
    npm ERR! gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    npm ERR! gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:950:32)
    npm ERR! gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    npm ERR! gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:974:19)
    npm ERR! gyp ERR! System Linux 5.10.63-1-lts
    npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd /opt/cytube/node_modules/cytubefilters
    npm ERR! gyp ERR! node -v v14.18.1
    npm ERR! gyp ERR! node-gyp -v v7.1.2
    npm ERR! gyp ERR! Node-gyp failed to build your package.
    npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
  ```

**Comment by calzoneman** [comment]
Hi,

It seems you're using a rather old version of node.js as far as Arch Linux is concerned.  I spun up a fresh Arch image in Docker, installed nodejs and npm, cloned the repo, and npm install succeeded as expected with these versions:

```
[root@4e737b9234ff sync]# node -v
v16.11.1
[root@4e737b9234ff sync]# npm -v
8.1.3
```

In particular, the error message you're seeing refers to dependency within node-gyp itself, which was [changed several months ago upstream](https://github.com/nodejs/node-gyp/commit/e81602ef55023cc8ffeebc5509a9a8649d60434d).  Thus, I don't have any control over fixing your issue since it seems like you have some kind of inconsistent/outdated installation of the nodejs/npm/node-gyp tooling.

I'd recommend you update your system to the latest versions of these tools and then try again.

**Comment by mariowo** [comment]
Thank you! Turns out I had nodejs-lts-fermium installed.
