### ISSUE TITLE
Cytube channel playing videos when room is empty

### ISSUE THREAD

**Issue by Frocto** [calzoneman/sync#929]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  - [ ] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? Closing the cytube tab
  - What happens? The channel continues playing videos
  - What do you expect to happen instead? The channel to stop playing videos

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows 10
  - **Web Browser (Firefox / Chrome / Other):** Chromium
  - **Error Messages Displayed:** 
  - **Screenshot of JavaScript Console:** https://i.imgur.com/KVWHkjO.png
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

**Comment by calzoneman** [comment]
Can you clarify what you mean?  It's expected that the playlist will remain, and that videos will start from the time you left off when you rejoin the channel.

There are known issues where the channel may stay loaded even after all users leave and continue advancing the timer; if that's the case you'll just need to give me the channel name so I can force-unload it.

**Comment by Frocto** [comment]
Yes, that's what's happening. The channel is https://cytu.be/r/TheMayaFeyAppreciationStation

**Comment by Frocto** [comment]
That fixed it, thankyou!
