### ISSUE TITLE
Subtitle not showing up for Google Drive videos.

### ISSUE THREAD

**Issue by AragorN8** [calzoneman/sync#933]
Subtitles stopped showing from Google Drive videos since this Monday. The option for selecting the subtitle doesn't show at all as shown [here](https://imgur.com/L65NMjp) , but it works in the [Google Drive player](https://imgur.com/gKB1WNE).

Tried videos that showed subtitles before, even different browsers. No success.

**Comment by calzoneman** [comment]
Google Drive is no longer officially supported and hasn't been for quite some time: https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#why-dont-you-support-google-drive-anymore

Closing as wontfix.

**Comment by Xaekai** [comment]
This particular issue was a side-effect of the elimination of legacy Node features and Babel transpilation oddities. It is resolved on site.
