### ISSUE TITLE
Video player not displaying subtitle on videos hosted on google drive

### ISSUE THREAD

**Issue by afornagieri** [calzoneman/sync#934]
In the browser I can see the option to activate subtitles, in the channel this option does not appear in the video player

I'm not using any software to embed the subtitles, I'm using the native functionality of google drive.
https://support.google.com/drive/answer/1372218?hl=en&co=GENIE.Platform%3DDesktop

**Comment by calzoneman** [comment]
See https://github.com/calzoneman/sync/issues/933

Closing wontfix.

**Comment by Xaekai** [comment]
Resolved.
