### ISSUE TITLE
Moderators' actions log visible for channel owners

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#94]
It would come in handy to detect abusing moderators. That's the suggestion from http://synchtube.6irc.net/r/ponenyymit

**Comment by calzoneman** [comment]
What information are you looking for besides kick/ban logs?

**Comment by ghost** [comment]
playlist interactions, mostly

**Comment by calzoneman** [comment]
That would spam the logs beyond belief.  I would encourage people not to give moderator power out so freely if this is an issue, since open queue allows finer control over what can be done (individual options for move/queue next/delete/skip to)

**Comment by ghost** [comment]
I guess you are right.
