### ISSUE TITLE
Adding Twitch clips or VODs fail with "Client ID not set for Twitch API"

### ISSUE THREAD

**Issue by reyaLPelbuoD** [calzoneman/sync#943]
## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [Y] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [Y] Disabling all browser extensions
  - [Y] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem?
Attempting to add a Twitch VOD or clip to the playlist (e.g. https://www.twitch.tv/videos/1456199895 or https://www.twitch.tv/grandpoobear/clip/VenomousCrowdedCaterpillarRiPepperonis)
  - What happens?
Cytube displays the following error message: "Client ID not set for Twitch API" and the Twitch media does not get added to the playlist
  - What do you expect to happen instead?
For the selected Twitch media to be added to the playlist

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows 11
  - **Web Browser (Firefox / Chrome / Other):** Edge
  - **Error Messages Displayed:** Client ID not set for Twitch API
  - **Screenshot of JavaScript Console:** 
![jsConsole](https://user-images.githubusercontent.com/103752916/163573160-de25da55-83ac-4c0f-a764-281f8057427e.png)

First time creating an issue on GitHub, so sorry if I missed something obvious in that regard.

**Comment by calzoneman** [comment]
Which instance are you using? Twitch banned cytu.be a couple years ago, but
I thought we added a specific error for that.

**Comment by reyaLPelbuoD** [comment]
I'm sorry, but I don't know what you mean by instance. I'm using cytu.be through https://cytu.be/ if that's what you're asking.

**Comment by calzoneman** [comment]
Yes, by instance I meant which website are you using (there are multiple websites using the source code from this repo and the many forks with individual customizations).

Unfortunately, twitch.tv blocks embedding from cytu.be due to alleged terms of service violations, which I haven't bothered with appealing, so the twitch.tv support in this repo applies ONLY to the third-party websites using the same code.  Sorry for the inconvenience.

**Comment by reyaLPelbuoD** [comment]
No worries, I understand that it is outside of your control with Twitch being Twitch, it's just I didn't think that's what the error message "Client ID not set for Twitch API" was trying to convey. I'll close the issue now, but thank you for taking your time explaining this to me.
