### ISSUE TITLE
Database Initial Connection Error

### ISSUE THREAD

**Issue by Raintrees25** [calzoneman/sync#949]
## Server Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [X] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [X] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [X] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem?
    -- _Fresh install, after setting up MySQL and editing config.yaml, I try 'node index.js' and I receive a Database Connection Error_. (Below)
  - What happens?
    -- _Database Connection Error, script kicks me out._
  - What do you expect to happen instead?
    -- _Database connects, spins up cytube._
      
### System Information ###

  - **Operating System:** Ubuntu 21.10
  - **Node Version:** v16.16.0 (with npm 8.11.0)
  - **CyTube Version:** N/A
  - **Error Messages Displayed:**

[ERROR] database: Initial database connection failed: Error: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/srv/-MyDir-/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/srv/-MyDir-/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/srv/-MyDir-/node_modules/mysql/lib/Connection.js:116:18)
    at /srv/-MyDir-/node_modules/knex/lib/dialects/mysql/index.js:56:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/srv/-MyDir-/node_modules/knex/lib/dialects/mysql/index.js:51:12)
    at create (/srv/-MyDir-/node_modules/knex/lib/client.js:237:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Raintrees25** [comment]
Update: I was able to fix this issue by updating the MySQL - Server: paramater from 'localhost' to '127.0.0.1'

Any idea why?

**Comment by Raintrees25** [comment]
Update: I was able to fix this issue by updating the MySQL - Server: parameter in config.yaml from 'localhost' to '127.0.0.1'

Any idea why?

**Comment by calzoneman** [comment]
Well, from the error message:

>`[ERROR] database: Initial database connection failed: Error: connect ECONNREFUSED ::1:3306`

It's trying to connect to `::1` which is an IPv6 loopback address.  I'd guess that your MySQL server was only configured to listen on `127.0.0.1` (IPv4 loopback), but when CyTube tried to connect to `localhost`, it got resolved to `::1`, and so the connection failed.

Sadly this is one of the many pitfalls of IPv4+IPv6 dual stack systems.
