### ISSUE TITLE
Error: Cannot find module 'node:fs/promises'

### ISSUE THREAD

**Issue by sorajhin** [calzoneman/sync#955]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Server Problem ##

_If your issue is related to using the website and not about running a server, you can remove this section._

**Please confirm whether you've tried the following debugging steps:**

  - [ Y] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [ Y] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [ Y] Restarted the server
  
### Description of the Problem ###

  - What triggers the problem? node index.js
  - What happens? Unable to start server
  - What do you expect to happen instead? Web Server started
  
### System Information ###

  - **Operating System:** Linux | Ubuntu 20.04.5 LTS
  - **Node Version:** _(run `node -v`)_
$ node -v
v12.22.12

  - **CyTube Version:** _(displayed at startup)_ [INFO] server: Starting CyTube v3.84.0
  - **Error Messages Displayed:**
FATAL: Failed to require() lib/main.js
Possible causes:
  * You haven't run `npm run build-server` to regenerate the runtime
  * You've upgraded node/npm and haven't rebuilt dependencies (try `npm rebuild` or `rm -rf node_modules && npm install`)
  * A dependency failed to install correctly (check the output of `npm install` next time)
Error: Cannot find module 'node:fs/promises'
[config.zip](https://github.com/calzoneman/sync/files/9851284/config.zip)

**Comment by calzoneman** [comment]
Node v12 is end of life and no longer supported upstream. Please install a
currently supported version of node, such as v16 LTS: https://nodejs.org/en/
.

**Comment by sorajhin** [comment]
oh my .... Thanks @calzoneman!! I didn't notice I was using an older version of Node. Thanks! will continue with setting up my server now!
