### ISSUE TITLE
Vimeo Embeds Blocked [Likely third-party issue]

### ISSUE THREAD

**Issue by Saberleo456** [calzoneman/sync#960]
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [ x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [ ] Disabling all browser extensions
  - [ x] Using a clean channel with no customizations
  
### Description of the Problem ###

Vimeo embeds mostly are broken, using the embed iframe causes a white square in the video frame. Sometimes it is possible that the embed loads anyway, but this is explained in the reproduction below.

After checking using developer tools, the iframe returns a 403 error. Digging deeper into it, the blocked request is a result of a referrer link to cytube. When the iframe does successfully load, the request no longer has a cytube referrer link in it.

Request that fails:
https://player.vimeo.com/video/770989825/config?autopause=0&background=0&badge=0&byline=0&bypass_privacy=1&collections=0&color=ff9900&context=embed_playlist.1973832&controls=1&default_to_hd=0&external_embed=1&force_embed=1&fullscreen=1&h=013a9c41ac&like=0&logo=0&loop=0&outro_new=0&playbar=1&portrait=0&referrer=https://cytu.be/&share=0&title=1&transparent=0&volume=1&watch_later=0&s=398edae27b780f912bc728f99f38cb5d4c38b5f8_1670070206

Request that succeeds:
https://player.vimeo.com/video/770989825/config?autopause=0&background=0&badge=0&byline=0&bypass_privacy=1&collections=0&color=ff9900&context=embed_playlist.1973832&controls=1&default_to_hd=0&external_embed=1&force_embed=1&fullscreen=1&h=013a9c41ac&like=0&logo=0&loop=0&outro_new=0&playbar=1&portrait=0&share=0&title=1&transparent=0&volume=1&watch_later=0&s=398edae27b780f912bc728f99f38cb5d4c38b5f8_1670070206

embed code used: <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://vimeo.com/event/1973832/embed/6d686c5e65" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div>

### System Information ###

  - Windows 10
  - Vivaldi
  - 403 embed error

**Comment by calzoneman** [comment]
Yeah, you won't be able to use Vimeo embeds on `cytu.be` as they've blocked the domain from embedding (long story).  It should still work if you use a different CyTube instance (or host your own).
