### ISSUE TITLE
Global and example filters

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#97]
I've added two new filters in channel.js, however they only work on new channels because of existing chandumps. I think that owners should have 100% control on their filters, but on the other hand [spoiler] tags and such are really useful and it would be nice to use them globally.

I'd suggest two filter sets: global (independent from chandumps) and a default one for new channels (that ends in initial chandumps, a mere examples of filters usage).

**Comment by calzoneman** [comment]
Is there a particular reason that inline spoilers are needed as opposed to the builtin `/sp` command?  I could try to make the dump loader not overwrite any existing default filters, but it seems needlessly complex to make a distinction between global and channel-only filters.

**Comment by ghost** [comment]
Imageboard users are in the majority of CyTube users, and they often use midtext [spoilers] in their chanspeak. /sp is kinda unnatural to them.

**Comment by calzoneman** [comment]
Would it suffice to apply the defaults in channel.js to every channel instead of just new ones?  People could still disable them with the checkbox, but would be unable to remove them.

**Comment by ghost** [comment]
Sure.

**Comment by calzoneman** [comment]
Sorry for the long turnaround, been busy the past few days.

**Comment by ghost** [comment]
It's alright, you've already done enough to receive a medal. All those addicted synchtubers... They should worship you ;D
