### ISSUE TITLE
[Feature Request] URL Blacklist

### ISSUE THREAD

**Issue by FlashSkyNews** [calzoneman/sync#973]
An URL/Word in Title Blacklist would be amazing. This would prevent many unwanted things without being 24/7 in the Channel.

**Comment by calzoneman** [comment]
Sorry that I didn't reply to this until now.  Could you clarify a little more about the problem you're trying to solve and what you were imagining here?  When you talk about URLs, are you meaning in chat, in video queues, in something else?

**Comment by Xaekai** [comment]
My interpretation is they want the ability to block/fail queuing of videos based on the presence strings/regex set by the channel admins.

I think this would be trivial for users set on being obnoxious to get around, making the feature rather useless.

**Comment by calzoneman** [comment]
Closing for lack of clarity and no response in 1 month, if you still desire this feature please comment with more details about what is being asked for and why.
