### ISSUE TITLE
Reporting underage material

### ISSUE THREAD

**Issue by Ttom77** [calzoneman/sync#979]
Is there an e-mail address I can report rooms that stream CSAM (child sexual abuse material).

Thank you,
Tom

**Comment by calzoneman** [comment]
Hello,

This is the issue tracker for software that is used by multiple websites; to report the content being shown on those website, please use the Contact link in the footer of the page where you found the inappropriate content to contact the administrators of the website.

**Comment by Ttom77** [comment]
I do do that. However this particular site has this statement…..

“We are not affiliated with cytube.xyz.
Please do not contact the cytu.be admins to report channels on cytube.xyz. We do not have admin privileges on the server, nor do we know of it, so there’s nothing we can do about it.”
 
I did come across another way to obtain a contact and they banned it.
