### ISSUE TITLE
Is sync compatible with `X-Content-Type-Options?`

### ISSUE THREAD

**Issue by Zankaria** [calzoneman/sync#982]
I'm hosting a server over https://tv.leftypol.org, and I couldn't really find any documentation regarding this project's compatibility with the `X-Content-Type-Options` header (nearest thing: https://github.com/calzoneman/sync/issues/738)
Is sync known to break if this header is set by a reverse-proxy server? Is it known to work? Or nobody has tried to find out?

**Comment by calzoneman** [comment]
Is there a specific problem you're having with it?  I'm not aware of any positive or negative support for it.

**Comment by Zankaria** [comment]
Mine is more of a precautionary question. I noticed that `cytu.be` doesn't use `X-Content-Type-Options`, and as such I wondered if it was due to the software being incompatible, or simply because nobody thought of using it.

> I'm not aware of any positive or negative support for it.

Damn. Well, as long as sync does include the proper `Content-Type` header, it should just work.
Which poses the question: does sync include it?

**Comment by calzoneman** [comment]
As far as I'm aware, the content-type header is correct; if you find an example where it's not you could file a bug for that.

However it raises the question of what you are trying to solve, sync itself is not a media CDN, the only content it is serving is HTML pages and some static assets like images, JavaScript, and CSS that are checked into the repository or generated at installation time.

**Comment by Zankaria** [comment]
Well that solves it for me :+1:

> However it raises the question of what you are trying to solve

Improving site security. Honestly I had relatively little contact with my predecessor and as such I still don't know a number of things about the setup, cytube being one of them.

With that said, thank you for your time :wink:
