### ISSUE TITLE
Demo CyTube  Server

### ISSUE THREAD

**Issue by Onefox** [calzoneman/sync#99]
is the domain with the demo down ? 
"I am hosting a CyTube server at http://cytube.calzoneman.net"

**Comment by ghost** [comment]
It's odd, calzoneman should be already on github about this time.

**Comment by ghost** [comment]
@Onefox 
For the time being you can use http://synchtube.6irc.net or http://tube.420chan.org

**Comment by calzoneman** [comment]
@Onefox my host emailed me informing they nullrouted my IP due to a DDoS

@Czterooki I was travelling today

**Comment by skorotkiewicz** [comment]
my demo server http://synchtube.itunix.eu/
